import assert from 'node:assert/strict';
import '../app/source-page-plan.js';
const P=globalThis.ThreadsPagePlan,measure=(t,s)=>Array.from(t).length*s*.6;
const body='긴 사건의 시작과 전개를 그대로 보존합니다.\n\n끝의 반전도 그대로입니다.';
const plan={originalTitle:'원제',coverTitle:'반전도 그대로',editorial:{templateId:'mint_text',titleEvidence:'끝의 반전도 그대로입니다.'},segments:[{id:'body',kind:'text',selected:true,text:body}],comments:[{id:'c1',selected:true,text:'실제로 확보한 첫 번째 댓글입니다.'},{id:'c2',selected:true,text:'다른 의견의 댓글도 원문대로입니다.'}]};
const p=P.compile(plan,{},measure);
assert.equal(p.titleEvidenceStatus,'matched_source');assert.deepEqual(p.titleEvidenceSourceIds,['body']);
assert.equal(p.typography.bodySize,52);assert.equal(p.typography.bodyLineHeight,78);
const comments=p.pages.filter(p=>p.role==='comments');assert.equal(comments.length,1);
assert(!comments[0].operations.some(o=>o.role==='body'),'Source comments must start on a separate page');
assert(comments[0].operations.filter(o=>o.role==='comment').every(o=>o.size===48&&o.lineHeight===72&&o.weight===400));
assert(comments[0].operations.some(o=>o.kind==='rect'&&o.height===2),'Distinct comments have a visual divider');
assert.deepEqual(p.selectedCommentIds,['c1','c2']);
assert.equal(p.publicationAllowed,false);assert.equal(p.reviewStatus,'needs_review');
assert.equal(P.compile({...plan,editorial:{titleEvidence:'원문에 없는 근거'}},{},measure).titleEvidenceStatus,'needs_review');
const long=P.compile({...plan,comments:[{id:'long',selected:true,text:'긴 댓글 문장입니다. '.repeat(200)}]}, {},measure);
assert(long.pages.filter(p=>p.operations.some(o=>o.role==='comment')).every(p=>p.role==='comments'));
const normalize=t=>t.replace(/\s/g,'');
assert.equal(normalize(long.pages.flatMap(p=>p.operations).filter(o=>o.role==='comment').map(o=>o.text).join('')),normalize('긴 댓글 문장입니다. '.repeat(200)));
console.log('Post foundation: title trace, comment separation, typography and continuation integrity PASS');
