import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import {spawnSync} from 'node:child_process';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),{runCoverReflow,createZipTools}=require('../desktop/reflow-review-covers-run.cjs'),{sha256}=require('../desktop/universal-reproduction.cjs');
const base=await fs.mkdtemp(path.join(os.tmpdir(),'threads-cover-reflow-')),zip=await createZipTools(path.resolve('.'));
const json=async(p,v)=>{await fs.mkdir(path.dirname(p),{recursive:true});await fs.writeFile(p,JSON.stringify(v));};
function png(height,marker){const b=Buffer.alloc(32);Buffer.from('89504e470d0a1a0a','hex').copy(b);b.writeUInt32BE(1080,16);b.writeUInt32BE(height,20);b[24]=marker;return b;}
async function fixture(name){const sourceRoot=path.join(base,name,'source'),destination=path.join(base,name,'dest'),raw=path.join(base,name,'raw'),out=path.join(sourceRoot,'06_자동 제작 결과'),rows=[];
 await json(path.join(raw,'raw.json'),{immutable:'source fixture'});
 for(const [id,variant]of [['paper','paper'],['photo','photo']]){const folder='current/'+id,p=path.join(out,folder),images=[{name:'rendered/slide-001.png',data:png(1920,1)},{name:'rendered/slide-002.png',data:png(700,2)}],plan={ruleVersion:'2026-10-08.2',coverTitle:id,sourceUnits:[{text:'EXACT BODY'}],pages:[{role:'cover',geometry:{old:true}},{role:'body',number:2,operations:[{text:'EXACT BODY'}]}],universalCover:{variant,title:id,context:'',emphasis:'',geometry:{old:true}}};
 await json(path.join(p,'production-plan.json'),plan);for(const image of images){await fs.mkdir(path.dirname(path.join(p,image.name)),{recursive:true});await fs.writeFile(path.join(p,image.name),image.data);}
 await fs.writeFile(path.join(p,'source-bundle.zip'),Buffer.from('immutable source '+id));await fs.writeFile(path.join(p,'cover.html'),'OLD COVER');await fs.writeFile(path.join(p,'other.txt'),'OTHER IMMUTABLE');await json(path.join(p,'fonts','OFL.txt'),{license:'fixture'});
 const preview=await zip.zip([...images,{name:'manifest.json',data:Buffer.from(JSON.stringify({productionPlan:plan,originalTitle:id,renderedPages:2}))},{name:'source-bundle.zip',data:Buffer.from('immutable source '+id)},{name:'cover.html',data:Buffer.from('OLD COVER')}]);await fs.writeFile(path.join(p,'review-preview.zip'),preview);
 rows.push({id,title:id,templateId:'universal_'+variant,status:'generated',ruleVersion:plan.ruleVersion,outputFolder:folder,images:images.map(i=>({name:i.name,sha256:sha256(i.data)})),sourceZipSha256:sha256(Buffer.from('immutable source '+id)),outputSha256:sha256(preview),sourceFingerprint:'OLD-'+id});}
 await json(path.join(out,'status.json'),{reviewRound:'old-round',reproductionContract:'universal-reproduction-v1',inputFolder:raw,processed:3,entries:[...rows,{id:'held',status:'needs_source',outputFolder:null,images:[]}]});
 await json(path.join(sourceRoot,'07_사용자 평가/평가 기록.json'),{schemaVersion:1,recordType:'user_post_quality_feedback',reviewRound:'old-round',evaluations:[]});
 await json(path.join(sourceRoot,'07_사용자 평가/검토 진행.json'),{schemaVersion:1,recordType:'user_review_workflow',reviewRound:'old-round',entries:[]});
 await json(path.join(sourceRoot,'review-current.json'),{reviewRound:'old-round'});
 return {sourceRoot,destination,rawSourceRoots:[raw],reviewRound:'new-round',expected:{entries:3,posts:2,pages:4,paper:1,photo:1,body:2},qaRoot:path.join(base,name,'qa')};}
const renderCover=async({row})=>({data:png(1920,9),geometry:{title:row.title,lines:[row.title],size:132,box:{x:108,y:280,width:864,height:151},width:1080,height:1920}});
try{
 const engine='C:/KJ/Github/Threads/desktop/node_modules/electron/dist/electron.exe';if(process.platform==='win32'&&await fs.access(engine).then(()=>true,()=>false)){const processResult=spawnSync(engine,[path.resolve('desktop/reflow-review-covers-run.cjs'),path.join(base,'missing-config.json'),'--user-data-dir='+path.join(base,'entry-profile')],{windowsHide:true,encoding:'utf8',timeout:5000});assert.equal(processResult.status,1,'Electron CLI must enter its handler and reject missing config rather than silently idle');assert.match(processResult.stderr,/ENOENT/);}
 const config=await fixture('good'),result=await runCoverReflow(config,{renderCover,zipTools:zip}),out=path.join(config.destination,'06_자동 제작 결과'),report=JSON.parse(await fs.readFile(path.join(out,'status.json'))),paper=report.entries.find(r=>r.id==='paper'),photo=report.entries.find(r=>r.id==='photo');
 assert.equal(result.coversReflowed,1);assert.equal(result.bodyImagesReused,2);assert.equal(result.photoCoversReused,1);assert.equal(result.oldPngAndZipHashesUnchanged,true);assert.equal(report.entries.length,3);assert.equal(report.intakeContract,'verified-intake-v1');assert.equal(report.reproductionContract,undefined);assert.equal(report.wholeCollectionRegenerated,false);assert.equal(report.deliveryStatus,'complete');assert.equal(paper.status,'generated');assert.equal(paper.intakeAuditPassed,true);assert.equal(photo.status,'already_done');assert.equal(photo.preservedCurrent,true);
 for(const row of report.entries.filter(r=>r.outputFolder)){const old=path.join(config.sourceRoot,'06_자동 제작 결과',row.outputFolder),fresh=path.join(out,row.outputFolder);assert.deepEqual(await fs.readFile(path.join(old,'source-bundle.zip')),await fs.readFile(path.join(fresh,'source-bundle.zip')));assert.deepEqual(await fs.readFile(path.join(old,row.images[1].name)),await fs.readFile(path.join(fresh,row.images[1].name)));const oldPlan=JSON.parse(await fs.readFile(path.join(old,'production-plan.json'))),newPlan=JSON.parse(await fs.readFile(path.join(fresh,'production-plan.json')));assert.deepEqual(newPlan.pages.slice(1),oldPlan.pages.slice(1));assert.equal(newPlan.ruleVersion,'2026-10-08.2');if(row.id==='photo')for(const name of ['cover.html','production-plan.json','review-preview.zip',row.images[0].name,'other.txt'])assert.deepEqual(await fs.readFile(path.join(old,name)),await fs.readFile(path.join(fresh,name)));}
 assert.notEqual(paper.sourceFingerprint,'OLD-paper');assert.equal(photo.sourceFingerprint,'OLD-photo');const manifest=JSON.parse(Buffer.from((await zip.read(await fs.readFile(path.join(out,paper.outputFolder,'review-preview.zip')))).get('manifest.json')));assert.deepEqual(manifest.productionPlan.pages.slice(1),JSON.parse(await fs.readFile(path.join(out,paper.outputFolder,'production-plan.json'))).pages.slice(1));
 const oldArchive=await zip.read(await fs.readFile(path.join(config.sourceRoot,'06_자동 제작 결과',paper.outputFolder,'review-preview.zip'))),newArchive=await zip.read(await fs.readFile(path.join(out,paper.outputFolder,'review-preview.zip')));for(const name of ['source-bundle.zip',paper.images[1].name])assert.deepEqual(Buffer.from(newArchive.get(name)),Buffer.from(oldArchive.get(name)));
 assert.deepEqual(JSON.parse(await fs.readFile(path.join(config.destination,'intake-complete.json'))).registeredIds,['paper','photo']);
 const compact=await fixture('compact'),compactStatus=path.join(compact.sourceRoot,'06_자동 제작 결과/status.json'),compactReport=JSON.parse(await fs.readFile(compactStatus)),photoRow=compactReport.entries.find(r=>r.id==='photo'),photoFolder=path.join(compact.sourceRoot,'06_자동 제작 결과',photoRow.outputFolder),photoPlan=JSON.parse(await fs.readFile(path.join(photoFolder,'production-plan.json'))),asset=png(800,4),sourceZip=await zip.zip([{name:'assets/photo.png',data:asset}]);
 photoPlan.coverAsset={kind:'original_source',name:'photo.png',sha256:sha256(asset),attribution:'QA Author',license:'CC BY 2.0'};await json(path.join(photoFolder,'production-plan.json'),photoPlan);await fs.writeFile(path.join(photoFolder,'source-bundle.zip'),sourceZip);photoRow.sourceZipSha256=sha256(sourceZip);
 const compactArchive=await zip.read(await fs.readFile(path.join(photoFolder,'review-preview.zip')));compactArchive.set('source-bundle.zip',sourceZip);compactArchive.set('manifest.json',Buffer.from(JSON.stringify({productionPlan:photoPlan})));const compactPreview=await zip.zip([...compactArchive].map(([name,data])=>({name,data})));await fs.writeFile(path.join(photoFolder,'review-preview.zip'),compactPreview);photoRow.outputSha256=sha256(compactPreview);await json(compactStatus,compactReport);
 const compactRender=async({row,html})=>{const input=JSON.parse(html.match(/window.coverInput=(.+?);window.coverResourcesReady=/s)[1]);assert.equal(input.aspectRatio,'square');if(row.id==='photo'){assert.equal(input.variant,'photo');assert(input.imageUrl.startsWith('data:image/png;base64,'));assert.equal(input.credit,'QA Author · CC BY 2.0');}return {data:png(1080,8),geometry:{title:row.title,lines:[row.title],size:128,box:{x:96,y:400,width:888,height:149},glyphBoxes:[{x:96,y:400,width:500,height:128}],width:1080,height:1080,aspectRatio:'square',imageBox:row.id==='photo'?{x:0,y:0,width:1080,height:800,fit:'contain'}:null}};};
 const compactResult=await runCoverReflow({...compact,aspectRatio:'auto'},{zipTools:zip,renderCover:compactRender}),compactNew=JSON.parse(await fs.readFile(path.join(compact.destination,'06_자동 제작 결과/status.json')));
 assert.equal(compactResult.coversReflowed,2);assert.equal(compactResult.photoCoversReused,0);assert.equal(compactResult.bodyImagesReused,2);assert(compactNew.entries.filter(r=>r.outputFolder).every(r=>r.images[0].height===1080&&r.status==='generated'&&r.intakeAuditPassed));
 for(const row of compactNew.entries.filter(r=>r.outputFolder)){
  const folder=path.join(compact.destination,'06_자동 제작 결과',row.outputFolder),plan=JSON.parse(await fs.readFile(path.join(folder,'production-plan.json'))),archive=await zip.read(await fs.readFile(path.join(folder,'review-preview.zip'))),manifest=JSON.parse(Buffer.from(archive.get('manifest.json')));
  assert.equal(plan.pages[0].width,1080);assert.equal(plan.pages[0].height,1080);assert.deepEqual(manifest.productionPlan.pages[0],plan.pages[0]);
 }
 for(const [name,mutate]of [['missing-font',g=>delete g.size],['invalid-glyph',g=>g.glyphBoxes=[{}]],['nonfinite',g=>g.glyphBoxes[0].x=NaN],['wrong-ratio',g=>{g.height=1350;g.aspectRatio='4:5';}],['stretched-photo',g=>g.imageBox={x:0,y:0,width:1080,height:800,fit:'cover'}]]){
  const cfg=await fixture('geometry-'+name);await assert.rejects(runCoverReflow({...cfg,aspectRatio:'square'},{zipTools:zip,renderCover:async args=>{const rendered=await compactRender(args);mutate(rendered.geometry);if(name==='wrong-ratio')rendered.data=png(1350,8);return rendered;}}),/안전 영역|전체 보존/,name+' must fail closed');
 }
 const complete=await fixture('square-complete'),aiFile=path.join(complete.rawSourceRoots[0],'fixture-ai.png'),aiBytes=png(1254,6);aiBytes.writeUInt32BE(1254,16);await fs.writeFile(aiFile,aiBytes);
 const aiAsset={sourceId:'paper',file:aiFile,sha256:sha256(aiBytes),width:1254,height:1254,prompt:'QA-only fictional staging',evidence:'QA-only body context',sourceUrl:'https://example.test/fixture',rightsStatus:'QA fixture only',actualScene:false,generatedForThisTask:true,publicationAllowed:false};
 const completeResult=await runCoverReflow({...complete,aspectRatio:'square',renderer:'square-complete',coverAssets:[aiAsset]},{zipTools:zip,renderCover:async({row,html})=>{
  const input=JSON.parse(html.match(/window.coverInput=(.+?);window.coverResourcesReady=/s)[1]);assert.equal(input.imageKind,row.id==='paper'?'ai-staging':'source');assert(html.includes('fonts/CutGothic-ExtraBold.woff'));if(row.id==='paper')assert(input.imageUrl.startsWith('data:image/png;base64,'));
  if(row.id==='paper'){const changed=Buffer.from(aiBytes);changed[24]=77;await fs.writeFile(aiFile,changed);}
  return {data:png(1080,8),geometry:{title:row.title,lines:[row.title],size:128,box:{x:96,y:400,width:888,height:149},glyphBoxes:[{x:96,y:400,width:500,height:128}],width:1080,height:1080,aspectRatio:'square',imageBox:row.id==='paper'?{x:0,y:0,width:1080,height:1080,fit:'contain'}:null,aiLabel:row.id==='paper'?'AI 연출 이미지':'',photoFallback:false}};
 },onProgress:value=>{if(value.phase==='reflow'&&value.id==='paper')require('node:fs').writeFileSync(aiFile,aiBytes);}});
 assert.equal(completeResult.coversReflowed,2);const completeFolder=path.join(complete.destination,'06_자동 제작 결과/current/paper'),completePlan=JSON.parse(await fs.readFile(path.join(completeFolder,'production-plan.json'))),completeZip=await zip.read(await fs.readFile(path.join(completeFolder,'review-preview.zip')));
 assert.equal(completePlan.universalCover.aiAsset.file,'cover-assets/fixture-ai.png');assert.equal(completePlan.universalCover.aiAssetUsed,true);assert.equal(completePlan.universalCover.credit,'AI 연출 이미지');
 assert.deepEqual(await fs.readFile(path.join(completeFolder,'cover-assets/fixture-ai.png')),aiBytes);assert.deepEqual(Buffer.from(completeZip.get('cover-assets/fixture-ai.png')),aiBytes);assert(completeZip.has('fonts/CutGothic-ExtraBold.woff'));assert(completeZip.has('fonts/OFL-NanumGothic.txt'));
 for(const row of compactNew.entries.filter(r=>r.outputFolder)){const fresh=path.join(compact.destination,'06_자동 제작 결과',row.outputFolder),old=path.join(compact.sourceRoot,'06_자동 제작 결과',row.outputFolder);assert.deepEqual(await fs.readFile(path.join(fresh,row.images[1].name)),await fs.readFile(path.join(old,row.images[1].name)));assert.deepEqual(await fs.readFile(path.join(fresh,'source-bundle.zip')),await fs.readFile(path.join(old,'source-bundle.zip')));}
 const bad=await fixture('changed');await assert.rejects(runCoverReflow(bad,{zipTools:zip,renderCover:async args=>{await fs.writeFile(path.join(bad.rawSourceRoots[0],'raw.json'),'CHANGED');return renderCover(args);}}),/변경|changed/);await assert.rejects(fs.stat(path.join(bad.destination,'intake-complete.json')),{code:'ENOENT'});assert.equal(JSON.parse(await fs.readFile(path.join(bad.destination,'06_자동 제작 결과/status.json'))).deliveryStatus,'fatal');assert(await fs.stat(path.join(bad.destination,'intake-fatal.json')));
 const advancing=await fixture('human-feedback'),advancedFeedback=path.join(advancing.sourceRoot,'07_사용자 평가/평가 기록.json'),humanBytes=JSON.stringify({schemaVersion:1,recordType:'user_post_quality_feedback',reviewRound:'old-round',evaluations:[{note:'Human wrote while covers rendered'}]});const advanced=await runCoverReflow({...advancing,allowUserFeedbackAdvance:true},{zipTools:zip,renderCover:async args=>{await fs.writeFile(advancedFeedback,humanBytes);return renderCover(args);}});
 assert.equal(advanced.advancedUserFeedback.length,1);assert.equal(await fs.readFile(advancedFeedback,'utf8'),humanBytes,'Live feedback must remain untouched for a fresh activation snapshot');
 for(const [name,invalid]of [['deleted',null],['corrupt','{bad'],['other-round',JSON.stringify({schemaVersion:1,recordType:'user_post_quality_feedback',reviewRound:'replacement',evaluations:[]})],['bad-schema',JSON.stringify({schemaVersion:2,recordType:'user_post_quality_feedback',reviewRound:'old-round',evaluations:[]})]]){
  const cfg=await fixture('feedback-'+name),file=path.join(cfg.sourceRoot,'07_사용자 평가/평가 기록.json');await assert.rejects(runCoverReflow({...cfg,allowUserFeedbackAdvance:true},{zipTools:zip,renderCover:async args=>{if(invalid===null)await fs.unlink(file);else await fs.writeFile(file,invalid);return renderCover(args);}}),undefined,name+' must not be a human feedback advance');
 }
 const failure=await fixture('renderer-failure');await assert.rejects(runCoverReflow(failure,{zipTools:zip,renderCover:async()=>{throw Error('renderer fixture failure');}}),/renderer fixture/);assert(await fs.stat(path.join(failure.destination,'06_자동 제작 결과/current/paper/source-bundle.zip')));await assert.rejects(fs.stat(path.join(failure.destination,'intake-complete.json')),{code:'ENOENT'});
 await assert.rejects(runCoverReflow({...config,destination:config.sourceRoot},{zipTools:zip,renderCover}),/원본|source/);
 console.log('Cover reflow: changed cover only, exact body/photo/ZIP preservation, verified completion, source mutation and renderer failures rejected PASS');
}finally{assert(path.resolve(base).startsWith(path.resolve(os.tmpdir())+path.sep));await fs.rm(base,{recursive:true,force:true});}
