import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import {spawnSync} from 'node:child_process';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),{runCoverReflow,createZipTools}=require('../desktop/reflow-review-covers-run.cjs'),{sha256}=require('../desktop/universal-reproduction.cjs');
const base=await fs.mkdtemp(path.join(os.tmpdir(),'threads-cover-reflow-')),zip=await createZipTools(path.resolve('.'));
const json=async(p,v)=>{await fs.mkdir(path.dirname(p),{recursive:true});await fs.writeFile(p,JSON.stringify(v));};
function png(height,marker){const b=Buffer.alloc(32);Buffer.from('89504e470d0a1a0a','hex').copy(b);b.writeUInt32BE(1080,16);b.writeUInt32BE(height,20);b[24]=marker;return b;}
async function fixture(name){const sourceRoot=path.join(base,name,'source'),destination=path.join(base,name,'dest'),raw=path.join(base,name,'raw'),out=path.join(sourceRoot,'06_자동 제작 결과'),rows=[];
 await json(path.join(raw,'raw.json'),{immutable:'source fixture'});
 for(const [id,variant]of [['paper','paper'],['photo','photo']]){const folder='current/'+id,p=path.join(out,folder),images=[{name:'rendered/slide-001.png',data:png(1920,1)},{name:'rendered/slide-002.png',data:png(700,2)}],plan={ruleVersion:'2026-10-08.2',coverTitle:id,sourceUnits:[{text:'EXACT BODY'}],pages:[{role:'cover',geometry:{old:true}},{role:'body',number:2,operations:[{text:'EXACT BODY'}]}],universalCover:{variant,title:id,context:'',emphasis:'',geometry:{old:true}}};
 await json(path.join(p,'production-plan.json'),plan);for(const image of images){await fs.mkdir(path.dirname(path.join(p,image.name)),{recursive:true});await fs.writeFile(path.join(p,image.name),image.data);}
 await fs.writeFile(path.join(p,'source-bundle.zip'),Buffer.from('immutable source '+id));await fs.writeFile(path.join(p,'cover.html'),'OLD COVER');await fs.writeFile(path.join(p,'other.txt'),'OTHER IMMUTABLE');await json(path.join(p,'fonts','OFL.txt'),{license:'fixture'});
 const preview=await zip.zip([...images,{name:'manifest.json',data:Buffer.from(JSON.stringify({productionPlan:plan,originalTitle:id,renderedPages:2}))},{name:'source-bundle.zip',data:Buffer.from('immutable source '+id)},{name:'cover.html',data:Buffer.from('OLD COVER')}]);await fs.writeFile(path.join(p,'review-preview.zip'),preview);
 rows.push({id,title:id,templateId:'universal_'+variant,status:'generated',ruleVersion:plan.ruleVersion,outputFolder:folder,images:images.map(i=>({name:i.name,sha256:sha256(i.data)})),sourceZipSha256:sha256(Buffer.from('immutable source '+id)),outputSha256:sha256(preview),sourceFingerprint:'OLD-'+id});}
 await json(path.join(out,'status.json'),{reviewRound:'old-round',reproductionContract:'universal-reproduction-v1',inputFolder:raw,processed:3,entries:[...rows,{id:'held',status:'needs_source',outputFolder:null,images:[]}]});
 for(const name of ['07_사용자 평가/평가 기록.json','07_사용자 평가/검토 진행.json','review-current.json'])await json(path.join(sourceRoot,name),{fixture:name});
 return {sourceRoot,destination,rawSourceRoots:[raw],reviewRound:'new-round',expected:{entries:3,posts:2,pages:4,paper:1,photo:1,body:2},qaRoot:path.join(base,name,'qa')};}
const renderCover=async({row})=>({data:png(1920,9),geometry:{title:row.title,lines:[row.title],size:132,box:{x:108,y:280,width:864,height:151},width:1080,height:1920}});
try{
 const engine='C:/KJ/Github/Threads/desktop/node_modules/electron/dist/electron.exe';if(process.platform==='win32'&&await fs.access(engine).then(()=>true,()=>false)){const processResult=spawnSync(engine,[path.resolve('desktop/reflow-review-covers-run.cjs'),path.join(base,'missing-config.json'),'--user-data-dir='+path.join(base,'entry-profile')],{windowsHide:true,encoding:'utf8',timeout:5000});assert.equal(processResult.status,1,'Electron CLI must enter its handler and reject missing config rather than silently idle');assert.match(processResult.stderr,/ENOENT/);}
 const config=await fixture('good'),result=await runCoverReflow(config,{renderCover,zipTools:zip}),out=path.join(config.destination,'06_자동 제작 결과'),report=JSON.parse(await fs.readFile(path.join(out,'status.json'))),paper=report.entries.find(r=>r.id==='paper'),photo=report.entries.find(r=>r.id==='photo');
 assert.equal(result.coversReflowed,1);assert.equal(result.bodyImagesReused,2);assert.equal(result.photoCoversReused,1);assert.equal(result.oldPngAndZipHashesUnchanged,true);assert.equal(report.entries.length,3);assert.equal(report.intakeContract,'verified-intake-v1');assert.equal(report.reproductionContract,undefined);assert.equal(report.wholeCollectionRegenerated,false);assert.equal(report.deliveryStatus,'complete');assert.equal(paper.status,'generated');assert.equal(paper.intakeAuditPassed,true);assert.equal(photo.status,'already_done');assert.equal(photo.preservedCurrent,true);
 for(const row of report.entries.filter(r=>r.outputFolder)){const old=path.join(config.sourceRoot,'06_자동 제작 결과',row.outputFolder),fresh=path.join(out,row.outputFolder);assert.deepEqual(await fs.readFile(path.join(old,'source-bundle.zip')),await fs.readFile(path.join(fresh,'source-bundle.zip')));assert.deepEqual(await fs.readFile(path.join(old,row.images[1].name)),await fs.readFile(path.join(fresh,row.images[1].name)));const oldPlan=JSON.parse(await fs.readFile(path.join(old,'production-plan.json'))),newPlan=JSON.parse(await fs.readFile(path.join(fresh,'production-plan.json')));assert.deepEqual(newPlan.pages.slice(1),oldPlan.pages.slice(1));assert.equal(newPlan.ruleVersion,'2026-10-08.2');if(row.id==='photo')for(const name of ['cover.html','production-plan.json','review-preview.zip',row.images[0].name,'other.txt'])assert.deepEqual(await fs.readFile(path.join(old,name)),await fs.readFile(path.join(fresh,name)));}
 assert.notEqual(paper.sourceFingerprint,'OLD-paper');assert.equal(photo.sourceFingerprint,'OLD-photo');const manifest=JSON.parse(Buffer.from((await zip.read(await fs.readFile(path.join(out,paper.outputFolder,'review-preview.zip')))).get('manifest.json')));assert.deepEqual(manifest.productionPlan.pages.slice(1),JSON.parse(await fs.readFile(path.join(out,paper.outputFolder,'production-plan.json'))).pages.slice(1));
 const oldArchive=await zip.read(await fs.readFile(path.join(config.sourceRoot,'06_자동 제작 결과',paper.outputFolder,'review-preview.zip'))),newArchive=await zip.read(await fs.readFile(path.join(out,paper.outputFolder,'review-preview.zip')));for(const name of ['source-bundle.zip',paper.images[1].name])assert.deepEqual(Buffer.from(newArchive.get(name)),Buffer.from(oldArchive.get(name)));
 assert.deepEqual(JSON.parse(await fs.readFile(path.join(config.destination,'intake-complete.json'))).registeredIds,['paper','photo']);
 const bad=await fixture('changed');await assert.rejects(runCoverReflow(bad,{zipTools:zip,renderCover:async args=>{await fs.writeFile(path.join(bad.rawSourceRoots[0],'raw.json'),'CHANGED');return renderCover(args);}}),/변경|changed/);await assert.rejects(fs.stat(path.join(bad.destination,'intake-complete.json')),{code:'ENOENT'});assert.equal(JSON.parse(await fs.readFile(path.join(bad.destination,'06_자동 제작 결과/status.json'))).deliveryStatus,'fatal');assert(await fs.stat(path.join(bad.destination,'intake-fatal.json')));
 const failure=await fixture('renderer-failure');await assert.rejects(runCoverReflow(failure,{zipTools:zip,renderCover:async()=>{throw Error('renderer fixture failure');}}),/renderer fixture/);assert(await fs.stat(path.join(failure.destination,'06_자동 제작 결과/current/paper/source-bundle.zip')));await assert.rejects(fs.stat(path.join(failure.destination,'intake-complete.json')),{code:'ENOENT'});
 await assert.rejects(runCoverReflow({...config,destination:config.sourceRoot},{zipTools:zip,renderCover}),/원본|source/);
 console.log('Cover reflow: changed cover only, exact body/photo/ZIP preservation, verified completion, source mutation and renderer failures rejected PASS');
}finally{assert(path.resolve(base).startsWith(path.resolve(os.tmpdir())+path.sep));await fs.rm(base,{recursive:true,force:true});}
