import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import vm from 'node:vm';
const context=vm.createContext({});vm.runInContext(await fs.readFile(new URL('../app/source-cut-review-loader.js',import.meta.url),'utf8'),context);
const {createLoader}=context.ThreadsReviewLoader;
const releases=[],started=[];
const loader=createLoader({limit:3,load:payload=>{started.push(payload);return new Promise(resolve=>releases.push(resolve));}});
const controllers=Array.from({length:50},()=>new AbortController());
const pending=controllers.map((c,i)=>loader.request('p'+i,i,{signal:c.signal}).catch(e=>e.name));
await new Promise(r=>setImmediate(r));assert.equal(started.length,3,'At most three original reads may reach IPC');
controllers.slice(0,49).forEach(c=>c.abort());
releases.splice(0).forEach(r=>r('old'));
await new Promise(r=>setImmediate(r));assert.deepEqual(started,[0,1,2,49],'Cancelled selection requests must not stay in the native queue');
releases.shift()('latest');assert.equal((await Promise.all(pending)).at(-1),'latest');
assert.equal(loader.stats().active,0);assert.equal(loader.stats().queued,0);
let resolveOld,resolveNew;
const retry=createLoader({load:()=>new Promise(r=>{if(!resolveOld)resolveOld=r;else resolveNew=r;})});
const old=retry.request('same',1),fresh=retry.request('same',1,{refresh:true});await new Promise(r=>setImmediate(r));
resolveNew('fresh');await fresh;resolveOld('old');await old;assert.equal(await retry.request('same',1),'fresh','Old response cannot replace retry cache');
retry.reset();assert.equal(retry.stats().bytes,0);assert.equal(retry.stats().entries,0);
console.log('Bounded reads, cancelled queue removal, retry cache identity, reset PASS');
const queuedReleases=[];
const queued=createLoader({limit:1,load:()=>new Promise(r=>queuedReleases.push(r))});
const busy=queued.request('busy',0);await new Promise(r=>setImmediate(r));
const replaced=queued.request('retry',1).catch(e=>e.name),replacement=queued.request('retry',1,{refresh:true});
queuedReleases.shift()('busy');await busy;await new Promise(r=>setImmediate(r));queuedReleases.shift()('fresh');await replacement;
assert.equal(await Promise.race([replaced,new Promise(r=>setTimeout(()=>r('orphaned'),100))]),'AbortError','Refreshing queued request must settle displaced clients');
const resetReleases=[],shared=createLoader({limit:1,load:()=>new Promise(r=>resetReleases.push(r))});
const blocker=shared.request('busy',0).catch(e=>e.name);await new Promise(r=>setImmediate(r));
const clientControl=new AbortController(),one=shared.request('shared',1,{signal:clientControl.signal}).catch(e=>e.name),two=shared.request('shared',1).catch(e=>e.name);
clientControl.abort();shared.reset();assert.equal(await one,'AbortError');assert.equal(await blocker,'AbortError');
assert.equal(await Promise.race([two,new Promise(r=>setTimeout(()=>r('orphaned'),100))]),'AbortError','Reset must cancel the remaining shared queued subscriber');resetReleases.shift()('done');
