import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import vm from 'node:vm';
const source=await fs.readFile(new URL('../app/source-cut-post-review.js',import.meta.url),'utf8');
const start=source.indexOf(' async function getImage('),end=source.indexOf('\n const thumbs=',start);
assert(start>=0&&end>start);const code=source.slice(start,end);
let requests=0,resolve,reject;
const context=vm.createContext({cache:new Map(),inFlight:new Map(),cacheEpoch:0,cacheBytes:0,api:{image:()=>{requests++;return new Promise((a,b)=>{resolve=a;reject=b;});}}});vm.runInContext(code,context);
const row={id:'a',outputVersion:'v1'};
const first=context.getImage(row,1),second=context.getImage(row,1);await Promise.resolve();assert.equal(requests,1,'Cover thumbnail and reader must share one pending request');resolve('data:image/png;base64,AA');assert.deepEqual(await Promise.all([first,second]),['data:image/png;base64,AA','data:image/png;base64,AA']);
await context.getImage(row,1);assert.equal(requests,1);
const failed=context.getImage(row,2);await Promise.resolve();reject(Error('missing'));await assert.rejects(failed,/missing/);
const retry=context.getImage(row,2);await Promise.resolve();assert.equal(requests,3,'Failed requests must be retryable');resolve('retry');assert.equal(await retry,'retry');
const old=context.getImage(row,3);await Promise.resolve();context.cacheEpoch++;context.cache.clear();context.cacheBytes=0;resolve('old');await old;assert.equal(context.cache.size,0,'A late response from a previous reload must not refill cache');
const reloadStart=source.indexOf('cacheEpoch++;cache.clear();'),reloadEnd=source.indexOf('pageRequest++;',reloadStart);assert(reloadStart>=0&&reloadEnd>reloadStart);
context.cache.set('fixture','large retained value');context.cacheBytes=20*1024*1024;vm.runInContext(source.slice(reloadStart,reloadEnd),context);assert.equal(context.cache.size,0);assert.equal(context.cacheBytes,0,'Reload must reset cache byte accounting together with its entries');
const decoded=[],decodeContext=vm.createContext({Image:class{constructor(){decoded.push(this);}removeAttribute(name){if(name==='src')this.src='';}}});
const decodeStart=source.indexOf(' function decodeImage('),decodeEnd=source.indexOf('\n function visibleEntries(',decodeStart);vm.runInContext(source.slice(decodeStart,decodeEnd),decodeContext);
const decodedPromise=decodeContext.decodeImage('data:image/png;base64,AA');decoded[0].onload();await decodedPromise;assert.equal(decoded[0].src,'','Decoded probe must release its image source');assert.equal(decoded[0].onload,null,'Probe handlers must not retain decoded image');
const brokenPromise=decodeContext.decodeImage('broken');decoded[1].onerror();await assert.rejects(brokenPromise,/이미지/);assert.equal(decoded[1].src,'','Failed probe must also release its image source');
const hanging=context.getImage(row,4);await Promise.resolve();const rejectOlder=reject,priorRequests=requests;
const explicitRetry=context.getImage(row,4,{refresh:true});await Promise.resolve();assert.equal(requests,priorRequests+1,'Explicit retry must replace a stalled request rather than join it');resolve('fresh retry');assert.equal(await explicitRetry,'fresh retry');rejectOlder(Error('late old failure'));await assert.rejects(hanging,/late old/);assert.equal(await context.getImage(row,4),'fresh retry');
console.log('review requests: overlapping thumbnail/reader calls deduplicated, retries and reload epochs preserved PASS');
