import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import crypto from 'node:crypto';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),{createPostReviewStore,version}=require('../desktop/post-review-store.cjs');
const root=await fs.mkdtemp(path.join(os.tmpdir(),'threads-workflow-test-'));
try{
 const out=path.join(root,'06_자동 제작 결과'),folder=path.join(out,'현재 결과','fixture');
 await fs.mkdir(path.join(folder,'rendered'),{recursive:true});
 const png=Buffer.from('fixture'),hash=crypto.createHash('sha256').update(png).digest('hex');
 await fs.writeFile(path.join(folder,'rendered','slide-001.png'),png);
 await fs.writeFile(path.join(folder,'rendered','slide-002.png'),png);
 await fs.writeFile(path.join(folder,'production-plan.json'),JSON.stringify({coverTitle:'동료가 일을 떠넘긴 후기',sourceUnits:[{kind:'text',text:'회사 동료와 일을 나누는 이야기'}],pages:[{role:'cover'},{role:'body'}]}));
 const a={id:'a',title:'동료가 일을 떠넘긴 후기',outputFolder:'현재 결과/fixture',sourceFingerprint:'a',outputSha256:'one',ruleVersion:'r',images:[{name:'rendered/slide-001.png',sha256:hash},{name:'rendered/slide-002.png',sha256:hash}]};
 const b={...a,id:'b',title:'부부 돈관리 후기',sourceFingerprint:'b'};
 const missing={id:'missing',title:'원문이 없는 소재',sourceFingerprint:'missing',status:'blocked',reason:'원본 부족'};
 const file=path.join(out,'status.json'),report=()=>fs.writeFile(file,JSON.stringify({entries:[a,b,missing]}));
 await report();const store=createPostReviewStore(root);
 assert.equal(typeof store.visit,'function','실제 열람 기록 API가 필요합니다');
 assert.equal(typeof store.decide,'function');assert.equal(typeof store.random,'function');
 let list=await store.list();assert.equal(list.entries.length,3);
 assert.equal(list.entries.find(e=>e.id==='a').topic,'work');
 assert.equal(list.entries.find(e=>e.id==='missing').hasOutput,false);
 assert.equal(list.entries.find(e=>e.id==='missing').disposition,'held');
 const v=version(a);
 await store.visit({id:'a',outputVersion:v,page:1});await store.visit({id:'a',outputVersion:v,page:2});
 list=await createPostReviewStore(root).list();let row=list.entries.find(e=>e.id==='a');
 assert(row.progress.seenAt);assert.equal(row.progress.lastPage,2);assert.deepEqual(row.progress.pagesSeen,[1,2]);assert.equal(row.progress.complete,true);assert.equal(row.current,null);
 await assert.rejects(store.visit({id:'a',outputVersion:v,page:3}));
 await assert.rejects(store.visit({id:'missing',outputVersion:version(missing),page:1}));
 await store.save({id:'a',outputVersion:v,score:9,note:'유지할 실제 평가'});
 const feedbackBefore=await fs.readFile(store.file,'utf8');
 await store.decide({id:'b',outputVersion:version(b),disposition:'rejected',reasonCode:'material_unsuitable',note:'소재 부적합'});
 assert.equal(await store.random({}),null);
 await store.decide({id:'b',outputVersion:version(b),disposition:'eligible',reasonCode:null,note:''});
 assert.equal((await store.random({})).id,'b');
 assert.equal(await store.random({topic:'health'}),null);
 await store.decide({id:'b',outputVersion:version(b),disposition:'held',reasonCode:'source_insufficient',note:'원본 보완'});
 row=(await createPostReviewStore(root).list()).entries.find(e=>e.id==='b');assert.equal(row.disposition,'held');assert.equal(row.progress.reasonCode,'source_insufficient');
 await store.decide({id:'b',outputVersion:version(b),disposition:'eligible',reasonCode:null,note:''});
 assert((await store.list()).entries.find(e=>e.id==='b').progress.decisions.some(d=>d.reasonCode==='source_insufficient'),'복원 후에도 보류 이유 이력 보존');
 await store.save({id:'b',outputVersion:version(b),score:null,note:'메모도 검토한 기록'});
 assert.equal(await store.random({}),null,'메모만 있는 기존 검토를 랜덤으로 다시 고르지 않음');
 for(const payload of [{disposition:'deleted',reasonCode:null},{disposition:'held',reasonCode:'unknown'}])await assert.rejects(store.decide({id:'b',outputVersion:version(b),note:'',...payload}));
 assert.equal((await store.list()).entries.find(e=>e.id==='a').current.note,'유지할 실제 평가');
 assert.equal(JSON.parse(await fs.readFile(store.file,'utf8')).evaluations[0].score,9);
 a.outputSha256='changed';await report();
 const workflowBeforeVersionRead=await fs.readFile(store.workflowFile,'utf8');
 const renewed=(await store.list()).entries.find(e=>e.id==='a');
 assert.equal(renewed.seenAt,null,'수정된 출력 버전은 안읽음');
 assert(renewed.previousSeenAt,'이전 버전의 실제 열람 이력은 별도로 유지');
 assert.equal(await fs.readFile(store.workflowFile,'utf8'),workflowBeforeVersionRead,'조회가 열람 이력을 변경하지 않음');
 row=(await store.list()).entries.find(e=>e.id==='a');assert.equal(row.progress,null);assert.equal(row.current,null);assert.equal(row.disposition,'eligible');
 await assert.rejects(store.visit({id:'a',outputVersion:v,page:1}));
 const saved=JSON.parse(await fs.readFile(store.workflowFile,'utf8'));assert.equal(saved.entries.filter(e=>e.id==='a').length,1);assert.equal(saved.recordType,'user_review_workflow');
 assert(feedbackBefore.includes('유지할 실제 평가'));
 await fs.writeFile(store.workflowFile,'invalid');
 await assert.rejects(store.visit({id:'a',outputVersion:version(a),page:1}));
 assert.equal(await fs.readFile(store.workflowFile,'utf8'),'invalid');
 console.log('Review workflow: durable actual views, version separation, topic classification, eligible unseen random, reversible triage and original ratings preserved PASS');
}finally{await fs.rm(root,{recursive:true,force:true});}

const preservedRoot = await fs.mkdtemp(path.join(os.tmpdir(), 'threads-preserved-triage-'));
try {
 const out = path.join(preservedRoot, '06_자동 제작 결과'), folder = path.join(out, 'current');
 await fs.mkdir(folder, {recursive:true});
 await fs.writeFile(path.join(folder,'production-plan.json'), JSON.stringify({coverTitle:'Fixture',sourceUnits:[],pages:[{role:'cover'}]}));
 const base = {title:'Fixture',outputFolder:'current',sourceFingerprint:'fixture',outputSha256:'fixture',ruleVersion:'fixture',reviewRound:'fresh-round',images:[{name:'rendered/slide-001.png',sha256:'fixture'}]};
 const rows = [{...base,id:'held',disposition:'held',reasonCode:'source_insufficient'},{...base,id:'rejected',disposition:'rejected',reasonCode:'material_unsuitable'}];
 await fs.writeFile(path.join(out,'status.json'), JSON.stringify({reviewRound:'fresh-round',entries:rows}));
 await fs.writeFile(path.join(preservedRoot,'review-current.json'), JSON.stringify({reviewRound:'fresh-round'}));
 const freshStore = createPostReviewStore(preservedRoot, {readOnly:true});
 let fresh = await freshStore.list();
 assert.equal(fresh.entries.find(e=>e.id==='held').disposition,'held');
 assert.equal(fresh.entries.find(e=>e.id==='rejected').disposition,'rejected');
 assert(fresh.entries.every(e=>e.progress===null && e.current===null));
 assert.equal(await freshStore.random({}),null,'preserved held and rejected rows must remain outside random review');
 rows.push({...base,id:'eligible',disposition:'eligible'});
 await fs.writeFile(path.join(out,'status.json'), JSON.stringify({reviewRound:'fresh-round',entries:rows}));
 assert.equal((await freshStore.random({})).id,'eligible');
 const {initialDisposition} = require('../desktop/review-workflow-model.cjs');
 assert.equal(initialDisposition({...base,disposition:'invalid'}),'eligible','invalid explicit disposition must fall back to output eligibility');
 console.log('Preserved row triage remains held/rejected in fresh store and random review excludes both: PASS');
} finally {
 assert(path.resolve(preservedRoot).startsWith(path.resolve(os.tmpdir()) + path.sep));
 assert(path.basename(preservedRoot).startsWith('threads-preserved-triage-'));
 await fs.rm(preservedRoot,{recursive:true,force:true});
}
