import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import vm from 'node:vm';
const source=await fs.readFile(new URL('../app/source-cut-post-review.js',import.meta.url),'utf8');
const decoded=[],context=vm.createContext({Image:class{constructor(){decoded.push(this);}removeAttribute(name){if(name==='src')this.src='';}},abortError:()=>Object.assign(Error('cancelled'),{name:'AbortError'})});
const start=source.indexOf(' function decodeImage('),end=source.indexOf('\n function seen(',start);vm.runInContext(source.slice(start,end),context);
const ready=context.decodeImage('original');decoded[0].onload();await ready;assert.equal(decoded[0].src,'');assert.equal(decoded[0].onload,null);
const broken=context.decodeImage('broken');decoded[1].onerror();await assert.rejects(broken,/이미지/);assert.equal(decoded[1].src,'');
const control=new AbortController(),pending=context.decodeImage('slow',{signal:control.signal});control.abort();await assert.rejects(pending,{name:'AbortError'});assert.equal(decoded[2].src,'');assert.equal(decoded[2].onload,null);assert.equal(decoded[2].onerror,null);
console.log('Decoder sources and handlers released on success, failure and selection cancellation PASS');
