import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import fs from 'node:fs';
import vm from 'node:vm';
const require = createRequire(import.meta.url);
const { captureUrl, cleanTitle, tiles, capturePage } = require('../desktop/capture.cjs');
const { publicAddress } = require('../desktop/network.cjs');
assert.equal(captureUrl(' https://example.com/post?id=3 '), 'https://example.com/post?id=3');
assert.equal(cleanTitle('웹진 인벤 : 자체생산)본인 일본 유학 및 결혼 썰 - 오픈이슈갤러리'), '자체생산)본인 일본 유학 및 결혼 썰');
assert.equal(cleanTitle('평범한 제목: 실제 내용'), '평범한 제목: 실제 내용');
for (const url of ['file:///C:/Windows/test', 'javascript:alert(1)', 'http://example.com', 'https://user:pass@example.com', 'https://127.0.0.1', 'https://[::1]', 'https://localhost', 'https://app.local', 'https://example.com:8443', 'https://gall.dcinside.com/example', 'https://www.teamblind.com/post']) assert.throws(() => captureUrl(url));
for (const ip of ['127.0.0.1', '10.1.1.1', '172.16.1.1', '192.168.0.1', '169.254.169.254', '100.64.1.1', '::1', '::ffff:127.0.0.1', 'fc00::1', 'fe80::1', 'bad']) assert.equal(publicAddress(ip), false, ip);
assert.equal(publicAddress('1.1.1.1'), true);
assert.equal(publicAddress('2606:4700:4700::1111'), true);
const parts = tiles(1280, 18501);
assert.deepEqual(parts.map(p => [p.y, p.height]), [[0,8000],[8000,8000],[16000,2501]]);
assert.equal(parts.reduce((n,p) => n + p.height,0), 18501);
assert.throws(() => tiles(1280,48001));
assert.throws(() => tiles(1800,500));
let destroyed = false;
await assert.rejects(capturePage({loadURL: async()=>{throw new Error('network unavailable');},isDestroyed:()=>destroyed,destroy(){destroyed=true;},webContents:{isDestroyed:()=>true}}, 'https://example.com'), /network unavailable/);
assert.equal(destroyed,true);
const scripts = [];
const exposed = {};
vm.runInNewContext(fs.readFileSync(new URL('../desktop/preload.cjs',import.meta.url),'utf8'), { require:()=>({contextBridge:{exposeInMainWorld:(key,value)=>{exposed[key]=value;}},ipcRenderer:{invoke:(...args)=>scripts.push(args),on(){},removeListener(){}}}),Object });
assert.deepEqual(Object.keys(exposed.ThreadsCutDesktop).sort(), ['cancel','capture','onProgress','openReferences','saveReference']);
exposed.ThreadsCutDesktop.capture('https://example.com');
assert.deepEqual(scripts[0], ['source-cut:capture','https://example.com']);
console.log('Source capture URL/network boundaries, complete tiling, failure cleanup and narrow preload bridge: PASS');
