import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const window = {};
const sandbox = { window, document: { createElement: () => ({ getContext: () => context }) } };
for (const name of ['source-cut-model.js', 'source-cut-composition.js']) vm.runInNewContext(fs.readFileSync(new URL('../app/' + name, import.meta.url), 'utf8'), sandbox);
const m = window.ThreadsSourceCut;
const context = { font: '', measureText: text => ({ width: text.length * 25 }), scale() {}, fillRect() {}, drawImage(...args) { this.lastImage = args; }, strokeText() {}, fillText() {} };
const p = m.newProject(); m.addAsset(p,{name:'source',width:600,height:1000,dataUrl:'data:image/png;base64,AA=='});
p.title='원문 제목'; p.assets[0].cuts=[400];
const pages=m.slides(p); const first=pages[1];
p.pageLayouts[first.key]={paddingTop:100,paddingBottom:120,paddingSide:80,minimumHeight:1350,beforeText:'작성한 설명',afterText:'내 의견',noteSize:50};
const g=m.pageGeometry(context,first,p);
assert.equal(g.imageWidth,920); assert.equal(g.height,1350); assert(g.beforeTop<g.imageTop); assert(g.afterTop>g.imageTop+g.imageHeight);
assert.equal(g.imageHeight,Math.round(920*400/600));
const c={getContext:()=>context};m.render(c,{},first,p,false);assert.equal(c.width,1080);assert.equal(c.height,1350);
const round=m.restore(JSON.parse(JSON.stringify(p)));assert.equal(round.assets[0].uid,p.assets[0].uid);assert.equal(m.slides(round)[1].key,first.key);assert.equal(round.pageLayouts[first.key].afterText,'내 의견');assert.equal(round.complete,false);
const legacy=m.restore({...p,pageLayouts:undefined,presets:undefined});assert.equal(Object.keys(legacy.pageLayouts).length,0);
const saved=m.preset({name:'내 프리셋',appearance:{fontId:'gothic',fontWeight:800,outlineWidth:12},page:p.pageLayouts[first.key]});
assert.equal(saved.appearance.fontId,'gothic');assert.equal(saved.appearance.fontWeight,800);assert.equal(saved.page.paddingTop,100);assert.equal(saved.page.afterText,'');
assert.equal(m.appearance({fontId:'gothic',fontWeight:900}).fontWeight,800);
m.assertFontText('상업용 한글 English 123 !?','gothic');assert.throws(()=>m.assertFontText(String.fromCodePoint(0x1f600),'sans'),/다른 시스템 폰트/);
const body=m.slides(p).slice(1);assert.equal(body.reduce((sum,s)=>sum+s.rect.height,0),1000);
p.pageLayouts[first.key].afterText='가\n'.repeat(100);assert.throws(()=>m.pageGeometry(context,first,p),/여러 장/);
console.log('Crop-preserving padding, note placement, stable source IDs, project compatibility and licensed-font presets: PASS');
