import json,glob,os
r=r'C:\Users\user\AppData\Local\Temp\threads_hourly_sol'
key='260916_탕수육딸기먼저먹을까봐'
cp=os.path.join(r,'data','candidates','260916_C0_A0_P0_탕수육딸기먼저먹을까봐.md')
s=open(cp,encoding='utf-8').read(); s=s.replace('- 정확한 원문 링크: 미확인','- 정확한 원문 링크: https://theqoo.net/square/4341634677\n- 원문 post ID: 4341634677\n- provenance 검증: 완료 (2026-09-21)\n- source asset bytes: 미확보 / BLOCKED_SOURCE_ASSET_BYTES')
open(cp,'w',encoding='utf-8').write(s)
td=os.path.join(r,'03_PRODUCTION','_TEMP_TEST_ONLY_DO_NOT_PUBLISH','260921_탕수육딸기먼저먹을까봐_TEMP_TEST_ONLY'); os.makedirs(td,exist_ok=True)
g={'temporaryTestOnly':True,'publicationAllowed':False,'candidateKey':key,'stage':9,'status':'BLOCKED_SOURCE_ASSET_BYTES','verifiedSourceUrl':'https://theqoo.net/square/4341634677','postId':'4341634677','observedPublicMedia':['https://img.theqoo.net/rLQEwT','https://img-cdn.theqoo.net/rPKjNn.jpg','https://img-cdn.theqoo.net/OMkwDl.jpg'],'sourceBytesAcquired':False,'approvedVersion':None,'executionEligible':False,'unblockCondition':'Acquire and store the original public/permitted source media bytes with URL+hash provenance; do not bypass login, anti-bot, paywall, or access controls.','coverRule':'No blur; real source media only when verified; no generated-image fallback; preserve slide 2+ source order/content.'}
json.dump(g,open(os.path.join(td,'stage9_exact_source_gate_TEMP_TEST_ONLY.json'),'w',encoding='utf-8'),ensure_ascii=False,indent=2)
p=os.path.join(r,'03_PRODUCTION','_TEMP_TEST_ONLY_DO_NOT_PUBLISH','TEMP_TEST_PROGRESS.json'); x=json.load(open(p,encoding='utf-8')); x['lastUpdated']='2026-09-21T16:28:00+09:00'; x['lastCandidateKey']=key; x['lastStage']=9; x['lastStatus']='BLOCKED_SOURCE_ASSET_BYTES'; json.dump(x,open(p,'w',encoding='utf-8'),ensure_ascii=False,indent=2)
h=os.path.join(r,'00_START_HERE','NEXT_RUN_HANDOFF.md'); t=open(h,encoding='utf-8').read(); t += '\n\n## Sol run 265 (2026-09-21 16:28 KST)\n- Queue snapshot rechecked: 1,248 candidates; next sequential rank 59 processed: `260916_탕수육딸기먼저먹을까봐`.\n- Exact TheQoo source verified: https://theqoo.net/square/4341634677 (post ID 4341634677). Public page exposes three media references, but source bytes+hash provenance were not stored; keep C0/A0/P0 and `BLOCKED_SOURCE_ASSET_BYTES`.\n- TEMP stage-9 gate saved under `_TEMP_TEST_ONLY_DO_NOT_PUBLISH`; `temporaryTestOnly=true`, `publicationAllowed=false`, `executionEligible=false`. Stage 10+ blocked until original permitted bytes are acquired. No P1/publishing.\n'; open(h,'w',encoding='utf-8').write(t)
