(function () {
  'use strict';
  let files = [];
  let packagePreview = null;
  function $(s) { return document.querySelector(s); }
  function escapeHtml(v) { return String(v).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])); }
  function inferKind(index, name) { const n=String(name||'').toLowerCase(); if(/comment|reply|댓글|반응/.test(n))return 'comment'; return index===0?'post':'continuation'; }
  function ensurePreviewRoot(){ let root=$('#sourceCarouselPreview'); if(root)return root; const status=$('#sourcePackageStatus'); if(!status)return null; root=document.createElement('div'); root.id='sourceCarouselPreview'; root.className='source-carousel-preview'; status.insertAdjacentElement('afterend',root); return root; }
  function renderList(){ const root=$('#sourceAssetList'); if(!root)return; root.innerHTML=files.length?files.map((entry,i)=>`<div class="source-asset-row" data-index="${i}"><img src="${entry.url}" alt="선택 이미지 ${i+1}"/><div><strong>${i+1}. ${escapeHtml(entry.file.name)}</strong><small>${escapeHtml(entry.file.type)} · OCR 미실행 · privacy review 필요</small><select class="source-kind"><option value="post"${entry.kind==='post'?' selected':''}>원문</option><option value="continuation"${entry.kind==='continuation'?' selected':''}>이어지는 캡처</option><option value="media"${entry.kind==='media'?' selected':''}>첨부 이미지</option><option value="comment"${entry.kind==='comment'?' selected':''}>댓글/반응</option></select></div><div class="source-order"><button type="button" data-move="up">↑</button><button type="button" data-move="down">↓</button></div></div>`).join(''):'<span class="muted-inline">선택된 실제 자산 없음 · ASSETS_PENDING</span>'; }
  function revokeAll(){ files.forEach(x=>URL.revokeObjectURL(x.url)); files=[]; packagePreview=null; renderList(); renderCarousel(); }
  function selectedCandidate(){ const id=globalThis.ThreadsSourceIntakeContext?.getSelectedId?.(); return globalThis.ThreadsSourceIntakeContext?.getCandidate?.(id)||null; }
  function buildPackage(){ const candidate=selectedCandidate(); if(!candidate)throw new Error('먼저 후보를 선택하세요.'); if(!files.length)throw new Error('실제 스크린샷/이미지가 필요합니다.'); document.querySelectorAll('.source-asset-row').forEach((row,i)=>{files[i].kind=row.querySelector('.source-kind').value;}); packagePreview=window.ThreadsSourcePackage.build({sourceUrl:candidate.url||'',sourcePlatform:candidate.sourceType||'manual',title:candidate.title,hookDraft:$('#sourceHookInput').value,captionDraft:$('#sourceCaptionInput').value,rightsState:$('#sourceRightsInput').value,userProvidedProvenance:candidate.url?'':'browser-local user-selected screenshot',assets:files.map((entry,i)=>({id:`asset-${String(i+1).padStart(2,'0')}`,name:entry.file.name,mime:entry.file.type,kind:entry.kind,provenance:candidate.url||'user-provided local screenshot',privacyReview:'REQUIRED',verifiedByVision:false,verifiedByOcr:false}))}); $('#sourcePackageStatus').textContent=`SOURCE_PACKAGE 준비됨 · ${packagePreview.assets.length}장\n게시: 차단 · 권리: ${packagePreview.rightsState} · 개인정보: REVIEW_REQUIRED\nOCR/vision: 실행 안 함\n흐름: ${packagePreview.renderPlan.map(x=>`${x.slide}:${x.treatment}`).join(' → ')}`; renderCarousel(); return packagePreview; }
  function renderCarousel(){ const root=ensurePreviewRoot(); if(!root)return; if(!packagePreview||!files.length){root.innerHTML='<span class="muted-inline">Source Package를 만들면 실제 자산 기반 1080×1080 구성을 여기서 미리 봅니다.</span>';return;} const hook=escapeHtml(packagePreview.hookDraft||packagePreview.title||'이 장면, 무슨 일이 있었던 걸까?'); const slides=[`<article class="source-slide source-slide-hook"><img class="source-slide-bg" src="${files[0].url}" alt="첫 실제 소스 이미지 블러 배경"/><div class="source-slide-shade"></div><div class="source-slide-copy"><small>01 · SOURCE</small><strong>${hook}</strong><span>넘겨서 원문 보기 →</span></div></article>`]; files.forEach((entry,i)=>slides.push(`<article class="source-slide source-slide-evidence"><img class="source-slide-bg" src="${entry.url}" alt="소스 배경 ${i+1}"/><div class="source-slide-backdrop"></div><img class="source-slide-main" src="${entry.url}" alt="실제 소스 자산 ${i+1}"/><span class="source-slide-badge">${String(i+2).padStart(2,'0')} · ${entry.kind==='comment'?'실제 반응':entry.kind==='media'?'첨부 이미지':entry.kind==='continuation'?'이어지는 내용':'원문'}</span></article>`)); slides.push(`<article class="source-slide source-slide-cta"><div class="source-slide-copy"><small>${escapeHtml(packagePreview.sourcePlatform||'SOURCE')}</small><strong>${escapeHtml(packagePreview.finalCta)}</strong><span>게시 전 권리·개인정보·사람 검토 필요</span></div></article>`); root.innerHTML=`<div class="source-carousel-actions"><button type="button" id="exportSourceCarouselPngBtn">1080×1080 PNG 세트 받기</button><small>브라우저에서 실제 선택 자산으로만 렌더 · 게시하지 않음</small></div>${slides.join('')}`; $('#exportSourceCarouselPngBtn')?.addEventListener('click', exportPngSet); }
  function loadImage(url){ return new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=()=>reject(new Error('이미지를 읽지 못했습니다.'));img.src=url;}); }
  function cover(ctx,img,w,h){const s=Math.max(w/img.naturalWidth,h/img.naturalHeight),dw=img.naturalWidth*s,dh=img.naturalHeight*s;ctx.drawImage(img,(w-dw)/2,(h-dh)/2,dw,dh);}
  function contain(ctx,img,w,h,pad=54){const aw=w-pad*2,ah=h-pad*2,s=Math.min(aw/img.naturalWidth,ah/img.naturalHeight),dw=img.naturalWidth*s,dh=img.naturalHeight*s;ctx.drawImage(img,(w-dw)/2,(h-dh)/2,dw,dh);}
  function wrapText(ctx,text,x,y,maxWidth,lineHeight,maxLines){const words=String(text).split(/\s+/);let line='',lines=[];for(const word of words){const test=line?`${line} ${word}`:word;if(ctx.measureText(test).width>maxWidth&&line){lines.push(line);line=word;}else line=test;}if(line)lines.push(line);lines=lines.slice(0,maxLines);lines.forEach((v,i)=>ctx.fillText(v,x,y+i*lineHeight));}
  function downloadCanvas(canvas,name){return new Promise((resolve,reject)=>canvas.toBlob(blob=>{if(!blob)return reject(new Error('PNG 생성 실패'));const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);resolve();},'image/png'));}
  async function exportPngSet(){if(!packagePreview||!files.length)return;const btn=$('#exportSourceCarouselPngBtn');if(btn){btn.disabled=true;btn.textContent='PNG 만드는 중…';}try{const W=1080,H=1080,images=await Promise.all(files.map(x=>loadImage(x.url)));const total=files.length+2;for(let index=0;index<total;index++){const canvas=document.createElement('canvas');canvas.width=W;canvas.height=H;const ctx=canvas.getContext('2d');ctx.fillStyle='#111';ctx.fillRect(0,0,W,H);if(index===0){cover(ctx,images[0],W,H);ctx.fillStyle='rgba(0,0,0,.62)';ctx.fillRect(0,0,W,H);ctx.fillStyle='#fff';ctx.font='700 66px system-ui,sans-serif';ctx.textBaseline='top';wrapText(ctx,packagePreview.hookDraft||packagePreview.title||'이 장면, 무슨 일이 있었던 걸까?',72,350,936,82,5);ctx.font='500 28px system-ui,sans-serif';ctx.fillText('넘겨서 원문 보기 →',72,930);}else if(index<=files.length){const img=images[index-1];ctx.save();ctx.filter='blur(30px) brightness(.45)';cover(ctx,img,W,H);ctx.restore();ctx.fillStyle='rgba(0,0,0,.2)';ctx.fillRect(0,0,W,H);contain(ctx,img,W,H,48);ctx.fillStyle='rgba(0,0,0,.72)';ctx.fillRect(36,36,270,58);ctx.fillStyle='#fff';ctx.font='600 25px system-ui,sans-serif';ctx.textBaseline='middle';const kind=files[index-1].kind;ctx.fillText(`${String(index+1).padStart(2,'0')} · ${kind==='comment'?'실제 반응':kind==='media'?'첨부 이미지':kind==='continuation'?'이어지는 내용':'원문'}`,55,65);}else{ctx.fillStyle='#fff';ctx.font='700 58px system-ui,sans-serif';ctx.textBaseline='top';wrapText(ctx,packagePreview.finalCta||'여러분은 어떻게 생각하세요?',72,360,936,76,5);ctx.font='500 24px system-ui,sans-serif';ctx.fillStyle='#bbb';ctx.fillText('게시 전 권리 · 개인정보 · 사람 검토 필요',72,930);}await downloadCanvas(canvas,`source-carousel-${String(index+1).padStart(2,'0')}.png`);}$('#sourcePackageStatus').textContent+=`\nPNG: ${total}장 브라우저 렌더 완료 · 게시 동작 없음`;}catch(e){$('#sourcePackageStatus').textContent+=`\nPNG 생성 실패: ${e.message}`;}finally{if(btn){btn.disabled=false;btn.textContent='1080×1080 PNG 세트 받기';}}}
  function bind(){ const input=$('#sourceAssetInput'); if(!input)return; input.addEventListener('change',()=>{revokeAll();files=[...input.files].map((file,i)=>({file,url:URL.createObjectURL(file),kind:inferKind(i,file.name)}));renderList();}); $('#clearSourceAssetsBtn').addEventListener('click',()=>{input.value='';revokeAll();$('#sourcePackageStatus').textContent='';}); $('#buildSourcePackageBtn').addEventListener('click',()=>{try{buildPackage();}catch(e){$('#sourcePackageStatus').textContent=`생성 차단: ${e.message}`;}}); $('#sourceAssetList').addEventListener('click',e=>{const b=e.target.closest('button[data-move]');if(!b)return;const row=b.closest('.source-asset-row');const i=Number(row.dataset.index);const j=b.dataset.move==='up'?i-1:i+1;if(j<0||j>=files.length)return;[files[i],files[j]]=[files[j],files[i]];renderList();}); renderList();renderCarousel(); }
  window.ThreadsSourceIntake=Object.freeze({bind,buildPackage,getPreview:()=>packagePreview,renderCarousel,exportPngSet}); document.readyState==='loading'?document.addEventListener('DOMContentLoaded',bind):bind();
})();
