(function () {
  'use strict';
  let files = [];
  let packagePreview = null;
  function $(s) { return document.querySelector(s); }
  function escapeHtml(v) { return String(v).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])); }
  function inferKind(name) { return /media|attach|image|photo|첨부|사진/i.test(String(name || '')) ? 'media' : 'post'; }
  function ensurePreviewRoot(){ let root=$('#sourceCarouselPreview'); if(root)return root; const status=$('#sourcePackageStatus'); if(!status)return null; root=document.createElement('div'); root.id='sourceCarouselPreview'; root.className='source-carousel-preview'; status.insertAdjacentElement('afterend',root); return root; }
  function renderList(){ const root=$('#sourceAssetList'); if(!root)return; root.innerHTML=files.length?`<div class="source-asset-row"><div><strong>1. AUTO COVER</strong><small>첫 원문 자산을 배경으로 1080×1080 커버 자동 생성 · 원문 제목 그대로 사용</small></div></div>`+files.map((entry,i)=>`<div class="source-asset-row" data-index="${i}"><img src="${entry.url}" alt="원문 자산 ${i+1}"/><div><strong>${i+2}. ${escapeHtml(entry.file.name)}</strong><small>원문 순서 ${i+1} · OCR/vision 미실행</small><select class="source-kind"><option value="post"${entry.kind==='post'?' selected':''}>원문 스크린샷</option><option value="media"${entry.kind==='media'?' selected':''}>원문 첨부 이미지/미디어</option></select></div><div class="source-order"><button type="button" data-move="up">↑</button><button type="button" data-move="down">↓</button></div></div>`).join(''):'<span class="muted-inline">원문 스크린샷/이미지를 선택하세요 · 커버는 첫 원문 자산으로 자동 생성됩니다.</span>'; }
  function revokeAll(){ files.forEach(x=>URL.revokeObjectURL(x.url)); files=[]; packagePreview=null; renderList(); renderCarousel(); }
  function selectedCandidate(){ const id=globalThis.ThreadsSourceIntakeContext?.getSelectedId?.(); return globalThis.ThreadsSourceIntakeContext?.getCandidate?.(id)||null; }
  function buildPackage(){ const candidate=selectedCandidate(); if(!candidate)throw new Error('먼저 후보를 선택하세요.'); if(files.length<1)throw new Error('실제 원문 스크린샷/미디어 1장 이상이 필요합니다. 커버는 자동 생성됩니다.'); document.querySelectorAll('.source-asset-row[data-index]').forEach(row=>{const i=Number(row.dataset.index);files[i].kind=row.querySelector('.source-kind').value;}); const fullBodyCaptureStatus=$('#sourceBodyCaptureStatus')?.value||'pending'; const sourceProvenance=candidate.url||'browser-local user-selected screenshot'; const first=files[0]; packagePreview=window.ThreadsSourcePackage.build({sourceUrl:candidate.url||'',sourcePlatform:candidate.sourceType||'manual',sourceFormat:$('#sourceFormatInput')?.value||'글',title:candidate.title,coverText:candidate.title,fullBodyCaptureStatus,rightsState:$('#sourceRightsInput').value,userProvidedProvenance:candidate.url?'':'browser-local user-selected screenshot',assets:[{id:'asset-cover-auto',name:`AUTO_COVER_FROM_${first.file.name}`,mime:'image/png',kind:'cover',provenance:`derived locally from ${sourceProvenance}; title=${candidate.title}`,verifiedByVision:false,verifiedByOcr:false},...files.map((entry,i)=>({id:`asset-${String(i+1).padStart(2,'0')}`,name:entry.file.name,mime:entry.file.type,kind:entry.kind,provenance:sourceProvenance,verifiedByVision:false,verifiedByOcr:false}))]}); $('#sourcePackageStatus').textContent=`SOURCE_PACKAGE 준비됨 · 자동 커버 1 + 원문 ${files.length}장\n전체 본문: ${packagePreview.fullBodyCaptureStatus} · ASSETS_PENDING: ${packagePreview.assetsPending?'YES':'NO'}\n커버: 첫 원문 자산 배경 + 원문 제목 자동 렌더\n게시: 차단 · 권리: ${packagePreview.rightsState} · 개인정보: USER_REVIEW\nOCR/vision: 실행 안 함`; renderCarousel(); return packagePreview; }
  function renderCarousel(){ const root=ensurePreviewRoot(); if(!root)return; if(!packagePreview||files.length<1){root.innerHTML='<span class="muted-inline">원문 전체 스크린샷을 순서대로 넣으면 첫 자산으로 커버를 자동 만들고 1080×1080 구성을 미리 봅니다.</span>';return;} const title=escapeHtml(packagePreview.coverText||packagePreview.title||''); const slides=[`<article class="source-slide source-slide-hook"><img class="source-slide-bg" src="${files[0].url}" alt="자동 커버 배경"/><div class="source-slide-shade"></div><div class="source-slide-copy"><small>01 · AUTO COVER</small><strong>${title}</strong></div></article>`]; files.forEach((entry,i)=>slides.push(`<article class="source-slide source-slide-evidence"><img class="source-slide-bg" src="${entry.url}" alt="원문 배경 ${i+1}"/><div class="source-slide-backdrop"></div><img class="source-slide-main" src="${entry.url}" alt="원문 자산 ${i+1}"/><span class="source-slide-badge">${String(i+2).padStart(2,'0')} · ${entry.kind==='media'?'원문 첨부 이미지':'원문'}</span></article>`)); root.innerHTML=`<div class="source-carousel-actions"><button type="button" id="exportSourceCarouselPngBtn"${packagePreview.fullBodyCaptureStatus!=='complete'?' disabled':''}>1080×1080 PNG 세트 받기</button><small>${packagePreview.fullBodyCaptureStatus==='complete'?'전체 본문 complete · 자동 커버 포함 · 게시 동작 없음':'전체 본문 complete 확인 전 export 차단 · ASSETS_PENDING'}</small></div>${slides.join('')}`; $('#exportSourceCarouselPngBtn')?.addEventListener('click', exportPngSet); }
  function loadImage(url){ return new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=()=>reject(new Error('이미지를 읽지 못했습니다.'));img.src=url;}); }
  function cover(ctx,img,w,h){const s=Math.max(w/img.naturalWidth,h/img.naturalHeight),dw=img.naturalWidth*s,dh=img.naturalHeight*s;ctx.drawImage(img,(w-dw)/2,(h-dh)/2,dw,dh);}
  function contain(ctx,img,w,h,pad=54){const aw=w-pad*2,ah=h-pad*2,s=Math.min(aw/img.naturalWidth,ah/img.naturalHeight),dw=img.naturalWidth*s,dh=img.naturalHeight*s;ctx.drawImage(img,(w-dw)/2,(h-dh)/2,dw,dh);}
  function wrapText(ctx,text,x,y,maxWidth,lineHeight,maxLines){const words=String(text).split(/\s+/);let line='',lines=[];for(const word of words){const test=line?`${line} ${word}`:word;if(ctx.measureText(test).width>maxWidth&&line){lines.push(line);line=word;}else line=test;}if(line)lines.push(line);lines=lines.slice(0,maxLines);lines.forEach((v,i)=>ctx.fillText(v,x,y+i*lineHeight));}
  function downloadCanvas(canvas,name){return new Promise((resolve,reject)=>canvas.toBlob(blob=>{if(!blob)return reject(new Error('PNG 생성 실패'));const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);resolve();},'image/png'));}
  async function exportPngSet(){if(!packagePreview||files.length<1||packagePreview.fullBodyCaptureStatus!=='complete')return;const btn=$('#exportSourceCarouselPngBtn');if(btn){btn.disabled=true;btn.textContent='PNG 만드는 중…';}try{const W=1080,H=1080,images=await Promise.all(files.map(x=>loadImage(x.url)));for(let slide=0;slide<=files.length;slide++){const canvas=document.createElement('canvas');canvas.width=W;canvas.height=H;const ctx=canvas.getContext('2d');ctx.fillStyle='#111';ctx.fillRect(0,0,W,H);if(slide===0){cover(ctx,images[0],W,H);ctx.fillStyle='rgba(0,0,0,.62)';ctx.fillRect(0,0,W,H);ctx.fillStyle='#fff';ctx.font='700 66px system-ui,sans-serif';ctx.textBaseline='top';wrapText(ctx,packagePreview.coverText||packagePreview.title||'',72,350,936,82,5);}else{const img=images[slide-1];ctx.save();ctx.filter='blur(30px) brightness(.45)';cover(ctx,img,W,H);ctx.restore();ctx.fillStyle='rgba(0,0,0,.2)';ctx.fillRect(0,0,W,H);contain(ctx,img,W,H,48);}await downloadCanvas(canvas,`source-carousel-${String(slide+1).padStart(2,'0')}.png`);}$('#sourcePackageStatus').textContent+=`\nPNG: ${files.length+1}장 브라우저 렌더 완료 · 자동 커버 1 + 원문 ${files.length} · 게시 동작 없음`;}catch(e){$('#sourcePackageStatus').textContent+=`\nPNG 생성 실패: ${e.message}`;}finally{if(btn){btn.disabled=false;btn.textContent='1080×1080 PNG 세트 받기';}}}
  function bind(){ const input=$('#sourceAssetInput'); if(!input)return; input.addEventListener('change',()=>{revokeAll();files=[...input.files].map(file=>({file,url:URL.createObjectURL(file),kind:inferKind(file.name)}));renderList();}); $('#clearSourceAssetsBtn').addEventListener('click',()=>{input.value='';revokeAll();$('#sourcePackageStatus').textContent='';}); $('#buildSourcePackageBtn').addEventListener('click',()=>{try{buildPackage();}catch(e){$('#sourcePackageStatus').textContent=`생성 차단: ${e.message}`;}}); $('#sourceAssetList').addEventListener('click',e=>{const b=e.target.closest('button[data-move]');if(!b)return;const row=b.closest('.source-asset-row');const i=Number(row.dataset.index);const j=b.dataset.move==='up'?i-1:i+1;if(j<0||j>=files.length)return;[files[i],files[j]]=[files[j],files[i]];renderList();}); renderList();renderCarousel(); }
  window.ThreadsSourceIntake=Object.freeze({bind,buildPackage,getPreview:()=>packagePreview,renderCarousel,exportPngSet}); document.readyState==='loading'?document.addEventListener('DOMContentLoaded',bind):bind();
})();
