import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import path from 'node:path';import os from 'node:os';import {createHash} from 'node:crypto';import {deflateSync} from 'node:zlib';
import {StateStore} from '../store.mjs';import {LocalAssets} from '../local-assets.mjs';import {ProductionInput,productionVersion} from '../production-input.mjs';import {CurrentProduction} from '../current-production.mjs';import {createState,importBundle,editPost,setFinalReview,finalReviewStatus} from '../domain.mjs';
import {AutoProductionLink} from '../auto-production-link.mjs';import {createStudioServer} from '../server.mjs';
import {CheckpointProductionInput} from '../checkpoint-production-input.mjs';
const sha=b=>createHash('sha256').update(b).digest('hex');
test('checkpoint directory traversal is rejected before reading files',()=>{
 assert.throws(()=>new CheckpointProductionInput(path.resolve('fixture'),null,{checkpointDirectory:'../secret'}),/production_checkpoint_directory_invalid/);
});
test('relocated checkpoint inputs link once and preserve current verdict and memo after worker restart',()=>fixture(async({base,root,row,store,worker,config,writeRow,assets,input})=>{
 await writeRow({...row,status:'rendering'});
 const run=path.join(base,'delivered'),output=path.join(run,'outputs','fixture'),checks=path.join(run,'checkpoints','relocated');
 await fs.mkdir(path.dirname(output),{recursive:true});
 await fs.cp(path.join(base,'material','06_자동 제작 결과','fixture'),output,{recursive:true});
 await fs.mkdir(checks,{recursive:true});
 const changed={...row,reviewRound:'delivered-version'},files=[];
 for(const name of ['production-plan.json','integrity-audit.json','rendered/slide-001.png'])files.push({name,sha256:sha(await fs.readFile(path.join(output,name)))});
 await fs.writeFile(path.join(checks,'post.json'),JSON.stringify({state:'complete',id:row.id,changed,
  versionLinks:{newOutputVersion:productionVersion(changed)},target:output,completedAt:'2026-10-10T00:00:00Z',files}));
 await store.write(path.join(root,'auto-production-link.json'),{...config,checkpoint_roots:[run],checkpoint_directory:'checkpoints/relocated'});
 assert.equal((await worker.run()).linked,1);
 await store.mutate(s=>setFinalReview(s,row.id,'passed',s.posts[0].revision,'2026-10-10T00:00:00Z'));
 await store.mutate(s=>editPost(s,row.id,{review_note:'Latest user memo'},s.posts[0].revision));
 const current=await store.read();
 assert.equal((await worker.run()).linked,0);
 const restarted=new AutoProductionLink(input,root,store,assets);
 assert.equal((await restarted.run()).linked,0);
 assert.deepEqual(await store.read(),current);
}));
function png(width=1080,height=1440){const crc=b=>{let c=0xffffffff;for(const x of b){c^=x;for(let i=0;i<8;i++)c=(c>>>1)^((c&1)?0xedb88320:0);}return(c^0xffffffff)>>>0;};const chunk=(type,b)=>{const t=Buffer.from(type),out=Buffer.alloc(b.length+12);out.writeUInt32BE(b.length);t.copy(out,4);b.copy(out,8);out.writeUInt32BE(crc(Buffer.concat([t,b])),b.length+8);return out;};const header=Buffer.alloc(13);header.writeUInt32BE(width);header.writeUInt32BE(height,4);header[8]=8;header[9]=2;return Buffer.concat([Buffer.from([137,80,78,71,13,10,26,10]),chunk('IHDR',header),chunk('IDAT',deflateSync(Buffer.alloc((width*3+1)*height))),chunk('IEND',Buffer.alloc(0))]);}
async function fixture(fn){const base=await fs.mkdtemp(path.join(os.tmpdir(),'studio-auto-link-'));let app;try{const root=path.join(base,'local'),material=path.join(base,'material'),output=path.join(material,'06_자동 제작 결과'),folder=path.join(output,'fixture');await fs.mkdir(path.join(folder,'rendered'),{recursive:true});const store=new StateStore(root),assets=new LocalAssets(root),old=await assets.add({name:'old',mime:'image/png',base64:png(10,10).toString('base64')});await store.mutate(s=>importBundle(s,{bundle_id:'old',posts:[{post_id:'source-example',output_version:'old',caption:'My edited caption',images:[{asset_id:old.asset_id,mime:old.mime,order:1}],production_caption_status:'authored'}]}));await store.mutate(s=>setFinalReview(s,'source-example','passed',s.posts[0].revision,'2026-10-09T00:00:00Z'));await store.mutate(s=>editPost(s,'source-example',{review_note:'Old private memo'},s.posts[0].revision));const state=await store.read();state.posts[0].accounts.instagram='chosen-account';state.posts[0].current_layout={activated:true,output_version:'old'};await store.write(store.file,state);await store.write(path.join(root,'current-layout-selection.json'),{schema:1,kind:'current-layout-selection',dynamic:true,entries:[{post_id:'source-example',output_version:'old'}]});const bytes=png(),row={id:'source-example',title:'Title',status:'generated',intakeAuditPassed:true,renderedPages:1,sourceFingerprint:sha('source'),outputSha256:sha('output'),ruleVersion:'portrait-fixture',outputFolder:'fixture',images:[{name:'rendered/slide-001.png',sha256:sha(bytes),width:1080,height:1440}]};const writeRow=async r=>{await fs.writeFile(path.join(output,'status.json'),JSON.stringify({entries:[r]}));};await fs.writeFile(path.join(folder,'rendered','slide-001.png'),bytes);await fs.writeFile(path.join(folder,'production-plan.json'),JSON.stringify({publishCaption:'Producer caption'}));await fs.writeFile(path.join(folder,'integrity-audit.json'),JSON.stringify({ok:true,issues:[]}));await writeRow(row);const config={schema:1,enabled:true,baseline:[{id:row.id,output_version:sha('baseline-version')}],interval_ms:15000};await store.write(path.join(root,'auto-production-link.json'),config);const input=new ProductionInput(material,assets),worker=new AutoProductionLink(input,root,store,assets);await fn({base,root,store,assets,input,worker,row,writeRow,old,config,setApp:a=>app=a,material});}finally{if(app)await app.close();await fs.rm(base,{recursive:true,force:true});}}
test('completed portrait automatically links, archives old evidence, and keeps local writing and account',()=>fixture(async({root,store,worker})=>{const prior=await store.read();assert.equal((await worker.run()).linked,1);const s=await store.read(),p=s.posts[0];assert.notEqual(p.output_version,'old');assert.equal(p.caption,prior.posts[0].caption);assert.equal(p.accounts.instagram,'chosen-account');assert.equal(p.review_note,'');assert.equal(finalReviewStatus(p).decision,'unreviewed');assert.equal(p.source.verified,false);assert.equal(p.safety.rights,'UNKNOWN');assert.equal(s.jobs.length,0);assert.deepEqual(s.publications,prior.publications);assert.equal(s.archived_posts.length,0);assert.ok(s.post_history[p.post_id].entries.every(e=>e.snapshot.output_version===p.output_version));const dirs=await fs.readdir(path.join(root,'replaced','auto-production'));const archived=JSON.parse(await fs.readFile(path.join(root,'replaced','auto-production',dirs[0],'previous-post.json'),'utf8'));assert.equal(archived.post.review_note,'Old private memo');assert.deepEqual(archived.post.final_review,prior.posts[0].final_review);}));
test('restart never repeats the same version or imports a baseline older result',()=>fixture(async({root,store,assets,input,worker,row,writeRow,config})=>{await worker.run();const before=await store.read();const restarted=new AutoProductionLink(input,root,store,assets);assert.equal((await restarted.run()).linked,0);assert.deepEqual(await store.read(),before);config.baseline=[{id:row.id,output_version:productionVersion(row)}];await store.write(path.join(root,'auto-production-link.json'),config);const changed={...row,reviewRound:'other'};await writeRow(changed);await restarted.run();await writeRow(row);assert.equal((await restarted.run()).linked,0);assert.equal((await store.read()).posts[0].output_version,productionVersion(changed));}));
test('incomplete result, tampered hash and square layout stay waiting without changing reviews',()=>fixture(async({worker,row,writeRow,store})=>{const before=await store.read();for(const patch of [{status:'rendering'},{intakeAuditPassed:false},{images:[{...row.images[0],sha256:'a'.repeat(64)}]},{images:[{...row.images[0],width:1080,height:1080}]}]){await writeRow({...row,...patch});const r=await worker.run();assert.equal(r.linked,0);assert.equal(r.waiting.length,1);assert.deepEqual(await store.read(),before);}}));
test('missing or failed integrity audit cannot activate a producer result',()=>fixture(async({base,worker,store})=>{const file=path.join(base,'material','06_자동 제작 결과','fixture','integrity-audit.json');await fs.writeFile(file,JSON.stringify({ok:false,issues:['incomplete']}));const before=await store.read();assert.equal((await worker.run()).linked,0);assert.deepEqual(await store.read(),before);}));
test('archive failure leaves current data and verdict untouched',()=>fixture(async({worker,store})=>{const before=await store.read();worker.archive=async()=>{throw Object.assign(Error('disk'),{code:'archive_failed'});};const r=await worker.run();assert.equal(r.linked,0);assert.equal(r.waiting[0].code,'archive_failed');assert.deepEqual(await store.read(),before);}));
test('dynamic current catalog follows newly activated versions without accepting unrelated versions',()=>fixture(async({root,store,assets,input,worker})=>{await worker.run();const current=new CurrentProduction(input,root,store,assets),catalog=await current.catalog();assert.equal(catalog.entries[0].output_version,(await store.read()).posts[0].output_version);await store.mutate(state=>{const s=structuredClone(state);s.posts[0].output_version='unverified';s.revision++;return s;});await assert.rejects(current.catalog(),/current_layout_version_changed/);}));
test('local server starts the automatic linker and exposes its real status',()=>fixture(async({root,material,store,setApp})=>{const app=await createStudioServer({root,materialRoot:material,port:0,seedTags:false});setApp(app);const status=await(await fetch(app.url+'/api/production/auto-status')).json();assert.equal(status.enabled,true);assert.equal(status.linked,1);assert.equal(status.externalCalls,0);assert.notEqual((await store.read()).posts[0].output_version,'old');assert.equal((await fetch(app.url+'/api/publish',{method:'POST'})).status,405);}));
test('retired assets are moved only after the recovery backup no longer references them',()=>fixture(async({worker,store,old,root})=>{await worker.run();assert.ok(await fs.stat(path.join(root,'assets',old.asset_id)));await store.mutate(s=>editPost(s,'source-example',{review_note:'New memo'},s.posts[0].revision));await worker.run();await assert.rejects(fs.stat(path.join(root,'assets',old.asset_id)),e=>e.code==='ENOENT');assert.equal((await store.read()).posts[0].review_note,'New memo');}));
test('completion after server startup is picked up by the timer without a browser import',()=>fixture(async({root,material,store,setApp,row,writeRow,config})=>{await store.write(path.join(root,'auto-production-link.json'),{...config,interval_ms:1000});await writeRow({...row,status:'rendering'});const app=await createStudioServer({root,materialRoot:material,port:0,seedTags:false});setApp(app);assert.equal((await store.read()).posts[0].output_version,'old');await writeRow(row);const deadline=Date.now()+5000;while((await store.read()).posts[0].output_version==='old'&&Date.now()<deadline)await new Promise(r=>setTimeout(r,100));assert.equal((await store.read()).posts[0].output_version,productionVersion(row));}));
test('an edit during image verification wins and the next scan keeps that writing',()=>fixture(async({worker,input,store})=>{const bundle=input.bundle.bind(input);let first=true;input.bundle=async selected=>{const result=await bundle(selected);if(first){first=false;await store.mutate(s=>editPost(s,'source-example',{caption:'Newest user writing'},s.posts[0].revision));}return result;};const held=await worker.run();assert.equal(held.linked,0);assert.equal(held.waiting[0].code,'automatic_version_conflict');assert.equal((await store.read()).posts[0].output_version,'old');assert.equal((await worker.run()).linked,1);assert.equal((await store.read()).posts[0].caption,'Newest user writing');}));
test('new completed IDs join the dynamic current list without duplicating existing posts',()=>fixture(async({worker,row,writeRow,input,root,store,assets})=>{const newRow={...row,id:'source-new'};await writeRow(newRow);assert.equal((await worker.run()).linked,1);const state=await store.read();assert.equal(state.posts.length,2);assert.equal(state.posts[0].output_version,'old');assert.equal(new CurrentProduction(input,root,store,assets) instanceof CurrentProduction,true);assert.equal((await new CurrentProduction(input,root,store,assets).catalog()).entries.length,2);assert.equal((await worker.run()).linked,0);}));
test('packaged producer completion checkpoints link without promoting the installed status file',()=>fixture(async({base,root,row,store,worker,config,writeRow})=>{await writeRow({...row,status:'rendering'});const run=path.join(base,'packaged'),output=path.join(run,'outputs','fixture'),checks=path.join(run,'work','checkpoints');await fs.mkdir(path.dirname(output),{recursive:true});await fs.cp(path.join(base,'material','06_자동 제작 결과','fixture'),output,{recursive:true});await fs.mkdir(checks,{recursive:true});const changed={...row,reviewRound:'packaged-new'},files=[];for(const name of ['production-plan.json','integrity-audit.json','rendered/slide-001.png'])files.push({name,sha256:sha(await fs.readFile(path.join(output,name)))});const checkpoint={state:'complete',id:row.id,changed,versionLinks:{newOutputVersion:productionVersion(changed)},target:output,completedAt:'2026-10-10T00:00:00Z',files};await fs.writeFile(path.join(checks,'post.json'),JSON.stringify(checkpoint));await store.write(path.join(root,'auto-production-link.json'),{...config,checkpoint_roots:[run]});assert.equal((await worker.run()).linked,1);assert.equal((await store.read()).posts[0].output_version,productionVersion(changed));assert.equal((await worker.run()).linked,0);const corrupt={...checkpoint,changed:{...changed,reviewRound:'corrupt'}};corrupt.versionLinks={newOutputVersion:productionVersion(corrupt.changed)};corrupt.completedAt='2026-10-10T01:00:00Z';corrupt.files=[{name:'integrity-audit.json',sha256:'a'.repeat(64)}];await fs.writeFile(path.join(checks,'post.json'),JSON.stringify(corrupt));const before=await store.read(),held=await worker.run();assert.equal(held.linked,0);assert.ok(held.waiting.some(e=>e.code==='production_checkpoint_changed'));assert.deepEqual(await store.read(),before);}));
