import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {spawn,spawnSync} from 'node:child_process';
import {createStudioServer} from '../server.mjs';
import assert from 'node:assert/strict';
const root=await fs.mkdtemp(path.join(os.tmpdir(),'upload-studio-browser-'));
const studioRoot=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const out=path.join(studioRoot,'evidence');await fs.mkdir(out,{recursive:true});
let chrome,app,socket;const calls=new Map(),events=new Map();let serial=0,external=0,heldImport=null,holdImport=false;
const wait=ms=>new Promise(r=>setTimeout(r,ms));
async function until(fn){for(let i=0;i<300;i++){const x=await fn();if(x)return x;await wait(100);}throw Error('browser_condition_timeout');}
function send(method,params={}){return new Promise((resolve,reject)=>{const id=++serial,timer=setTimeout(()=>{calls.delete(id);reject(Error('CDP timeout: '+method));},10000);calls.set(id,{resolve:v=>{clearTimeout(timer);resolve(v);},reject:e=>{clearTimeout(timer);reject(e);}});socket.send(JSON.stringify({id,method,params}));});}
const evaluate=async expression=>{const r=await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw Error(r.exceptionDetails.text);return r.result.value;};
async function click(selector){const rect=await evaluate('(()=>{const e=document.querySelector('+JSON.stringify(selector)+');if(!e)throw Error("missing element");e.scrollIntoView({block:"center"});const r=e.getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2};})()');await send('Input.dispatchMouseEvent',{type:'mousePressed',button:'left',clickCount:1,...rect});await send('Input.dispatchMouseEvent',{type:'mouseReleased',button:'left',clickCount:1,...rect});}
async function fill(selector,text){await click(selector);await send('Input.dispatchKeyEvent',{type:'rawKeyDown',key:'a',code:'KeyA',windowsVirtualKeyCode:65,modifiers:2});await send('Input.dispatchKeyEvent',{type:'keyUp',key:'a',code:'KeyA',windowsVirtualKeyCode:65,modifiers:2});await send('Input.insertText',{text});}
async function shot(name){await evaluate('window.scrollTo(0,0)');const {data}=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});await fs.writeFile(path.join(out,name),Buffer.from(data,'base64'));console.log('SCREENSHOT_BASE64 '+name+' '+data);}
async function api(route,body){const r=await fetch(app.url+route,{method:body?'POST':'GET',headers:body?{'content-type':'application/json','x-studio-local':'1'}:{},body:body?JSON.stringify(body):undefined});const v=await r.json();assert.equal(r.status,200,JSON.stringify(v));return v;}
try{
 const material=path.join(root,'production-materials'),folder=path.join(material,'06_자동 제작 결과','fixture','rendered');await fs.mkdir(folder,{recursive:true});
 const bytes=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Wl2ol8AAAAASUVORK5CYII=','base64'),{createHash}=await import('node:crypto');
 const imageFile=path.join(folder,'slide-001.png'),statusFile=path.join(folder,'..','..','status.json');await fs.writeFile(imageFile,bytes);await fs.writeFile(path.join(folder,'..','production-plan.json'),JSON.stringify({publishCaption:'자동 연결 문안\\n\\n기존 게시 입력'}));
 const rows=Array.from({length:3},(_,i)=>({id:'auto-'+i,title:'자동 연결 제목 '+i,sourceUrl:'https://example.invalid/source',sourceFingerprint:'s',outputSha256:'o',ruleVersion:'r',reviewRound:'review-round',outputFolder:'fixture',images:[{name:'rendered/slide-001.png',sha256:createHash('sha256').update(bytes).digest('hex')}]}));await fs.writeFile(statusFile,JSON.stringify({entries:rows}));
  for(const file of ['domain.mjs','store.mjs','server.mjs','adapter.mjs','planner-worker.mjs','local-assets.mjs','public/studio.js','public/icons.mjs','public/draft-backups.mjs','production-input.mjs','production-sync.mjs','title-normalization.mjs']){const r=spawnSync(process.execPath,['--check',path.join(studioRoot,file)],{encoding:'utf8'});assert.equal(r.status,0,r.stderr);}
  let executable;for(const p of [path.join(process.env.PROGRAMFILES||'C:\\Program Files','Google','Chrome','Application','chrome.exe'),path.join(process.env['PROGRAMFILES(X86)']||'C:\\Program Files (x86)','Google','Chrome','Application','chrome.exe'),'/usr/bin/google-chrome','/usr/bin/google-chrome-stable','/usr/bin/chromium','/usr/bin/chromium-browser']){try{await fs.access(p);executable=p;break;}catch{}}
  if(!executable)throw Error('actual_browser_unavailable');
  app=await createStudioServer({root:path.join(root,'data'),port:0,materialRoot:path.join(root,'production-materials')});
  chrome=spawn(executable,['--headless=new','--disable-gpu','--disable-background-networking','--disable-component-update','--disable-sync','--disable-default-apps','--no-first-run','--no-default-browser-check','--remote-debugging-port=0','--remote-debugging-address=127.0.0.1','--user-data-dir='+path.join(root,'chrome'),'about:blank'],{stdio:['ignore','ignore','pipe'],windowsHide:true});
  let errors='';chrome.stderr.on('data',c=>errors+=String(c));chrome.on('error',e=>errors+=e.message);
  const port=await until(async()=>{try{return (await fs.readFile(path.join(root,'chrome','DevToolsActivePort'),'utf8')).split('\n')[0];}catch{if(chrome.exitCode!==null)throw Error('Chrome exited: '+errors.slice(-1200));return null;}});
  const pages=await fetch('http://127.0.0.1:'+port+'/json/list').then(r=>r.json());socket=new WebSocket(pages.find(x=>x.type==='page').webSocketDebuggerUrl);
  socket.addEventListener('message',event=>{const msg=JSON.parse(String(event.data));if(msg.id){const c=calls.get(msg.id);if(c){calls.delete(msg.id);msg.error?c.reject(Error(msg.error.message)):c.resolve(msg.result);}}else events.get(msg.method)?.(msg.params);});
  await new Promise((resolve,reject)=>{socket.addEventListener('open',resolve,{once:true});socket.addEventListener('error',reject,{once:true});});
  await send('Page.enable');await send('Runtime.enable');await send('Network.enable');await send('Fetch.enable',{patterns:[{urlPattern:'*'}]});
  events.set('Fetch.requestPaused',p=>{if(holdImport&&p.request.url===app.url+'/api/production/import'){heldImport=p.requestId;return;}if(p.request.url.startsWith(app.url+'/')||p.request.url.startsWith('data:')||p.request.url.startsWith('blob:'))send('Fetch.continueRequest',{requestId:p.requestId}).catch(()=>{});else {external++;send('Fetch.failRequest',{requestId:p.requestId,errorReason:'BlockedByClient'}).catch(()=>{});}});
  await send('Emulation.setDeviceMetricsOverride',{width:1600,height:1400,deviceScaleFactor:1,mobile:false});await send('Emulation.setTimezoneOverride',{timezoneId:'Asia/Seoul'});

 await send('Page.navigate',{url:app.url});await until(()=>evaluate('document.querySelectorAll("#post-list [data-post]").length===3 && document.querySelector("#production-sync-state").textContent.includes("3개 연결")'));
 assert.equal(await evaluate('document.querySelector("#caption").value'),'자동 연결 문안\\n\\n기존 게시 입력');assert.equal((await api('/api/state')).state.jobs.length,0);await shot('04-startup-autoload.png');
 await fill('#caption','사용자 편집\\n\\n끝 공백  ');await until(()=>evaluate('document.querySelector("#save-state").textContent==="로컬 저장 완료"'));
 await click('[data-platform="instagram"]');await click('[name="timing"][value="planned"]');await evaluate('(()=>{const x=document.querySelector("#local-time");x.value="2026-10-12T18:00";x.dispatchEvent(new Event("change",{bubbles:true}));})()');await until(async()=>{const p=(await api('/api/state')).state.posts[0];return p.targets.length===1&&p.timing.due_at==='2026-10-12T09:00:00.000Z';});
 await click('#load-production');await until(()=>evaluate('document.querySelector("#production-dialog").open'));await click('#production-all');assert.equal(await evaluate('document.querySelector("#production-count").textContent'),'3 / 3개 선택');await click('#production-none');assert.equal(await evaluate('document.querySelector("#production-count").textContent'),'0 / 3개 선택');assert.equal(await evaluate('document.querySelector("#import-production").disabled'),true);
 await click('[data-production-id="auto-1"]');await click('[data-production-id="auto-2"]');assert.equal(await evaluate('document.querySelector("#production-count").textContent'),'2 / 3개 선택');await shot('05-multiple-selection.png');holdImport=true;await click('#import-production');await until(()=>heldImport);await click('#close-production');await fill('#caption','동기화 중 편집\\n\\n다른 글에 넣지 않는다.');holdImport=false;await send('Fetch.continueRequest',{requestId:heldImport});heldImport=null;await until(()=>evaluate('document.querySelector("#status").textContent.startsWith("선택한 2개 글 동기화")));assert.equal(await evaluate('document.querySelector("#caption").value'),'자동 연결 문안\\n\\n기존 게시 입력');await click('[data-post="auto-0"]');await until(()=>evaluate('document.querySelector("#identity").textContent.includes("auto-0")'));
 assert.equal((await api('/api/state')).state.posts[0].caption,'동기화 중 편집\\n\\n다른 글에 넣지 않는다.');await fill('#caption','사용자 편집\\n\\n끝 공백  ');await until(()=>evaluate('document.querySelector("#save-state").textContent==="로컬 저장 완료"'));
 let saved=(await api('/api/state')).state;assert.equal(saved.posts.length,3);assert.equal(saved.posts[0].caption,'사용자 편집\\n\\n끝 공백  ');
 await evaluate('window.__reloadMarker=true');await send('Page.reload');await until(()=>evaluate('window.__reloadMarker!==true && document.querySelector("#production-sync-state")?.textContent.includes("3개 연결")'));assert.equal(await evaluate('document.querySelector("#caption").value'),'사용자 편집\\n\\n끝 공백  ');
 await app.close();app=await createStudioServer({root:path.join(root,'data'),port:0,materialRoot:material});await send('Page.navigate',{url:app.url});await until(()=>evaluate('document.querySelector("#production-sync-state")?.textContent.includes("3개 연결")'));saved=(await api('/api/state')).state;assert.equal(saved.posts.length,3);assert.deepEqual(saved.posts[0].targets,['threads']);assert.equal(saved.posts[0].timing.due_at,'2026-10-12T09:00:00.000Z');
 await evaluate('(()=>{document.querySelector(".review-panel").open=true;document.querySelector("#review-note").value="저장 전 검수 메모";document.querySelector("#source-url").value="https://example.invalid/unsaved";})()');await wait(16000);assert.equal(await evaluate('document.querySelector("#review-note").value'),'저장 전 검수 메모');assert.equal(await evaluate('document.querySelector("#source-url").value'),'https://example.invalid/unsaved');
 const version=saved.posts[0].output_version;rows[0].reviewRound='updated-round';rows.push({...rows[2],id:'auto-3'});await fs.writeFile(statusFile,JSON.stringify({entries:rows}));await until(async()=>{const s=(await api('/api/state')).state;return s.posts.length===4&&s.posts[0].output_version!==version;});saved=(await api('/api/state')).state;await until(()=>evaluate('!document.querySelector("#review-version-change").hidden'));assert.equal(await evaluate('document.querySelector("#review-note").value'),'저장 전 검수 메모');assert.equal(await evaluate('document.querySelector("#save-review").disabled'),true);
 assert.equal(saved.posts[0].caption,'사용자 편집\\n\\n끝 공백  ');assert.deepEqual(saved.posts[0].targets,['threads']);assert.equal(saved.posts[0].timing.due_at,'2026-10-12T09:00:00.000Z');assert.equal(saved.posts[0].approval,null);assert.equal(saved.jobs.length,0);assert.equal(saved.publications.length,0);assert.deepEqual(await fs.readFile(imageFile),bytes);assert.equal(external,0);
 await app.close();await fs.writeFile(path.join(folder,'..','production-plan.json'),JSON.stringify({displayTitle:'wrong-contract'}));app=await createStudioServer({root:path.join(root,'data'),port:0,materialRoot:material});await send('Page.navigate',{url:app.url});await until(()=>evaluate('document.querySelector("#production-sync-state")?.textContent.includes("production_title_contract_changed")'));await fs.writeFile(path.join(folder,'..','production-plan.json'),JSON.stringify({publishCaption:'자동 연결 문안\\n\\n기존 게시 입력'}));rows.push({...rows[2],id:'auto-4'});await fs.writeFile(statusFile,JSON.stringify({entries:rows}));await until(async()=>(await api('/api/state')).state.posts.length===5);assert.equal((await api('/api/state')).state.posts[0].caption,'사용자 편집\\n\\n끝 공백  ');assert.equal(external,0);
 console.log('AUTOLOAD_BROWSER_PASS initial3 posts/captions/images; multiple/all/none selection; bulk sync; reload and process restart preservation; automatic new-version/new-post polling; jobs0/publications0/external0.');
}finally{socket?.close();chrome?.kill('SIGTERM');if(app)await app.close();await fs.rm(root,{recursive:true,force:true});}
