import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import path from 'node:path';import os from 'node:os';
import {createState,importBundle,setFinalReview,finalReviewStatus,syncProductionBundle,isActivePost} from '../domain.mjs';import {ProductionSync} from '../production-sync.mjs';
let replaceCurrentLayouts,CurrentProduction;
try{({replaceCurrentLayouts}=await import('../current-layout.mjs'));}catch(e){if(e.code!=='ERR_MODULE_NOT_FOUND')throw e;replaceCurrentLayouts=s=>structuredClone(s);}
try{({CurrentProduction}=await import('../current-production.mjs'));}catch(e){if(e.code!=='ERR_MODULE_NOT_FOUND')throw e;CurrentProduction=class{constructor(input){return input;}};}
const image=n=>({asset_id:String(n).repeat(64),order:1,mime:'image/png'});
function fixture(){let s=importBundle(createState(),{bundle_id:'fixture',posts:[{post_id:'source-example',output_version:'old',caption:'Test caption',production_caption_status:'authored',images:[image(1)],review_note:'Previous memo'}]});s=setFinalReview(s,'source-example','passed',s.posts[0].revision,'2026-10-09T00:00:00Z');return s;}
const entry={post_id:'source-example',old_output_version:'old',new_output_version:'new',images:[image(2)],content_verified:true,mapping_sha256:'a'.repeat(64),source_bundle_sha256:'b'.repeat(64)};
const operation={operation_id:'explicit-fresh-replacement',at:'2026-10-10T00:00:00Z'};
test('fresh replacement clears all previous review evidence and keeps input writing',()=>{const s=fixture(),prior=structuredClone(s),next=replaceCurrentLayouts(s,[entry],operation),p=next.posts[0];assert.equal(p.output_version,'new');assert.deepEqual(p.images,[image(2)]);assert.equal(finalReviewStatus(p).decision,'unreviewed');assert.equal(p.review_note,'');assert.equal(p.review,null);assert.equal(p.approval,null);assert.equal(p.publication_approval,null);assert.equal(p.source.verified,false);assert.equal(p.safety.rights,'UNKNOWN');assert.deepEqual(p.production_feedback,{current:null,previous:null});assert.equal(p.caption,prior.posts[0].caption);assert.deepEqual(p.targets,prior.posts[0].targets);assert.deepEqual(s,prior);assert.equal(next.archived_posts.length,0);assert.deepEqual(next.post_history,{});});
test('version mismatch and incomplete replacement reject without touching existing state',()=>{const s=fixture();assert.throws(()=>replaceCurrentLayouts(s,[{...entry,old_output_version:'other'}],operation),/layout_version_conflict/);assert.throws(()=>replaceCurrentLayouts(s,[],operation),/layout_scope_invalid/);assert.equal(finalReviewStatus(s.posts[0]).passed,true);});
test('image-ready current items stay visible even while caption is held',()=>{const s=fixture();s.posts[0].inactive_for_this_batch=true;s.posts[0].production_caption_status='held-structure';const next=replaceCurrentLayouts(s,[entry],operation);assert.equal(isActivePost(next.posts[0]),true);assert.equal(next.posts[0].production_caption_status,'held-structure');assert.equal(finalReviewStatus(next.posts[0]).passed,false);});
test('current selection prevents automatic refresh from resurrecting old layouts or verdicts',async()=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'studio-layout-test-'));try{let saved=fixture();saved.posts[0].output_version='new';const store={read:async()=>saved,mutate:async fn=>{saved=await fn(saved);return saved;}};const input={catalog:async()=>({available:true,entries:[{id:'source-example',output_version:'old'}]}),metadata:async()=>({bundle_id:'old',posts:[{...saved.posts[0],output_version:'old'}]}),bundle:async function(){return this.metadata();}};await fs.writeFile(path.join(dir,'current-layout-selection.json'),JSON.stringify({schema:1,kind:'current-layout-selection',entries:[{post_id:'source-example',output_version:'new'}]}));const current=new CurrentProduction(input,dir,store),sync=new ProductionSync(current,store),before=structuredClone(saved);await sync.run();assert.deepEqual(saved,before);assert.equal((await current.catalog()).entries[0].output_version,'new');await assert.rejects(()=>current.bundle([{id:'source-example',output_version:'old'}]),/production_version_changed/);}finally{await fs.rm(dir,{recursive:true,force:true});}});
test('without a selection ordinary producer input remains unchanged',async()=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'studio-layout-test-'));try{const input={catalog:async()=>({available:true,entries:[]})},current=new CurrentProduction(input,dir,{read:async()=>createState()});assert.deepEqual(await current.catalog(),await input.catalog());}finally{await fs.rm(dir,{recursive:true,force:true});}});
