export async function runDomainSuite(api, assert) {
  const cases=[];const test=async(name,fn)=>{try{await fn();cases.push({name,ok:true});}catch(e){cases.push({name,ok:false,error:e.message});}};
  const bundle=(caption="첫 문단\n\n둘째 문단 🌿  ")=>({bundle_id:"b1",posts:[{post_id:"p1",output_version:"v2",source:{url:"https://example.invalid/source/p1",verified:false,label:"기존 제작글"},caption,tags:"#기록",images:[{asset_id:"a".repeat(64),order:1,mime:"image/jpeg"},{asset_id:"b".repeat(64),order:2,mime:"image/jpeg"}]}]});
  const seeded=()=>api.importBundle(api.createState(),bundle());
  const reviewed=()=>{let s=seeded();return api.editPost(s,"p1",{safety:{fact:"PASS",rights:"PASS",privacy:"PASS",defamation:"PASS",platform_policy:"PASS"},source:{url:"https://example.invalid/source/p1",verified:true,label:"기존 제작글"},review:{output_version:"v2",score:8,decision:"approved",note:"사용자 직접 검수"}},1);};
  await test("preserves long multiline text exactly across edit/export",()=>{const text=("긴 문안 🌿\r\n\r\n줄바꿈 보존  ").repeat(400);let s=api.importBundle(api.createState(),bundle(text));assert.equal(s.posts[0].caption,text);s=api.editPost(s,"p1",{caption:text+"\n끝  "},1);assert.equal(JSON.parse(JSON.stringify(s)).posts[0].caption,text+"\n끝  ");});
  await test("settings remain independent for each post",()=>{const b=bundle();b.posts.push({...b.posts[0],post_id:"p2"});let s=api.importBundle(api.createState(),b);s=api.editPost(s,"p1",{targets:["threads"],timing:{mode:"planned",local:"2026-10-12T18:00",offset_minutes:-540}},1);assert.deepEqual(s.posts[0].targets,["threads"]);assert.deepEqual(s.posts[1].targets,["instagram","threads"]);assert.equal(s.posts[1].timing.mode,"now");assert.equal(s.posts[0].timing.due_at,"2026-10-12T09:00:00.000Z");});
  await test("rejects stale revision instead of losing another edit",()=>{let s=api.editPost(seeded(),"p1",{caption:"새 글"},1);assert.throws(()=>api.editPost(s,"p1",{caption:"오래된 탭"},1),/revision_conflict/);assert.equal(s.posts[0].caption,"새 글");});
  await test("missing rights/source/current review blocks approval",()=>{const s=seeded();assert.throws(()=>api.approveDryRun(s,"p1",1),/review_required/);assert.ok(api.readiness(s.posts[0]).some(x=>x.code==="source_unverified"));});
  await test("current manual review permits dry-run approval only",()=>{let s=reviewed();s=api.approveDryRun(s,"p1",2);assert.equal(s.posts[0].approval.scope,"dry-run");assert.equal(s.posts[0].publication_approval,null);assert.ok(api.readiness(s.posts[0]).some(x=>x.code==="account_unconnected"));});
  await test("image order edit invalidates approval and pending queue",()=>{let s=api.approveDryRun(reviewed(),"p1",2);s=api.queuePost(s,"p1",2);s=api.editPost(s,"p1",{images:[...s.posts[0].images].reverse().map((x,i)=>({...x,order:i+1}))},2);assert.equal(s.posts[0].approval,null);assert.equal(s.jobs[0].state,"waiting");assert.equal(s.jobs[0].stale,true);});
  await test("same queue request is idempotent and new version does not autoqueue",()=>{let s=api.queuePost(seeded(),"p1",1);s=api.queuePost(s,"p1",1);assert.equal(s.jobs.length,1);const b=bundle("새 버전");b.posts[0].output_version="v3";s=api.importBundle(s,b);assert.equal(s.jobs.length,1);assert.equal(s.posts[0].approval,null);assert.equal(s.jobs[0].stale,true);});
  await test("due date never runs without explicit dry-run action",()=>{let s=api.editPost(seeded(),"p1",{timing:{mode:"planned",local:"2020-01-01T09:00",offset_minutes:-540}},1);s=api.queuePost(s,"p1",2);assert.equal(s.jobs[0].state,"scheduled");assert.equal(s.dry_runs.length,0);assert.equal(s.publications.length,0);});
  await test("long platform text remains intact and blocks transport preparation",()=>{let s=api.importBundle(api.createState(),bundle("가".repeat(3000)));assert.equal(s.posts[0].caption.length,3000);const reasons=api.readiness(s.posts[0]);assert.ok(reasons.some(x=>x.code==="instagram_caption_limit"));assert.ok(reasons.some(x=>x.code==="threads_text_limit"));});
  await test("cancelled queue persists and interrupted work requires reconciliation",()=>{let s=api.queuePost(seeded(),"p1",1);s=api.cancelJobs(s,[s.jobs[0].id]);assert.equal(s.jobs[0].state,"cancelled");s.jobs[0].state="running";s=api.recoverJobs(s);assert.equal(s.jobs[0].state,"reconciliation");assert.throws(()=>api.retryJob(s,s.jobs[0].id),/reconciliation_required/);});
  await test("dry-run never creates a real publication or URL",()=>{let s=api.approveDryRun(reviewed(),"p1",2);s=api.queuePost(s,"p1",2);const id=s.jobs[0].id;s=api.startDryRun(s,id);s=api.finishDryRun(s,id,{plans:[{platform:"instagram",dryRun:true,externalCalls:0}],externalCalls:0});assert.equal(s.jobs[0].state,"dry_run_complete");assert.equal(s.publications.length,0);assert.equal(s.dry_runs.length,1);assert.equal(s.dry_runs[0].publication_url,null);});
  await test("secret-shaped bundle keys are refused and never retained",()=>{const b=bundle();b.access_token="DO_NOT_STORE";assert.throws(()=>api.importBundle(api.createState(),b),/secret_field_forbidden/);});
  await test("invalid dates and invalid ordering fail closed",()=>{assert.throws(()=>api.editPost(seeded(),"p1",{timing:{mode:"planned",local:"2026-02-30T18:00",offset_minutes:-540}},1),/invalid_local_time/);const b=bundle();b.posts[0].images[1].order=1;assert.throws(()=>api.importBundle(api.createState(),b),/image_order_invalid/);});
  await test("caption changes require a fresh user review before approval",()=>{let s=api.approveDryRun(reviewed(),"p1",2);s=api.editPost(s,"p1",{caption:"검수 뒤 바뀐 문안"},2);assert.equal(s.posts[0].review,null);assert.throws(()=>api.approveDryRun(s,"p1",3),/review_required/);});
  return cases;
}
