import assert from 'node:assert/strict';import * as d from '../domain.mjs';import * as h from '../history.mjs';
let s=d.createState();s=h.captureHistory(s,d.importBundle(s,{bundle_id:'b',posts:[{post_id:'p',output_version:'v1',caption:'보존 문안',images:[]}]}),'t1');s=h.captureHistory(s,d.editPost(s,'p',{platform_captions:{instagram:''}},1),'t2');assert.equal(s.posts[0].caption,'');const undone=h.undoPost(s,'p',2);assert.equal(undone.posts[0].caption,'보존 문안');assert.equal(undone.posts[0].review,null);assert.equal(undone.posts[0].approval,null);assert.equal(h.captureHistory(s,undone,'t3').post_history.p.entries.length,2);const redo=h.redoPost(undone,'p',undone.posts[0].revision);assert.equal(redo.posts[0].caption,'');const branch=h.captureHistory(undone,d.editPost(undone,'p',{platform_captions:{instagram:'새 수정'}},undone.posts[0].revision),'t4');assert.throws(()=>h.redoPost(branch,'p',branch.posts[0].revision),/redo_unavailable/);assert.throws(()=>h.undoPost(branch,'p',1),/revision_conflict/);for(let i=0;i<30;i++)s=h.captureHistory(s,d.editPost(s,'p',{platform_captions:{instagram:'문안'+i}},s.posts[0].revision),'t'+i);assert.equal(s.post_history.p.entries.length,20);assert.equal(s.publications.length,0);console.log('Persistent undo/redo/history branching, revision checks and approval reset passed.');

const legacy=d.createState();legacy.revision=1;legacy.posts=[{...s.posts[0],platform_captions:undefined}];const migrated=h.captureHistory(legacy,d.editPost(legacy,'p',{tags:'#복원'},legacy.posts[0].revision),'legacy');assert.equal(h.historyFor(migrated,'p').entries.length,2);assert.equal(h.undoPost(migrated,'p',migrated.posts[0].revision).posts[0].caption,legacy.posts[0].caption);
const current=d.syncProductionBundle(s,{posts:[{post_id:'p',output_version:'v2',source:{cover_title:'현재 표지 제목'},threads_title_only:true,platform_captions:{instagram:'새 원문 문안',threads:'새 요약'},images:[]}]});assert.equal(d.platformCaption(current.posts[0],'threads'),'현재 표지 제목');assert.equal(d.finalCaption({...current.posts[0],tags:'#이야기'},'threads'),'현재 표지 제목');assert.equal(current.posts[0].platform_captions.threads,s.posts[0].platform_captions.threads);const after=h.captureHistory(s,current,'new-version');const restored=h.restorePostSnapshot(after,'p',after.post_history.p.entries[0].id,after.posts[0].revision);assert.equal(restored.posts[0].output_version,'v2');assert.equal(restored.posts[0].restored_from_output_version,'v1');assert.equal(restored.posts[0].source.verified,false);

const retained=d.createState();retained.posts=Array.from({length:199},(_,i)=>({post_id:'source-'+i,production_caption_status:i<186?'authored':'awaiting-authored-captions'}));assert.deepEqual(d.activePostCounts(retained),{active:186,stored:199,held:13,source_deleted:0});assert.equal(retained.posts.length,199);assert.throws(()=>d.queuePost({...retained,jobs:[]},'source-198',undefined),/post_out_of_active_scope/);
const common=d.setCommonTags(branch,['이야기','읽을거리'],branch.revision);assert.deepEqual(common.posts[0].common_tags,['이야기','읽을거리']);assert.equal(common.posts[0].approval,null);assert.equal(common.posts[0].review,null);assert.throws(()=>d.setCommonTags(common,[],common.revision-1),/revision_conflict/);

let held=d.syncProductionBundle(d.createState(),{posts:[{post_id:'source-held',output_version:'v1',production_caption_status:'awaiting-authored-captions',caption:'보관 원문',images:[]}]});held=d.syncProductionBundle(held,{posts:[{post_id:'source-held',output_version:'v1',production_caption_status:'authored',caption:'후속 제작 문안',images:[]}]});assert.equal(d.isActivePost(held.posts[0]),false);assert.equal(held.posts.length,1);
