import './platform-schedule.test.mjs';
import './contract.test.mjs';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {createHash} from 'node:crypto';
import {ProductionInput,productionVersion} from '../production-input.mjs';
import {LocalAssets} from '../local-assets.mjs';
import {DraftBackups,BACKUP_PREFIX} from '../public/draft-backups.mjs';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import * as domain from '../domain.mjs';
import {runDomainSuite} from './domain-suite.mjs';
import {StateStore} from '../store.mjs';
import {offlinePlan} from '../adapter.mjs';
import {createStudioServer} from '../server.mjs';
import {PublicationJournal} from '../vendor/publication-journal.mjs';
const cases=await runDomainSuite(domain,assert);for(const c of cases)assert.ok(c.ok,c.name+': '+(c.error||''));console.log('domain: '+cases.length+' passed');
const roots=[];const temporary=async()=>{const r=await fs.mkdtemp(path.join(os.tmpdir(),'upload-studio-test-'));roots.push(r);return r;};
async function fixtureProduction(base){const material=path.join(base,'자료'),folder=path.join(material,'06_자동 제작 결과','fixture','rendered');await fs.mkdir(folder,{recursive:true});const bytes=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Wl2ol8AAAAASUVORK5CYII=','base64'),row={id:'production-fixture',title:'실제 제작 입력 계약 시험',sourceUrl:'https://example.invalid/original',sourceFingerprint:'source-v1',outputSha256:'zip-v1',ruleVersion:'rule-v1',outputFolder:'fixture',images:[{name:'rendered/slide-001.png',sha256:createHash('sha256').update(bytes).digest('hex')}]};const imageFile=path.join(folder,'slide-001.png'),planFile=path.join(folder,'..','production-plan.json'),statusFile=path.join(material,'06_자동 제작 결과','status.json');await fs.writeFile(imageFile,bytes);await fs.writeFile(planFile,JSON.stringify({publishCaption:'[ 실제 제작 문안 ]\n\n원문에 따른 내용이다.  '}));await fs.writeFile(statusFile,JSON.stringify({entries:[row]}));return {material,row,planFile,imageFile,statusFile};}
let count=cases.length;
async function check(name,fn){await fn();count++;console.log('PASS '+name);}
try {
await check('disk save preserves long text on a fresh store instance',async()=>{const r=await temporary(),store=new StateStore(r);await store.mutate(s=>domain.importBundle(s,{bundle_id:'b',posts:[{post_id:'p1',output_version:'v1',caption:'첫줄\n\n끝  '.repeat(500)}]}));const after=await new StateStore(r).read();assert.equal(after.posts[0].caption,'첫줄\n\n끝  '.repeat(500));});
await check('two store instances serialize competing edits without losing state',async()=>{const r=await temporary(),a=new StateStore(r),b=new StateStore(r);await a.mutate(s=>domain.importBundle(s,{bundle_id:'b',posts:[{post_id:'p',output_version:'v1'}]}));const res=await Promise.allSettled([a.mutate(s=>domain.editPost(s,'p',{caption:'A'},1)),b.mutate(s=>domain.editPost(s,'p',{caption:'B'},1))]);assert.equal(res.filter(x=>x.status==='fulfilled').length,1);assert.match(res.find(x=>x.status==='rejected').reason.message,/revision_conflict/);assert.equal((await a.read()).posts[0].revision,2);});
await check('corrupt state is blocked while the previous backup remains recoverable',async()=>{const r=await temporary(),a=new StateStore(r);await a.mutate(s=>domain.importBundle(s,{bundle_id:'b',posts:[{post_id:'p',output_version:'v1',caption:'保존'}]}));await a.mutate(s=>domain.editPost(s,'p',{caption:'새로운 글'},1));await fs.writeFile(path.join(r,'state.json'),'{bad');await assert.rejects(a.read(),/state_corrupt/);const b=await a.restoreBackup();assert.equal(b.posts[0].caption,'保존');assert.ok((await fs.readdir(r)).some(x=>x.startsWith('state.corrupt.')));});
await check('official planners run with an empty worker environment and no network',async()=>{const p={post_id:'p',output_version:'v1',caption:'줄1\n\n줄2',tags:'#태그',targets:['instagram','threads'],images:[{asset_id:'a'.repeat(64),order:1,mime:'image/jpeg'},{asset_id:'b'.repeat(64),order:2,mime:'image/jpeg'}]};const plans=await offlinePlan(p);assert.equal(plans.length,2);for(const x of plans){assert.equal(x.externalCalls,0);assert.equal(x.dryRun,true);assert.equal(x.capability.configured,false);assert.equal(x.localOnly,true);assert.match(x.mediaUrls[0],/example.invalid\/local\/a/);}assert.equal(plans[0].steps.at(-2).params.caption,'줄1\n\n줄2\n\n#태그');assert.equal(plans[1].mediaCount,2);});
await check('existing publication journal replays a local dry-run without executing again',async()=>{const r=await temporary(),j=new PublicationJournal(r);let calls=0;const args={provider:'offline-preview',candidateId:'p',approvalBasis:'v1',accountKey:'unconnected-instagram',payload:{caption:'원문'},publish:async()=>{calls++;return {dryRun:true,externalCalls:0};}};await j.execute(args);const replay=await new PublicationJournal(r).execute(args);assert.equal(replay.replayed,true);assert.equal(calls,1);await assert.rejects(j.execute({...args,payload:{caption:'바뀜'}}),/같은 승인/);});
await check('ambiguous journal error prevents replay after restart',async()=>{const r=await temporary(),args={provider:'offline-preview',candidateId:'p',approvalBasis:'v1',accountKey:'unconnected-threads',payload:{caption:'원문'},publish:async()=>{throw Error('fixture-failure');}};await assert.rejects(new PublicationJournal(r).execute(args),/fixture-failure/);await assert.rejects(new PublicationJournal(r).execute(args),/중복 게시/);});
await check('loopback server saves/restarts and refuses live, foreign origin and secret fields',async()=>{const r=await temporary();let app=await createStudioServer({root:r,port:0});const request=(route,body,extra={})=>fetch(app.url+route,{method:body===undefined?'GET':'POST',headers:body===undefined?{}:{'content-type':'application/json','x-studio-local':'1',...extra},body:body===undefined?undefined:JSON.stringify(body)});
try{let response=await request('/api/bundles',{bundle_id:'b',posts:[{post_id:'p',output_version:'v1',caption:'긴 글\n\n마지막  '.repeat(300)}]});assert.equal(response.status,200);response=await request('/api/posts/p',{expected_revision:1,patch:{targets:['threads']}});assert.equal(response.status,200);assert.equal((await response.json()).state.posts[0].caption,'긴 글\n\n마지막  '.repeat(300));assert.equal((await request('/api/publish',{})).status,405);assert.equal((await request('/api/schedule',{})).status,405);assert.equal((await request('/api/posts/p',{expected_revision:2,patch:{caption:'공격'}},{Origin:'https://example.invalid'})).status,403);assert.equal((await request('/api/bundles',{bundle_id:'bad',access_token:'DO_NOT_STORE',posts:[]})).status,400);assert.equal((await request('/api/queue',{post_id:'p',expected_revision:2})).status,200);
}finally{await app.close();}app=await createStudioServer({root:r,port:0});try{const s=await request('/api/state').then(x=>x.json());assert.deepEqual(s.state.posts[0].targets,['threads']);assert.equal(s.state.jobs.length,1);assert.equal(s.state.publications.length,0);}finally{await app.close();}});
await check('local image asset bytes are retrieved only from the local vault',async()=>{const r=await temporary(),app=await createStudioServer({root:r,port:0});try{const bytes=Buffer.from([255,216,255,224,1,2,255,217]);const response=await fetch(app.url+'/api/assets',{method:'POST',headers:{'content-type':'application/json','x-studio-local':'1'},body:JSON.stringify({name:'fixture.jpg',mime:'image/jpeg',base64:bytes.toString('base64')})});assert.equal(response.status,200);const asset=(await response.json()).asset;const read=await fetch(app.url+'/assets/'+asset.asset_id);assert.equal(read.headers.get('content-type'),'image/jpeg');assert.deepEqual(Buffer.from(await read.arrayBuffer()),bytes);assert.equal((await fetch(app.url+'/assets/../../state.json')).status,404);}finally{await app.close();}});
await check('HTTP dry-run records only dry-run history and survives restart',async()=>{const r=await temporary();let app=await createStudioServer({root:r,port:0});const req=(route,body)=>fetch(app.url+route,{method:body?'POST':'GET',headers:body?{'content-type':'application/json','x-studio-local':'1'}:{},body:body?JSON.stringify(body):undefined}).then(async x=>{const result=await x.json();assert.equal(x.status,200,JSON.stringify(result));return result;});
try{const asset=(await req('/api/assets',{name:'local.jpg',mime:'image/jpeg',base64:Buffer.from([255,216,255,224,1,2,255,217]).toString('base64')})).asset;await req('/api/bundles',{bundle_id:'b',posts:[{post_id:'p',output_version:'v1',caption:'원문\n\n내용',images:[{...asset,order:1}]}]});await req('/api/posts/p',{expected_revision:1,patch:{source:{url:'https://example.invalid/source',verified:true},safety:{fact:'PASS',rights:'PASS',privacy:'PASS',defamation:'PASS',platform_policy:'PASS'},review:{output_version:'v1',score:8,decision:'approved',note:'테스트 사용자 직접 확인'}}});await req('/api/approve',{post_id:'p',expected_revision:2});const job=(await req('/api/queue',{post_id:'p',expected_revision:2})).state.jobs[0];const result=await req('/api/dry-run',{job_id:job.id});assert.equal(result.state.jobs[0].state,'dry_run_complete');assert.equal(result.state.dry_runs.length,1);assert.equal(result.state.publications.length,0);}finally{await app.close();}app=await createStudioServer({root:r,port:0});try{const s=await req('/api/state');assert.equal(s.state.dry_runs[0].externalCalls,0);assert.equal(s.state.publications.length,0);}finally{await app.close();}});
await check('production bridge preserves canonical IDs/versions/order without writing originals',async()=>{const base=await temporary(),{material,row,planFile,imageFile,statusFile}=await fixtureProduction(base),assets=new LocalAssets(path.join(base,'vault')),input=new ProductionInput(material,assets);const original=await Promise.all([statusFile,planFile,imageFile].map(x=>fs.readFile(x)));const canonical=createRequire(import.meta.url)('../../desktop/post-review-store.cjs').version;assert.equal(productionVersion(row),canonical(row));const catalog=await input.catalog();assert.equal(catalog.entries[0].pages,1);const b=await input.bundle([{id:row.id,output_version:productionVersion(row)}]);assert.equal(b.posts[0].caption,'[ 실제 제작 문안 ]\n\n원문에 따른 내용이다.  ');assert.equal(b.posts[0].source.verified,false);assert.equal(b.posts[0].images[0].asset_id,row.images[0].sha256);for(let i=0;i<original.length;i++)assert.deepEqual(await fs.readFile([statusFile,planFile,imageFile][i]),original[i]);await fs.writeFile(planFile,JSON.stringify({pages:[{body:'자동으로 기사화하지 않는 제작 본문'}]}));assert.equal((await input.bundle([{id:row.id,output_version:productionVersion(row)}])).posts[0].caption,'');});
await check('production bridge refuses changed hashes, stale versions, traversal and symlink escape',async()=>{const base=await temporary(),{material,row,statusFile,imageFile}=await fixtureProduction(base),input=new ProductionInput(material,new LocalAssets(path.join(base,'vault')));await assert.rejects(input.bundle([{id:row.id,output_version:'outdated'}]),/production_version_changed/);const original=await fs.readFile(imageFile);await fs.writeFile(imageFile,Buffer.from('tampered'));await assert.rejects(input.bundle([{id:row.id,output_version:productionVersion(row)}]),/production_image_changed/);await fs.writeFile(imageFile,original);await fs.writeFile(statusFile,JSON.stringify({entries:[{...row,outputFolder:'../outside'}]}));await assert.rejects(input.bundle([{id:row.id,output_version:productionVersion(row)}]),/production_path_invalid/);await fs.writeFile(statusFile,JSON.stringify({entries:[row]}));const outside=path.join(base,'outside.png');await fs.writeFile(outside,original);await fs.rm(imageFile);await fs.symlink(outside,imageFile);await assert.rejects(input.bundle([{id:row.id,output_version:productionVersion(row)}]),/production_path_invalid/);});
await check('production HTTP reimport preserves edited caption and changed version does not autoqueue',async()=>{const base=await temporary(),{material,row,statusFile}=await fixtureProduction(base),app=await createStudioServer({root:path.join(base,'studio'),port:0,materialRoot:material});const req=async(route,body)=>{const r=await fetch(app.url+route,{method:body?'POST':'GET',headers:body?{'content-type':'application/json','x-studio-local':'1'}:{},body:body?JSON.stringify(body):undefined});const result=await r.json();assert.equal(r.status,200,JSON.stringify(result));return result;};try{assert.equal((await req('/api/production')).available,true);const selection=[{id:row.id,output_version:productionVersion(row)}];await req('/api/production/import',{selection});await req('/api/posts/'+row.id,{expected_revision:1,patch:{caption:'[ 직접 편집한 글 ]\n\n보존해야 한다.'}});await req('/api/queue',{post_id:row.id,expected_revision:2});let result=await req('/api/production/import',{selection});assert.equal(result.state.posts[0].caption,'[ 직접 편집한 글 ]\n\n보존해야 한다.');const changed={...row,outputSha256:'new-output'};await fs.writeFile(statusFile,JSON.stringify({entries:[changed]}));result=await req('/api/production/import',{selection:[{id:row.id,output_version:productionVersion(changed)}]});assert.equal(result.state.jobs.length,1);assert.equal(result.state.jobs[0].stale,true);assert.equal(result.state.posts[0].review,null);assert.equal(result.state.posts[0].approval,null);assert.equal(result.state.archived_posts[0].caption,'[ 직접 편집한 글 ]\n\n보존해야 한다.');}finally{await app.close();}});
await check('unresolved backups survive empty actions in a different tab and a reopened page',async()=>{const map=new Map(),storage={get length(){return map.size;},key:i=>[...map.keys()][i]??null,getItem:k=>map.get(k)??null,setItem:(k,v)=>map.set(k,v),removeItem:k=>map.delete(k)};const a=new DraftBackups(storage,'tab-a'),records={p:{expected_revision:1,patch:{caption:'미저장\n\n문안  '}}};a.persist(records);const b=new DraftBackups(storage,'tab-b');b.persist({});assert.deepEqual(b.list()[0].records,records);const reopened=new DraftBackups(storage,'reopened');reopened.persist({});assert.deepEqual(reopened.list()[0].records,records);assert.ok(storage.getItem(BACKUP_PREFIX+'tab-a'));});
await check('recovery acknowledgement never removes a newer snapshot written by its owner',async()=>{const map=new Map(),storage={get length(){return map.size;},key:i=>[...map.keys()][i]??null,getItem:k=>map.get(k)??null,setItem:(k,v)=>map.set(k,v),removeItem:k=>map.delete(k)},a=new DraftBackups(storage,'a'),b=new DraftBackups(storage,'b');a.persist({p:{expected_revision:1,patch:{caption:'처음'}}});const entry=b.list()[0];a.persist({p:{expected_revision:1,patch:{caption:'더 새 문안'}}});b.acknowledge(entry);assert.equal(b.list()[0].records.p.patch.caption,'더 새 문안');a.persist({});assert.equal(b.list().length,0);});
await check('crash during owner preparation and empty legacy lock do not block restart',async()=>{const r=await temporary();await fs.mkdir(path.join(r,'.state-candidate-abandoned'));await fs.writeFile(path.join(r,'.state-candidate-abandoned','owner.partial.json'),'{partial');await fs.mkdir(path.join(r,'.state-lock'));const store=new StateStore(r);await store.mutate(s=>domain.importBundle(s,{bundle_id:'b',posts:[{post_id:'p',output_version:'v1'}]}));assert.equal((await store.read()).posts.length,1);await assert.rejects(fs.access(path.join(r,'.state-lock')),{code:'ENOENT'});});
await check('simultaneous stale-owner reclaimers preserve one successful compare-and-swap',async()=>{for(let i=0;i<20;i++){const r=await temporary(),a=new StateStore(r),b=new StateStore(r);await a.mutate(s=>domain.importBundle(s,{bundle_id:'b',posts:[{post_id:'p',output_version:'v1'}]}));await fs.mkdir(path.join(r,'.state-lock'));await fs.writeFile(path.join(r,'.state-lock','owner.11111111-1111-4111-8111-111111111111.json'),JSON.stringify({pid:2147483647}));const results=await Promise.allSettled([a.mutate(s=>domain.editPost(s,'p',{caption:'A'},1)),b.mutate(s=>domain.editPost(s,'p',{caption:'B'},1))]);assert.equal(results.filter(x=>x.status==='fulfilled').length,1);assert.match(results.find(x=>x.status==='rejected').reason.message,/revision_conflict/);assert.equal((await a.read()).posts[0].revision,2);}});
await check('releasing an observed old owner cannot delete a fresh owner',async()=>{const r=await temporary(),store=new StateStore(r),lease=await store.acquire();await store.release({ownerFile:'owner.00000000-0000-4000-8000-000000000000.json'});const files=await fs.readdir(path.join(r,'.state-lock'));assert.deepEqual(files,[lease.ownerFile]);await store.release(lease);await assert.rejects(fs.access(path.join(r,'.state-lock')),{code:'ENOENT'});});
await check('matched production quality is read-only metadata and never grants publication review',async()=>{const base=await temporary(),{material,row,statusFile}=await fixtureProduction(base),qualityFolder=path.join(material,'07_사용자 평가');await fs.mkdir(qualityFolder);const qualityFile=path.join(qualityFolder,'평가 기록.json');const quality={schemaVersion:1,evaluations:[{id:row.id,outputVersion:productionVersion(row),score:9,note:'기존 제작 평가 메모',updatedAt:'2026-10-09T12:00:00Z'},{id:row.id,outputVersion:'older-version',score:7,note:'이전 버전',updatedAt:'2026-10-08T12:00:00Z'}]};await fs.writeFile(qualityFile,JSON.stringify(quality));const original=await fs.readFile(qualityFile),app=await createStudioServer({root:path.join(base,'studio'),port:0,materialRoot:material});const req=async(route,body)=>{const r=await fetch(app.url+route,{method:body?'POST':'GET',headers:body?{'content-type':'application/json','x-studio-local':'1'}:{},body:body?JSON.stringify(body):undefined});const result=await r.json();assert.equal(r.status,200,JSON.stringify(result));return result;};try{const selection=[{id:row.id,output_version:productionVersion(row)}];let result=await req('/api/production/import',{selection});assert.equal(result.state.posts[0].production_feedback.current.score,9);assert.equal(result.state.posts[0].review,null);assert.equal(result.state.posts[0].approval,null);assert.deepEqual(await fs.readFile(qualityFile),original);await req('/api/posts/'+row.id,{expected_revision:1,patch:{caption:'[ 편집 후 문안 ]\n\n보존'}});quality.evaluations[0].score=8;await fs.writeFile(qualityFile,JSON.stringify(quality));result=await req('/api/production/import',{selection});assert.equal(result.state.posts[0].production_feedback.current.score,8);assert.equal(result.state.posts[0].caption,'[ 편집 후 문안 ]\n\n보존');assert.equal(result.state.posts[0].revision,2);assert.equal(result.state.posts[0].publication_approval,null);const changed={...row,outputSha256:'new-version'};await fs.writeFile(statusFile,JSON.stringify({entries:[changed]}));result=await req('/api/production/import',{selection:[{id:row.id,output_version:productionVersion(changed)}]});assert.equal(result.state.posts[0].production_feedback.current,null);assert.equal(result.state.posts[0].production_feedback.previous.score,8);assert.equal(result.state.posts[0].review,null);}finally{await app.close();}});
await check('full production sync batches 45 posts, is idempotent and preserves local edits after restart/version changes',async()=>{
 const base=await temporary(),f=await fixtureProduction(base),rows=Array.from({length:45},(_,i)=>({...f.row,id:'bulk-'+i,reviewRound:'current-review-round'}));
 await fs.writeFile(f.statusFile,JSON.stringify({entries:rows}));const original=await fs.readFile(f.imageFile);
 let app=await createStudioServer({root:path.join(base,'studio'),port:0,materialRoot:f.material});
 const req=async(route,body)=>{const r=await fetch(app.url+route,{method:body?'POST':'GET',headers:body?{'content-type':'application/json','x-studio-local':'1'}:{},body:body?JSON.stringify(body):undefined});const result=await r.json();assert.equal(r.status,200,JSON.stringify(result));return result;};
 try{
  let result=await req('/api/production/sync',{});assert.equal(result.synced,45);assert.equal(result.state.posts.length,45);assert.equal(result.state.jobs.length,0);
  const version=result.state.posts[0].output_version;
  await req('/api/posts/bulk-0',{expected_revision:1,patch:{caption:'사용자 글\\n\\n끝 공백  ',targets:['threads'],timing:{mode:'planned',local:'2026-10-12T18:00',offset_minutes:-540}}});
  await req('/api/queue',{post_id:'bulk-0',expected_revision:2});
  result=await req('/api/production/sync',{});const unchanged=result.state.revision;
  assert.equal(result.state.posts[0].caption,'사용자 글\\n\\n끝 공백  ');assert.equal((await req('/api/production/import',{selection:rows.map(r=>({id:r.id,output_version:version}))})).state.revision,unchanged);
  await app.close();app=await createStudioServer({root:path.join(base,'studio'),port:0,materialRoot:f.material});result=await req('/api/production/sync',{});
  assert.equal(result.state.posts.length,45);assert.deepEqual(result.state.posts[0].targets,['threads']);assert.equal(result.state.posts[0].timing.due_at,'2026-10-12T09:00:00.000Z');
  rows[0]={...rows[0],reviewRound:'new-review-round'};await fs.writeFile(f.statusFile,JSON.stringify({entries:rows}));
  result=await req('/api/production/sync',{});const p=result.state.posts[0];
  assert.notEqual(p.output_version,version);assert.equal(p.output_version,productionVersion(rows[0]));assert.equal(p.caption,'사용자 글\\n\\n끝 공백  ');assert.deepEqual(p.targets,['threads']);assert.equal(p.timing.due_at,'2026-10-12T09:00:00.000Z');assert.equal(p.review,null);assert.equal(p.approval,null);assert.equal(p.publication_approval,null);
  assert.equal(result.state.jobs.length,1);assert.equal(result.state.jobs[0].stale,true);assert.equal(result.state.publications.length,0);assert.deepEqual(await fs.readFile(f.imageFile),original);
 }finally{await app.close();}
});
await check('same-version legacy title refresh keeps edited writing, user URL and gates stale approval',async()=>{
 let s=domain.importBundle(domain.createState(),{bundle_id:'b',posts:[{post_id:'legacy',output_version:'v',caption:'내 문안',source:{label:'[ YTN ] 제목',url:'https://example.invalid/producer'}}]});
 s.posts[0].source={label:'[ YTN ] 제목',url:'https://example.invalid/user-checked',verified:true};
 s.posts[0].approval={scope:'dry-run',basis:domain.contentBasis(s.posts[0])};s=domain.queuePost(s,'legacy',1);
 const r=domain.syncProductionBundle(s,{posts:[{post_id:'legacy',output_version:'v',source:{label:'제목',display_title:'제목',caption_input_title:'제목',original_title:'[ YTN ] 제목'}}]});
 assert.equal(r.posts[0].caption,'내 문안');assert.equal(r.posts[0].source.url,'https://example.invalid/user-checked');assert.equal(r.posts[0].source.verified,true);assert.equal(r.posts[0].source.original_title,'[ YTN ] 제목');assert.equal(r.posts[0].source.label,'제목');assert.equal(r.posts[0].approval,null);assert.equal(r.jobs[0].stale,true);
 const again=domain.syncProductionBundle(r,{posts:[{post_id:'legacy',output_version:'v',source:{label:'제목',display_title:'제목',caption_input_title:'제목',original_title:'[ YTN ] 제목'}}]});assert.equal(again.revision,r.revision);
});
console.log('Upload Studio: '+count+' checks passed. External platform calls: 0.');
}finally {for(const r of roots)await fs.rm(r,{recursive:true,force:true});}
