import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import * as domain from '../domain.mjs';
import {runDomainSuite} from './domain-suite.mjs';
import {StateStore} from '../store.mjs';
import {offlinePlan} from '../adapter.mjs';
import {createStudioServer} from '../server.mjs';
import {PublicationJournal} from '../vendor/publication-journal.mjs';
const cases=await runDomainSuite(domain,assert);for(const c of cases)assert.ok(c.ok,c.name+': '+(c.error||''));console.log('domain: '+cases.length+' passed');
const roots=[];const temporary=async()=>{const r=await fs.mkdtemp(path.join(os.tmpdir(),'upload-studio-test-'));roots.push(r);return r;};
let count=cases.length;
async function check(name,fn){await fn();count++;console.log('PASS '+name);}
try {
await check('disk save preserves long text on a fresh store instance',async()=>{const r=await temporary(),store=new StateStore(r);await store.mutate(s=>domain.importBundle(s,{bundle_id:'b',posts:[{post_id:'p1',output_version:'v1',caption:'첫줄\n\n끝  '.repeat(500)}]}));const after=await new StateStore(r).read();assert.equal(after.posts[0].caption,'첫줄\n\n끝  '.repeat(500));});
await check('two store instances serialize competing edits without losing state',async()=>{const r=await temporary(),a=new StateStore(r),b=new StateStore(r);await a.mutate(s=>domain.importBundle(s,{bundle_id:'b',posts:[{post_id:'p',output_version:'v1'}]}));const res=await Promise.allSettled([a.mutate(s=>domain.editPost(s,'p',{caption:'A'},1)),b.mutate(s=>domain.editPost(s,'p',{caption:'B'},1))]);assert.equal(res.filter(x=>x.status==='fulfilled').length,1);assert.match(res.find(x=>x.status==='rejected').reason.message,/revision_conflict/);assert.equal((await a.read()).posts[0].revision,2);});
await check('corrupt state is blocked while the previous backup remains recoverable',async()=>{const r=await temporary(),a=new StateStore(r);await a.mutate(s=>domain.importBundle(s,{bundle_id:'b',posts:[{post_id:'p',output_version:'v1',caption:'保존'}]}));await a.mutate(s=>domain.editPost(s,'p',{caption:'새로운 글'},1));await fs.writeFile(path.join(r,'state.json'),'{bad');await assert.rejects(a.read(),/state_corrupt/);const b=await a.restoreBackup();assert.equal(b.posts[0].caption,'保존');assert.ok((await fs.readdir(r)).some(x=>x.startsWith('state.corrupt.')));});
await check('official planners run with an empty worker environment and no network',async()=>{const p={post_id:'p',output_version:'v1',caption:'줄1\n\n줄2',tags:'#태그',targets:['instagram','threads'],images:[{asset_id:'a'.repeat(64),order:1,mime:'image/jpeg'},{asset_id:'b'.repeat(64),order:2,mime:'image/jpeg'}]};const plans=await offlinePlan(p);assert.equal(plans.length,2);for(const x of plans){assert.equal(x.externalCalls,0);assert.equal(x.dryRun,true);assert.equal(x.capability.configured,false);assert.equal(x.localOnly,true);assert.match(x.mediaUrls[0],/example.invalid\/local\/a/);}assert.equal(plans[0].steps.at(-2).params.caption,'줄1\n\n줄2\n\n#태그');assert.equal(plans[1].mediaCount,2);});
await check('existing publication journal replays a local dry-run without executing again',async()=>{const r=await temporary(),j=new PublicationJournal(r);let calls=0;const args={provider:'offline-preview',candidateId:'p',approvalBasis:'v1',accountKey:'unconnected-instagram',payload:{caption:'원문'},publish:async()=>{calls++;return {dryRun:true,externalCalls:0};}};await j.execute(args);const replay=await new PublicationJournal(r).execute(args);assert.equal(replay.replayed,true);assert.equal(calls,1);await assert.rejects(j.execute({...args,payload:{caption:'바뀜'}}),/같은 승인/);});
await check('ambiguous journal error prevents replay after restart',async()=>{const r=await temporary(),args={provider:'offline-preview',candidateId:'p',approvalBasis:'v1',accountKey:'unconnected-threads',payload:{caption:'원문'},publish:async()=>{throw Error('fixture-failure');}};await assert.rejects(new PublicationJournal(r).execute(args),/fixture-failure/);await assert.rejects(new PublicationJournal(r).execute(args),/중복 게시/);});
await check('loopback server saves/restarts and refuses live, foreign origin and secret fields',async()=>{const r=await temporary();let app=await createStudioServer({root:r,port:0});const request=(route,body,extra={})=>fetch(app.url+route,{method:body===undefined?'GET':'POST',headers:body===undefined?{}:{'content-type':'application/json','x-studio-local':'1',...extra},body:body===undefined?undefined:JSON.stringify(body)});
try{let response=await request('/api/bundles',{bundle_id:'b',posts:[{post_id:'p',output_version:'v1',caption:'긴 글\n\n마지막  '.repeat(300)}]});assert.equal(response.status,200);response=await request('/api/posts/p',{expected_revision:1,patch:{targets:['threads']}});assert.equal(response.status,200);assert.equal((await response.json()).state.posts[0].caption,'긴 글\n\n마지막  '.repeat(300));assert.equal((await request('/api/publish',{})).status,405);assert.equal((await request('/api/schedule',{})).status,405);assert.equal((await request('/api/posts/p',{expected_revision:2,patch:{caption:'공격'}},{Origin:'https://example.invalid'})).status,403);assert.equal((await request('/api/bundles',{bundle_id:'bad',access_token:'DO_NOT_STORE',posts:[]})).status,400);assert.equal((await request('/api/queue',{post_id:'p',expected_revision:2})).status,200);
}finally{await app.close();}app=await createStudioServer({root:r,port:0});try{const s=await request('/api/state').then(x=>x.json());assert.deepEqual(s.state.posts[0].targets,['threads']);assert.equal(s.state.jobs.length,1);assert.equal(s.state.publications.length,0);}finally{await app.close();}});
await check('local image asset bytes are retrieved only from the local vault',async()=>{const r=await temporary(),app=await createStudioServer({root:r,port:0});try{const bytes=Buffer.from([255,216,255,224,1,2,255,217]);const response=await fetch(app.url+'/api/assets',{method:'POST',headers:{'content-type':'application/json','x-studio-local':'1'},body:JSON.stringify({name:'fixture.jpg',mime:'image/jpeg',base64:bytes.toString('base64')})});assert.equal(response.status,200);const asset=(await response.json()).asset;const read=await fetch(app.url+'/assets/'+asset.asset_id);assert.equal(read.headers.get('content-type'),'image/jpeg');assert.deepEqual(Buffer.from(await read.arrayBuffer()),bytes);assert.equal((await fetch(app.url+'/assets/../../state.json')).status,404);}finally{await app.close();}});
await check('HTTP dry-run records only dry-run history and survives restart',async()=>{const r=await temporary();let app=await createStudioServer({root:r,port:0});const req=(route,body)=>fetch(app.url+route,{method:body?'POST':'GET',headers:body?{'content-type':'application/json','x-studio-local':'1'}:{},body:body?JSON.stringify(body):undefined}).then(async x=>{const result=await x.json();assert.equal(x.status,200,JSON.stringify(result));return result;});
try{const asset=(await req('/api/assets',{name:'local.jpg',mime:'image/jpeg',base64:Buffer.from([255,216,255,224,1,2,255,217]).toString('base64')})).asset;await req('/api/bundles',{bundle_id:'b',posts:[{post_id:'p',output_version:'v1',caption:'원문\n\n내용',images:[{...asset,order:1}]}]});await req('/api/posts/p',{expected_revision:1,patch:{source:{url:'https://example.invalid/source',verified:true},safety:{fact:'PASS',rights:'PASS',privacy:'PASS',defamation:'PASS',platform_policy:'PASS'},review:{output_version:'v1',score:8,decision:'approved',note:'테스트 사용자 직접 확인'}}});await req('/api/approve',{post_id:'p',expected_revision:2});const job=(await req('/api/queue',{post_id:'p',expected_revision:2})).state.jobs[0];const result=await req('/api/dry-run',{job_id:job.id});assert.equal(result.state.jobs[0].state,'dry_run_complete');assert.equal(result.state.dry_runs.length,1);assert.equal(result.state.publications.length,0);}finally{await app.close();}app=await createStudioServer({root:r,port:0});try{const s=await req('/api/state');assert.equal(s.state.dry_runs[0].externalCalls,0);assert.equal(s.state.publications.length,0);}finally{await app.close();}});
console.log('Upload Studio: '+count+' checks passed. External platform calls: 0.');
}finally {for(const r of roots)await fs.rm(r,{recursive:true,force:true});}
