import cp from 'node:child_process';import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');const qa=path.join(root,'qa');fs.mkdirSync(qa,{recursive:true});
const base=process.argv[2];if(!/^http:\/\/127\.0\.0\.1:\d+$/.test(base))throw Error('Loopback fixture URL required');
const chrome=cp.spawn('C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe',['--headless=new','--remote-debugging-pipe','--no-first-run','--disable-gpu','--disable-background-networking','--disable-component-update','--disable-default-apps','--no-default-browser-check','--user-data-dir='+path.join(qa,'isolated-profile-'+Date.now())],{windowsHide:true,stdio:['ignore','ignore','pipe','pipe','pipe']});
let seq=0,buffer=Buffer.alloc(0);const waiting=new Map();
chrome.stdio[4].on('data',chunk=>{buffer=Buffer.concat([buffer,chunk]);for(let at;(at=buffer.indexOf(0))>=0;){const msg=JSON.parse(buffer.subarray(0,at).toString());buffer=buffer.subarray(at+1);const w=waiting.get(msg.id);if(w){waiting.delete(msg.id);msg.error?w.reject(Error(JSON.stringify(msg.error))):w.resolve(msg.result);}}});
function call(method,params={},sessionId){return new Promise((resolve,reject)=>{const id=++seq;waiting.set(id,{resolve,reject});chrome.stdio[3].write(JSON.stringify({id,method,params,...(sessionId?{sessionId}:{})})+'\0');setTimeout(()=>{if(waiting.has(id)){waiting.delete(id);reject(Error('CDP timeout '+method));}},10000).unref();});}
let session;const checks=[];
async function evaluate(expression){const r=await call('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true},session);if(r.exceptionDetails)throw Error(r.exceptionDetails.text+' '+JSON.stringify(r.exceptionDetails.exception));return r.result.value;}
async function until(expression){const end=Date.now()+10000;while(Date.now()<end){if(await evaluate(expression))return;await new Promise(r=>setTimeout(r,100));}throw Error('Condition timed out: '+expression);}
async function navigate(url){await call('Page.navigate',{url},session);await until("document.getElementById('pending')&&document.getElementById('aboutTab').onclick!==null");}
async function shot(name){const r=await call('Page.captureScreenshot',{format:'png',captureBeyondViewport:false},session);fs.writeFileSync(path.join(qa,name),Buffer.from(r.data,'base64'));}
try{
 const target=await call('Target.createTarget',{url:'about:blank'});session=(await call('Target.attachToTarget',{targetId:target.targetId,flatten:true})).sessionId;await call('Page.enable',{},session);await call('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true},session);
 await navigate(base+'/');assert.match(await evaluate("document.getElementById('connection').textContent"),/차단/);assert.equal(await evaluate("document.getElementById('empty').hidden"),false);await shot('390-empty.png');checks.push('shipped empty UI truthfully blocks Internet synchronization');
 await call('Page.navigate',{url:base+'/seed'},session);await until("location.pathname==='/'&&document.querySelectorAll('.post').length===1");
 await evaluate("document.querySelector('.post').click()");await until("document.getElementById('saveReview')!==null");assert.equal(await evaluate("document.querySelectorAll('.score-grid button').length"),10);assert.equal(await evaluate("document.documentElement.scrollWidth<=innerWidth"),true);await shot('390-review.png');await evaluate("document.getElementById('saveReview').scrollIntoView({block:'end'})");await shot('390-review-controls.png');
 await evaluate("document.querySelector('[aria-label=\"9점\"]').click();document.getElementById('memo').value='화면검증 fixture 한글 메모';document.querySelector('[data-criterion=readable]').checked=true;document.querySelector('[data-decision=publish_approved]').click()");assert.equal(await evaluate("document.getElementById('approve').open"),true);await evaluate("document.getElementById('approveNo').click();document.querySelector('[data-decision=held]').click();document.getElementById('saveReview').click()");await until("document.getElementById('pending').textContent==='1'");checks.push('390px review images/ten score buttons/Korean memo/checks/explicit approval dialog');
 await navigate(base+'/');await evaluate("document.querySelector('.post').click()");await until("document.getElementById('memo')!==null");assert.equal(await evaluate("document.getElementById('memo').value"),'화면검증 fixture 한글 메모');assert.equal(await evaluate("document.querySelector('.score-grid button.active').textContent"),'9');assert.equal(await evaluate("document.querySelector('.decisions .active').dataset.decision"),'held');checks.push('IndexedDB survives reload with score/note/check/held state');
 await evaluate(`(async()=>{const m=await import('/core.js'),r=indexedDB.open('threads-mobile-review-v1',1);await new Promise(done=>r.onsuccess=done);const db=r.result;const s=await new Promise(done=>{const q=db.transaction('state').objectStore('state').get('current');q.onsuccess=()=>done(q.result)});const manifest=structuredClone(s.manifest);manifest.entries[0].revision=4;manifest.entries[0].review={score:2,note:'서버 fixture 메모',checks:{},decision:'needs_revision'};const next=m.applyManifest(s,manifest);await new Promise((done,reject)=>{const t=db.transaction('state','readwrite');t.objectStore('state').put(next,'current');t.oncomplete=done;t.onerror=reject});})()`);
 await navigate(base+'/');await evaluate("document.getElementById('queueTab').click()");await until("document.querySelector('#operations h3').textContent.includes('충돌')");await shot('390-conflict.png');await evaluate("Array.from(document.querySelectorAll('#operations button')).find(b=>b.textContent==='내 기록 다시 보내기').click()");await until("document.getElementById('operations').textContent.includes('사용자 선택으로 처리')");checks.push('real queue screen exposes both records and explicit conflict rebase');
 await evaluate(`(async()=>{const m=await import('/core.js'),r=indexedDB.open('threads-mobile-review-v1',1);await new Promise(done=>r.onsuccess=done);const db=r.result;const s=await new Promise(done=>{const q=db.transaction('state').objectStore('state').get('current');q.onsuccess=()=>done(q.result)});if(s.outbox.at(-1).baseRevision!==4)throw Error('wrong rebase');const manifest=structuredClone(s.manifest);manifest.entries[0].outputVersion='c'.repeat(64);manifest.entries[0].revision=0;delete manifest.entries[0].review;const next=m.applyManifest(s,manifest);await new Promise((done,reject)=>{const t=db.transaction('state','readwrite');t.objectStore('state').put(next,'current');t.oncomplete=done;t.onerror=reject});})()`);
 await navigate(base+'/');await evaluate("document.querySelector('.post').click()");await until("document.getElementById('memo')!==null");assert.equal(await evaluate("document.getElementById('memo').value"),'');assert.equal(await evaluate("document.querySelector('.score-grid button.active')===null"),true);checks.push('new outputVersion starts blank in actual UI, old queue marked stale');
 await call('Emulation.setDeviceMetricsOverride',{width:800,height:1000,deviceScaleFactor:1,mobile:false},session);assert.equal(await evaluate("document.documentElement.scrollWidth<=innerWidth"),true);await shot('800-review.png');checks.push('390px/800px no horizontal overflow');
 await call('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true},session);await evaluate("document.getElementById('aboutTab').click()");assert.equal(await evaluate("document.getElementById('connectGithub')!==null"),true);assert.match(await evaluate("document.getElementById('about').textContent"),/실제 연결되지/);await evaluate("document.getElementById('connectGithub').click()");assert.match(await evaluate("document.getElementById('message').textContent"),/아직 승인/);assert.equal(await evaluate("document.documentElement.scrollWidth<=innerWidth"),true);await shot('390-connection-ready.png');checks.push('0.1.2 connection preparation explicitly disconnected; browser has no native login');
 fs.writeFileSync(path.join(qa,'browser-result.json'),JSON.stringify({pass:true,apkVersion:'0.1.2',fixtureOnly:true,actualUserDataTouched:false,engine:'installed Chrome headless over private pipe',androidDevice:false,nativeScreenExecuted:false,onlineSync:false,checks},null,2));console.log(JSON.stringify({pass:true,checks},null,2));
}catch(e){fs.writeFileSync(path.join(qa,'browser-error.txt'),e.stack);throw e;}finally{try{await call('Browser.close');}catch{chrome.kill();}}
