import cp from 'node:child_process';import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),qa=path.join(root,'qa');fs.mkdirSync(qa,{recursive:true});const base=process.argv[2];if(!/^http:\/\/127\.0\.0\.1:\d+$/.test(base))throw Error('Loopback fixture URL required');
const chrome=cp.spawn('C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe',['--headless=new','--remote-debugging-pipe','--no-first-run','--disable-gpu','--disable-background-networking','--disable-component-update','--disable-default-apps','--no-default-browser-check','--user-data-dir='+path.join(qa,'isolated-profile-'+Date.now())],{windowsHide:true,stdio:['ignore','ignore','pipe','pipe','pipe']});
let seq=0,buffer=Buffer.alloc(0),session;const waiting=new Map(),checks=[];chrome.stderr.on('data',()=>{});chrome.stdio[4].on('data',chunk=>{buffer=Buffer.concat([buffer,chunk]);for(let at;(at=buffer.indexOf(0))>=0;){const msg=JSON.parse(buffer.subarray(0,at));buffer=buffer.subarray(at+1);const w=waiting.get(msg.id);if(w){waiting.delete(msg.id);msg.error?w.reject(Error(JSON.stringify(msg.error))):w.resolve(msg.result);}}});
function call(method,params={},sid){return new Promise((resolve,reject)=>{const id=++seq;waiting.set(id,{resolve,reject});chrome.stdio[3].write(JSON.stringify({id,method,params,...(sid?{sessionId:sid}:{})})+'\0');setTimeout(()=>{if(waiting.delete(id))reject(Error('CDP timeout '+method));},10000).unref();});}
async function evaluate(expression){const r=await call('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true},session);if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value;}
async function until(expression){const end=Date.now()+10000;while(Date.now()<end){if(await evaluate(expression))return;await new Promise(r=>setTimeout(r,50));}throw Error('Condition timed out: '+expression);}
async function navigate(url){await call('Page.navigate',{url},session);await until("document.getElementById('aboutTab')&&document.getElementById('aboutTab').onclick!==null");}
async function shot(name){const r=await call('Page.captureScreenshot',{format:'png',captureBeyondViewport:false},session);fs.writeFileSync(path.join(qa,name),Buffer.from(r.data,'base64'));}
async function mutate(change){await evaluate(`(async()=>{const core=await import('/core.js'),r=indexedDB.open('threads-mobile-review-v1',1);await new Promise((done,fail)=>{r.onsuccess=done;r.onerror=fail});const db=r.result;try{const s=await new Promise((done,fail)=>{const q=db.transaction('state').objectStore('state').get('current');q.onsuccess=()=>done(q.result);q.onerror=fail});${change};await new Promise((done,fail)=>{const t=db.transaction('state','readwrite');t.objectStore('state').put(s,'current');t.oncomplete=done;t.onerror=fail})}finally{db.close()}})()`);}
try{
 const t=await call('Target.createTarget',{url:'about:blank'});session=(await call('Target.attachToTarget',{targetId:t.targetId,flatten:true})).sessionId;await call('Page.enable',{},session);await call('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true},session);await navigate(base+'/');assert.equal(await evaluate("document.getElementById('empty').hidden"),false);assert.equal(await evaluate("document.getElementById('connectGithub').hidden"),true);assert.equal(await evaluate("document.getElementById('filters').hidden"),true);assert.equal(await evaluate("document.getElementById('connection').hidden"),true);assert.equal(await evaluate("document.querySelector('#about details').open"),false);await shot('390-empty.png');await call('Emulation.setEmulatedMedia',{features:[{name:'prefers-color-scheme',value:'dark'}]},session);await shot('390-empty-dark.png');await call('Emulation.setEmulatedMedia',{features:[{name:'prefers-color-scheme',value:'light'}]},session);checks.push('compact disconnected onboarding; no fake login or empty search; collapsed technical information');
 await call('Page.navigate',{url:base+'/seed'},session);await until("location.pathname==='/'&&document.querySelectorAll('.post').length===1");await evaluate("document.querySelector('.post').click()");assert.equal(await evaluate("document.querySelectorAll('.score-grid button').length"),10);await until("document.querySelector('.pages img')!==null");assert.equal(await evaluate("document.documentElement.scrollWidth<=innerWidth"),true);await shot('390-review.png');await evaluate("document.getElementById('saveReview').scrollIntoView({block:'end'})");await shot('390-review-controls.png');
 await evaluate("document.querySelector('.score-grid button:nth-child(9)').click();document.getElementById('memo').value='합성 화면 검증 메모';document.querySelector('[data-criterion=readable]').checked=true;document.querySelector('[data-decision=publish_approved]').click()");assert.equal(await evaluate("document.getElementById('approve').open"),true);await evaluate("document.getElementById('approveNo').click();document.querySelector('[data-decision=held]').click();document.getElementById('saveReview').click()");await until("document.getElementById('pending').textContent==='1'");checks.push('exact-hash cached PNG; ten scores; Korean memo; criteria; explicit approval dialog');
 await navigate(base+'/');await evaluate("document.querySelector('.post').click()");assert.equal(await evaluate("document.getElementById('memo').value"),'합성 화면 검증 메모');assert.equal(await evaluate("document.querySelector('.score-grid button.active').textContent"),'9');assert.equal(await evaluate("document.querySelector('.decisions .active').dataset.decision"),'held');checks.push('offline IndexedDB review survives reload');
 await mutate("const manifest=structuredClone(s.manifest);manifest.entries[0].revision=4;manifest.entries[0].review={score:2,note:'합성 서버 평가',checks:{},decision:'needs_revision'};Object.assign(s,core.applyManifest(s,manifest))");await navigate(base+'/');await evaluate("document.getElementById('queueTab').click()");assert.ok(await evaluate("document.getElementById('operations').textContent.includes('합성 서버 평가')"));await shot('390-conflict.png');await evaluate("Array.from(document.querySelectorAll('#operations button')).find(b=>b.textContent==='내 평가 다시 보내기').click()");await until("document.getElementById('operations').textContent.includes('충돌 처리 완료')");checks.push('conflict displays both reviews and explicit rebase');
 await mutate("if(s.outbox.at(-1).baseRevision!==4)throw Error('wrong rebase');const manifest=structuredClone(s.manifest);manifest.entries[0].outputVersion='c'.repeat(64);manifest.entries[0].revision=0;delete manifest.entries[0].review;Object.assign(s,core.applyManifest(s,manifest))");await navigate(base+'/');await evaluate("document.querySelector('.post').click()");assert.equal(await evaluate("document.getElementById('memo').value"),'');assert.equal(await evaluate("document.querySelector('.score-grid button.active')===null"),true);checks.push('new output version starts blank; old queue retained stale');
 await mutate("s.outbox[0].status='confirmed'");await navigate(base+'/');await evaluate("document.getElementById('queueTab').click()");assert.ok(await evaluate("document.getElementById('operations').textContent.includes('서버 저장 확인')"));assert.equal(await evaluate("document.getElementById('operations').textContent.includes('PC 반영 확인')"),false);checks.push('server acknowledgement never claims PC canonical merge');
 await call('Emulation.setDeviceMetricsOverride',{width:800,height:1000,deviceScaleFactor:1,mobile:false},session);assert.equal(await evaluate("document.documentElement.scrollWidth<=innerWidth"),true);await shot('800-review.png');await evaluate("document.getElementById('aboutTab').click()");assert.equal(await evaluate("document.querySelector('#about details').open"),false);checks.push('390px/800px fit; settings disclosure stays closed');
 const result={pass:true,apkVersion:'0.1.4',fixtureOnly:true,actualUserDataTouched:false,engine:'installed Chrome headless over private pipe',androidDevice:false,nativeScreenExecuted:false,onlineSync:false,checks};fs.writeFileSync(path.join(qa,'browser-result.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));
}catch(error){fs.writeFileSync(path.join(qa,'browser-error.txt'),error.stack);throw error;}finally{try{await call('Browser.close');}catch{chrome.kill();}}
