import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import {createHash} from 'node:crypto';
import {version} from '../../../desktop/post-review-store.cjs';
const moduleUrl=new URL('../pc/exchange.mjs',import.meta.url);
const load=()=>import(moduleUrl);
const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aN5sAAAAASUVORK5CYII=','base64');
const sha=bytes=>createHash('sha256').update(bytes).digest('hex');
const criteria={version:'criteria-1',items:[{id:'readable',label:'Readable'}]};
const row=(extra={})=>({id:'synthetic-post',title:'Synthetic fixture',sourceFingerprint:'1'.repeat(64),outputSha256:'2'.repeat(64),ruleVersion:'rules-1',reviewRound:'fixture-round',outputFolder:'synthetic-output',images:[{name:'rendered/slide-001.png',sha256:sha(png)}],...extra});
const store=(r=row(),current=null)=>({readOnly:true,root:path.join(os.tmpdir(),'synthetic-materials'),list:async()=>({reviewRound:r.reviewRound,entries:[{id:r.id,title:r.title,outputVersion:version(r),hasOutput:true,current,topic:'life',topicLabel:'Life',category:'all',pageLabels:['Cover']}]}),image:async()=> 'data:image/png;base64,'+png.toString('base64'),save:()=>assert.fail('PC store must never be saved')});
async function fixture(t,options={}){const root=await fs.mkdtemp(path.join(os.tmpdir(),'pc-exchange-'));t.after(()=>fs.rm(root,{recursive:true,force:true}));const raw=await load(),r=options.row||row(),s=options.store||store(r);const exported=await raw.exportRelease({store:s,rows:[r],criteria,reviewRound:r.reviewRound,allowedOutputRoot:root,outputDirectory:path.join(root,'release'),...options});const trustedLocalSnapshot=JSON.parse(await fs.readFile(exported.snapshotFile,'utf8'));const api={...raw,prepareFeedbackImport:input=>raw.prepareFeedbackImport({trustedLocalSnapshot,...input})};return {root,api,r,s,...exported,trustedLocalSnapshot};}
const operation=(r,extra={})=>({operationId:'synthetic-operation',id:r.id,outputVersion:version(r),reviewRound:r.reviewRound,baseRevision:0,criteriaVersion:criteria.version,kind:'review',payload:{score:8,note:'Memo is separate',checks:{readable:true},decision:'held'},deviceId:'synthetic-device',createdAt:'2026-10-08T00:00:00.000Z',...extra});
function withOperation(api,state,op,result={operationId:op.operationId,status:'applied',revision:op.baseRevision+1}){const next=structuredClone(state);next.operations[op.operationId]={requestHash:api.requestHash(op),request:structuredClone(op),result};const e=next.manifest.entries[0];if(result.status==='applied'){e.review=structuredClone(op.payload);e.revision=result.revision;}return next;}

test('exports canonical versions and physically retained PNG Git blobs to a new namespace',async t=>{const {state,root,r}=await fixture(t);assert.equal(state.manifest.entries[0].outputVersion,version(r));assert.equal(state.manifest.entries[0].review,null);assert.equal(state.manifest.entries[0].revision,0);const image=state.manifest.entries[0].images[0],bytes=await fs.readFile(path.join(root,'release','mobile-review','assets',sha(png)+'.png'));assert.deepEqual(bytes,png);assert.equal(state.assets[image.url].blobSha,createHash('sha1').update(Buffer.concat([Buffer.from('blob '+png.length+'\0'),png])).digest('hex'));assert.deepEqual(JSON.parse(await fs.readFile(path.join(root,'release','mobile-review','state.json'),'utf8')),state);});
test('rejects overwrite and containment escape without touching source',async t=>{const {api,root,s,r}=await fixture(t);const input={store:s,rows:[r],criteria,reviewRound:r.reviewRound,allowedOutputRoot:root};await assert.rejects(api.exportRelease({...input,outputDirectory:path.join(root,'release')}),/exist/i);await assert.rejects(api.exportRelease({...input,outputDirectory:path.join(root,'..','escape')}),/namespace|root/i);await assert.rejects(api.exportRelease({...input,allowedOutputRoot:s.root,outputDirectory:path.join(s.root,'new')}),/source|material/i);});
test('rejects changed PNG hash, invalid PNG and unverified store/version/round',async t=>{const api=await load(),root=await fs.mkdtemp(path.join(os.tmpdir(),'pc-exchange-invalid-'));t.after(()=>fs.rm(root,{recursive:true,force:true}));const input={store:store(),rows:[row()],criteria,reviewRound:'fixture-round',allowedOutputRoot:root,outputDirectory:path.join(root,'release')},changed=row({images:[{name:'rendered/slide-001.png',sha256:'f'.repeat(64)}]});await assert.rejects(api.exportRelease({...input,rows:[changed],store:store(changed)}),/hash/i);await assert.rejects(api.exportRelease({...input,store:{...store(),image:async()=> 'data:image/png;base64,'+Buffer.from('not png').toString('base64')}}),/PNG|hash/i);await assert.rejects(api.exportRelease({...input,store:{...store(),readOnly:false}}),/read.only/i);await assert.rejects(api.exportRelease({...input,reviewRound:'wrong-round'}),/round/i);await assert.rejects(api.exportRelease({...input,store:{...store(),list:async()=>({reviewRound:'fixture-round',entries:[{id:row().id,outputVersion:'f'.repeat(64)}]})}}),/version/i);});
test('preserves history/operations/assets on a new release without copying scores',async t=>{const f=await fixture(t),op=operation(f.r),previous=withOperation(f.api,f.state,op);const r=row({reviewRound:'next-round',outputSha256:'3'.repeat(64)});const next=await f.api.exportRelease({store:store(r),rows:[r],criteria,reviewRound:r.reviewRound,previousState:previous,previousTrustedLocalSnapshot:f.trustedLocalSnapshot,previousAssetDirectory:path.join(f.root,'release','mobile-review','assets'),allowedOutputRoot:f.root,outputDirectory:path.join(f.root,'next')});assert.equal(next.state.manifest.entries[0].review,null);assert.equal(next.state.manifest.entries[0].revision,0);assert.deepEqual(next.state.operations,previous.operations);assert.equal(next.state.history[0].manifest.entries[0].review.score,8);assert.deepEqual(await fs.readFile(path.join(f.root,'next','mobile-review','assets',sha(png)+'.png')),png);});
test('imports canonical evaluation proposals and separate decisions with exact provenance',async t=>{const f=await fixture(t),op=operation(f.r),state=withOperation(f.api,f.state,op);const result=f.api.prepareFeedbackImport({state,rows:[f.r],criteria,reviewRound:f.r.reviewRound,sourceCommit:'a'.repeat(40)});assert.equal(result.evaluationProposals.length,1);assert.deepEqual(result.evaluationProposals[0].evaluation,{id:f.r.id,outputVersion:version(f.r),sourceFingerprint:f.r.sourceFingerprint,outputSha256:f.r.outputSha256,ruleVersion:f.r.ruleVersion,title:f.r.title,score:8,note:'Memo is separate',updatedAt:op.createdAt,reviewRound:f.r.reviewRound});assert.equal(result.evaluationProposals[0].provenance.requestHash,f.api.requestHash(op));assert.deepEqual(result.mobileDecisionRecords[0].checks,{readable:true});assert.equal(result.mobileDecisionRecords[0].decision,'held');assert.equal(Object.hasOwn(result.evaluationProposals[0].evaluation,'decision'),false);assert.equal(result.canonicalWritePerformed,false);});
test('preserves score null and memo without converting decision into a PC disposition',async t=>{const f=await fixture(t),op=operation(f.r,{payload:{score:null,note:'Only a memo',checks:{readable:false},decision:'publish_approved'}});const result=f.api.prepareFeedbackImport({state:withOperation(f.api,f.state,op),rows:[f.r],criteria,reviewRound:f.r.reviewRound});assert.equal(result.evaluationProposals[0].evaluation.score,null);assert.equal(result.evaluationProposals[0].evaluation.note,'Only a memo');assert.equal(result.mobileDecisionRecords[0].decision,'publish_approved');assert.equal(Object.hasOwn(result.mobileDecisionRecords[0],'disposition'),false);});
test('deduplicates identical receipts and rejects changed-content replay',async t=>{const f=await fixture(t),op=operation(f.r),state=withOperation(f.api,f.state,op);const first=f.api.prepareFeedbackImport({state,rows:[f.r],criteria,reviewRound:f.r.reviewRound});const second=f.api.prepareFeedbackImport({state,rows:[f.r],criteria,reviewRound:f.r.reviewRound,receipts:first.proposedReceipts});assert.equal(second.evaluationProposals.length,0);assert.equal(second.duplicates.length,1);const wrong=structuredClone(first.proposedReceipts);wrong[0].requestHash='f'.repeat(64);assert.throws(()=>f.api.prepareFeedbackImport({state,rows:[f.r],criteria,reviewRound:f.r.reviewRound,receipts:wrong}),/reused|replay/i);});
test('rejects ledger hash tampering and invalid score/check/result fields',async t=>{const f=await fixture(t),op=operation(f.r),state=withOperation(f.api,f.state,op),input={state,rows:[f.r],criteria,reviewRound:f.r.reviewRound};const bad=structuredClone(state);bad.operations[op.operationId].request.payload.note='tampered';assert.throws(()=>f.api.prepareFeedbackImport({...input,state:bad}),/hash/i);for(const payload of [{...op.payload,score:11},{...op.payload,checks:{unknown:true}},{...op.payload,checks:{readable:'yes'}}])assert.throws(()=>f.api.prepareFeedbackImport({...input,state:withOperation(f.api,state,{...op,payload})}));assert.throws(()=>f.api.prepareFeedbackImport({...input,state:withOperation(f.api,state,op,{operationId:op.operationId,status:'applied',revision:5})}),/revision/i);});
test('blocks missing request provenance while preserving legacy ledgers',async t=>{const f=await fixture(t),op=operation(f.r),state=withOperation(f.api,f.state,op);delete state.operations[op.operationId].request;const result=f.api.prepareFeedbackImport({state,rows:[f.r],criteria,reviewRound:f.r.reviewRound});assert.equal(result.evaluationProposals.length,0);assert.equal(result.blockers[0].reason,'missing_request_provenance');});
test('reports stale release/criteria and explicit conflicts without last-write-wins',async t=>{const f=await fixture(t),op=operation(f.r);let result=f.api.prepareFeedbackImport({state:withOperation(f.api,f.state,op),rows:[row({reviewRound:'next-round'})],criteria,reviewRound:'next-round'});assert.equal(result.stale.length,1);assert.equal(result.evaluationProposals.length,0);result=f.api.prepareFeedbackImport({state:withOperation(f.api,f.state,op),rows:[f.r],criteria:{...criteria,version:'criteria-2'},reviewRound:f.r.reviewRound});assert.equal(result.stale.length,1);result=f.api.prepareFeedbackImport({state:withOperation(f.api,f.state,op,{operationId:op.operationId,status:'conflict',revision:2,review:null}),rows:[f.r],criteria,reviewRound:f.r.reviewRound});assert.equal(result.conflicts.length,1);assert.equal(result.evaluationProposals.length,0);});
test('detects PC canonical changes since export and revision gaps',async t=>{const f=await fixture(t),op=operation(f.r),state=withOperation(f.api,f.state,op),input={state,rows:[f.r],criteria,reviewRound:f.r.reviewRound};const result=f.api.prepareFeedbackImport({...input,canonicalEvaluations:[{id:f.r.id,outputVersion:version(f.r),score:4,note:'PC edit'}]});assert.equal(result.conflicts[0].reason,'canonical_changed_since_export');assert.equal(result.evaluationProposals.length,0);const gap=operation(f.r,{baseRevision:2});const gapResult=f.api.prepareFeedbackImport({...input,state:withOperation(f.api,f.state,gap)});assert.equal(gapResult.conflicts[0].reason,'base_revision_mismatch');});
test('requires dedicated private repository metadata and never configures a live repository',async()=>{const api=await load();assert.deepEqual(api.dedicatedRepositoryMetadata({owner:'synthetic-owner',repo:'private-review-fixture',repositoryId:123,private:true,dedicatedReviewRepository:true,branch:'mobile-review/data',excludedRepositories:['owner/bridge']}),{owner:'synthetic-owner',repo:'private-review-fixture',repositoryId:123,private:true,dedicatedReviewRepository:true,branch:'mobile-review/data'});assert.throws(()=>api.dedicatedRepositoryMetadata({owner:'owner',repo:'bridge',repositoryId:123,private:true,dedicatedReviewRepository:true,branch:'mobile-review/data',excludedRepositories:['owner/bridge']}),/separate|excluded/i);assert.throws(()=>api.dedicatedRepositoryMetadata({owner:'owner',repo:'review',repositoryId:123,private:false,dedicatedReviewRepository:true,branch:'mobile-review/data'}),/private/i);});
test('same-release re-export preserves the initial PC baseline for unimported operations',async t=>{const f=await fixture(t),op=operation(f.r),previous=withOperation(f.api,f.state,op);const next=await f.api.exportRelease({store:f.s,rows:[f.r],criteria,reviewRound:f.r.reviewRound,previousState:previous,previousTrustedLocalSnapshot:f.trustedLocalSnapshot,previousAssetDirectory:f.assetDirectory,allowedOutputRoot:f.root,outputDirectory:path.join(f.root,'again')});assert.deepEqual(next.state.pcExport,f.state.pcExport);assert.equal(f.api.prepareFeedbackImport({state:next.state,rows:[f.r],criteria,reviewRound:f.r.reviewRound}).evaluationProposals.length,1);});
test('rejects receipt identity mismatch',async t=>{const f=await fixture(t),op=operation(f.r),state=withOperation(f.api,f.state,op),input={state,rows:[f.r],criteria,reviewRound:f.r.reviewRound};const receipt=f.api.prepareFeedbackImport(input).proposedReceipts[0];assert.throws(()=>f.api.prepareFeedbackImport({...input,receipts:[{...receipt,id:'wrong-post'}]}),/receipt|identity/i);});
test('preserves ordered operations and rejects a forged final manifest review',async t=>{const f=await fixture(t),first=operation(f.r),second=operation(f.r,{operationId:'second-operation',baseRevision:1,payload:{score:10,note:'Second memo',checks:{readable:true},decision:'needs_revision'}});const state=withOperation(f.api,withOperation(f.api,f.state,first),second),input={state,rows:[f.r],criteria,reviewRound:f.r.reviewRound};const result=f.api.prepareFeedbackImport(input);assert.deepEqual(result.evaluationProposals.map(p=>p.evaluation.score),[8,10]);const forged=structuredClone(state);forged.manifest.entries[0].review.score=3;assert.throws(()=>f.api.prepareFeedbackImport({...input,state:forged}),/manifest|ledger/i);});
test('opens the verified 0.3.18 store with readOnly and exposes no write methods',async t=>{const api=await load(),root=await fs.mkdtemp(path.join(os.tmpdir(),'pc-readonly-fixture-'));t.after(()=>fs.rm(root,{recursive:true,force:true}));const opened=api.createReadOnlyPcStore(root);assert.equal(opened.pcVersion,'0.3.18');assert.equal(opened.readOnly,true);assert.equal(Object.hasOwn(opened,'save'),false);assert.equal(Object.hasOwn(opened,'decide'),false);assert.deepEqual((await opened.list()).entries,[]);assert.deepEqual(await fs.readdir(root),[]);});
test('approved receipt plus matching canonical evaluation permits the next revision',async t=>{const f=await fixture(t),first=operation(f.r),firstResult=f.api.prepareFeedbackImport({state:withOperation(f.api,f.state,first),rows:[f.r],criteria,reviewRound:f.r.reviewRound}),second=operation(f.r,{operationId:'next-operation',baseRevision:1,payload:{score:1,note:'Next canonical proposal',checks:{readable:false},decision:'unreviewed'}});const state=withOperation(f.api,withOperation(f.api,f.state,first),second);const result=f.api.prepareFeedbackImport({state,rows:[f.r],criteria,reviewRound:f.r.reviewRound,receipts:firstResult.proposedReceipts,canonicalEvaluations:[firstResult.evaluationProposals[0].evaluation]});assert.equal(result.duplicates.length,1);assert.equal(result.evaluationProposals.length,1);assert.equal(result.evaluationProposals[0].evaluation.score,1);});
test('reusable fixture exports without real materials and invalid image identity is denied',async t=>{const {syntheticInputs,syntheticPng}=await import('../pc/synthetic-fixture.mjs');const input=syntheticInputs(),api=await load(),root=await fs.mkdtemp(path.join(os.tmpdir(),'pc-reusable-fixture-'));t.after(()=>fs.rm(root,{recursive:true,force:true}));const exported=await api.exportRelease({...input,allowedOutputRoot:root,outputDirectory:path.join(root,'release')});assert.deepEqual(await fs.readFile(path.join(exported.assetDirectory,sha(syntheticPng)+'.png')),syntheticPng);await assert.rejects(input.store.image('wrong-id',1,version(input.rows[0])),/identity/i);});
test('writes the trusted PC snapshot outside the mobile-review upload tree',async t=>{const f=await fixture(t);assert.ok(f.snapshotFile);assert.equal(path.dirname(f.snapshotFile),path.join(f.outputDirectory,'pc-local'));assert.deepEqual(JSON.parse(await fs.readFile(f.snapshotFile,'utf8')),f.trustedLocalSnapshot);assert.equal(f.trustedLocalSnapshot.pcExchangeProvenanceSchema,1);assert.deepEqual(f.trustedLocalSnapshot.pcExport,f.state.pcExport);assert.equal((await fs.readdir(path.join(f.outputDirectory,'mobile-review'))).includes('export-provenance.json'),false);});
test('requires the independently retained local snapshot and rejects a forged remote baseline',async t=>{const f=await fixture(t),raw=await load(),state=withOperation(f.api,f.state,operation(f.r)),input={state,rows:[f.r],criteria,reviewRound:f.r.reviewRound};assert.throws(()=>raw.prepareFeedbackImport(input),/trusted.*snapshot/i);const forged=structuredClone(state),k=Object.keys(forged.pcExport.entries)[0];forged.pcExport.entries[k].canonicalEvaluationHash='f'.repeat(64);assert.throws(()=>raw.prepareFeedbackImport({...input,state:forged,trustedLocalSnapshot:f.trustedLocalSnapshot}),/trusted|baseline/i);const malformed=structuredClone(f.trustedLocalSnapshot);malformed.pcExchangeProvenanceSchema=999;assert.throws(()=>raw.prepareFeedbackImport({...input,trustedLocalSnapshot:malformed}),/trusted.*snapshot/i);});
test('prior-state export requires a local snapshot and rejects remotely modified provenance',async t=>{const f=await fixture(t),input={store:f.s,rows:[f.r],criteria,reviewRound:f.r.reviewRound,previousState:f.state,previousAssetDirectory:f.assetDirectory,allowedOutputRoot:f.root,outputDirectory:path.join(f.root,'again')};await assert.rejects(f.api.exportRelease(input),/trusted.*snapshot/i);const forged=structuredClone(f.state),k=Object.keys(forged.pcExport.entries)[0];forged.pcExport.entries[k].baseRevision=10;await assert.rejects(f.api.exportRelease({...input,previousState:forged,previousTrustedLocalSnapshot:f.trustedLocalSnapshot}),/trusted|baseline/i);assert.equal(await fs.stat(input.outputDirectory).catch(e=>e.code),'ENOENT');});
test('trusted snapshot binds release identity and criteria while allowing mobile review updates',async t=>{const f=await fixture(t),raw=await load(),op=operation(f.r),state=withOperation(f.api,f.state,op),input={state,rows:[f.r],criteria,reviewRound:f.r.reviewRound,trustedLocalSnapshot:f.trustedLocalSnapshot};assert.equal(raw.prepareFeedbackImport(input).evaluationProposals.length,1);const altered=structuredClone(state);altered.manifest.criteria.items[0].label='Tampered criterion';assert.throws(()=>raw.prepareFeedbackImport({...input,state:altered}),/trusted|identity/i);const changedId=structuredClone(state);changedId.manifest.entries[0].id='forged-post';assert.throws(()=>raw.prepareFeedbackImport({...input,state:changedId}),/trusted|identity/i);});
test('refuses absent remote baseline and a local snapshot from a different release',async t=>{const f=await fixture(t),raw=await load(),input={state:f.state,trustedLocalSnapshot:f.trustedLocalSnapshot,rows:[f.r],criteria,reviewRound:f.r.reviewRound};const absent=structuredClone(f.state);delete absent.pcExport;assert.throws(()=>raw.prepareFeedbackImport({...input,state:absent}),/baseline|trusted/i);const wrong=structuredClone(f.trustedLocalSnapshot);wrong.releaseIdentityHash='f'.repeat(64);assert.throws(()=>raw.prepareFeedbackImport({...input,trustedLocalSnapshot:wrong}),/identity|trusted/i);});
test('rejects a junction alias into source materials with zero source writes',async t=>{const api=await load(),root=await fs.mkdtemp(path.join(os.tmpdir(),'pc-exchange-junction-'));t.after(async()=>{const relative=path.relative(path.resolve(os.tmpdir()),path.resolve(root));assert.ok(relative&&!relative.startsWith('..')&&!path.isAbsolute(relative));await fs.rm(root,{recursive:true,force:true});});const source=path.join(root,'materials'),alias=path.join(root,'alias');await fs.mkdir(source);await fs.symlink(source,alias,process.platform==='win32'?'junction':'dir');const s={...store(),root:source};await assert.rejects(api.exportRelease({store:s,rows:[row()],criteria,reviewRound:'fixture-round',allowedOutputRoot:root,outputDirectory:path.join(alias,'new')}),/source|material/i);assert.deepEqual(await fs.readdir(source),[]);});

test('exports verified 0.3.18 provenance and imports its exact trusted baseline',async t=>{const f=await fixture(t,{store:{...store(),pcVersion:'0.3.18'}});assert.equal(f.state.pcExport.pcVersion,'0.3.18');assert.equal(f.trustedLocalSnapshot.pcExport.pcVersion,'0.3.18');const op=operation(f.r);assert.equal(f.api.prepareFeedbackImport({state:withOperation(f.api,f.state,op),rows:[f.r],criteria,reviewRound:f.r.reviewRound}).evaluationProposals.length,1);});
test('supports only exact verified PC contracts and rejects unsupported claimed store versions before writes',async t=>{const api=await load();for(const candidate of ['0.3.16','0.3.18'])assert.equal(api.isVerifiedPcVersion(candidate),true);for(const candidate of ['0.3.17','0.3.19','0.3.180','0.3.18-beta',null,318])assert.equal(api.isVerifiedPcVersion(candidate),false);const root=await fs.mkdtemp(path.join(os.tmpdir(),'pc-version-denied-'));t.after(()=>fs.rm(root,{recursive:true,force:true}));for(const pcVersion of ['0.3.17','0.3.19'])await assert.rejects(api.exportRelease({store:{...store(),pcVersion},rows:[row()],criteria,reviewRound:'fixture-round',allowedOutputRoot:root,outputDirectory:path.join(root,'denied')}),/verified.*version/i);assert.deepEqual(await fs.readdir(root),[]);});
test('same release after PC runtime upgrade retains legacy trusted remote baseline and importability',async t=>{const f=await fixture(t,{store:{...store(),pcVersion:'0.3.16'}}),op=operation(f.r),previous=withOperation(f.api,f.state,op);const next=await f.api.exportRelease({store:{...f.s,pcVersion:'0.3.18'},rows:[f.r],criteria,reviewRound:f.r.reviewRound,previousState:previous,previousTrustedLocalSnapshot:f.trustedLocalSnapshot,previousAssetDirectory:f.assetDirectory,allowedOutputRoot:f.root,outputDirectory:path.join(f.root,'upgraded')});assert.equal(next.state.pcExport.pcVersion,'0.3.16');assert.deepEqual(next.state.pcExport,previous.pcExport);assert.deepEqual(next.trustedLocalSnapshot,f.trustedLocalSnapshot);const input={state:previous,trustedLocalSnapshot:next.trustedLocalSnapshot,rows:[f.r],criteria,reviewRound:f.r.reviewRound};assert.equal(f.api.prepareFeedbackImport(input).evaluationProposals.length,1);assert.deepEqual(next.state.operations,previous.operations);});
test('new release after PC runtime upgrade records 0.3.18 and preserves exact prior 0.3.16 history',async t=>{const f=await fixture(t,{store:{...store(),pcVersion:'0.3.16'}}),r=row({reviewRound:'next-round',outputSha256:'3'.repeat(64)});const next=await f.api.exportRelease({store:{...store(r),pcVersion:'0.3.18'},rows:[r],criteria,reviewRound:r.reviewRound,previousState:f.state,previousTrustedLocalSnapshot:f.trustedLocalSnapshot,previousAssetDirectory:f.assetDirectory,allowedOutputRoot:f.root,outputDirectory:path.join(f.root,'next-version')});assert.equal(next.state.pcExport.pcVersion,'0.3.18');assert.deepEqual(next.state.history[0].pcExport,f.state.pcExport);});
test('rejects unverified trusted provenance versions even if remote version matches',async t=>{const f=await fixture(t),state=structuredClone(f.state),trusted=structuredClone(f.trustedLocalSnapshot);state.pcExport.pcVersion=trusted.pcExport.pcVersion='0.3.19';assert.throws(()=>f.api.prepareFeedbackImport({state,trustedLocalSnapshot:trusted,rows:[f.r],criteria,reviewRound:f.r.reviewRound}),/trusted.*snapshot/i);});
