import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {syntheticInputs} from '../pc/synthetic-fixture.mjs';
import {version} from '../../../desktop/post-review-store.cjs';
const load=()=>import('../pc/github-transport.mjs');
const repo={owner:'synthetic-owner',repo:'private-review-fixture',repositoryId:123,private:true,dedicatedReviewRepository:true,branch:'mobile-review/data',excludedRepositories:['synthetic-owner/bridge-fixture']};
const prefix='/repos/'+repo.owner+'/'+repo.repo,head='a'.repeat(40),tree='b'.repeat(40);
const blobSha=b=>createHash('sha1').update(Buffer.concat([Buffer.from('blob '+b.length+'\0'),b])).digest('hex');
function fixture(){const f=syntheticInputs(),r=f.rows[0];const url='/v1/review/assets/'+r.images[0].sha256+'.png';return {githubReviewSchema:1,manifest:{schemaVersion:1,reviewRound:f.reviewRound,criteria:f.criteria,entries:[{id:r.id,title:r.title,outputVersion:version(r),reviewRound:f.reviewRound,revision:0,images:[{url,sha256:r.images[0].sha256}],review:null}]},assets:{[url]:{sha256:r.images[0].sha256,blobSha:blobSha(Buffer.from('synthetic'))}},operations:{}};}
function apiMock(state=fixture()){return async route=>{if(route===prefix)return {...repo,id:repo.repositoryId,owner:{login:repo.owner},name:repo.repo,default_branch:'main'};if(route===prefix+'/git/ref/heads/'+repo.branch)return {object:{sha:head}};if(route===prefix+'/git/commits/'+head)return {sha:head,tree:{sha:tree}};if(route===prefix+'/contents/mobile-review/state.json?ref='+head){const b=Buffer.from(JSON.stringify(state));return {encoding:'base64',content:b.toString('base64'),size:b.length,sha:blobSha(b)};}throw Error('Unexpected mock route');};}
test('PC transport and pinned reader default off before credential or network access',async()=>{const m=await load();let calls=0;const api=m.createPcGithubTransport({repository:repo,getAccessToken:()=>{calls++;},fetchImpl:()=>{calls++;}});await assert.rejects(api(prefix),/disabled/i);await assert.rejects(m.readPinnedReviewState({repository:repo,api:()=>{calls++;}}),/disabled/i);assert.equal(calls,0);});
test('fixed official HTTPS selected-repository transport uses injected token only',async()=>{const m=await load();const calls=[];const api=m.createPcGithubTransport({enabled:true,repository:repo,getAccessToken:async()=> 'synthetic-access',fetchImpl:async(url,init)=>{calls.push({url,init});return new Response(JSON.stringify({private:true}),{status:200});}});assert.deepEqual(await api(prefix),{private:true});assert.equal(calls[0].url,'https://api.github.com'+prefix);assert.equal(calls[0].init.redirect,'manual');assert.equal(calls[0].init.headers.Authorization,'Bearer synthetic-access');});
test('unexpected host, other repository, workflow path and force update make zero calls',async()=>{const m=await load();let calls=0;const api=m.createPcGithubTransport({enabled:true,repository:repo,getAccessToken:()=>{calls++;return 'synthetic-access';},fetchImpl:()=>{calls++;}});for(const p of ['https://evil.invalid'+prefix,prefix+'-other',prefix+'/actions',prefix+'/contents/secret'])await assert.rejects(api(p),/route|path/i);await assert.rejects(api(prefix+'/git/refs/heads/'+repo.branch,{method:'PATCH',body:{sha:head,force:true}}),/route|force/i);assert.equal(calls,0);});
test('write trees only contain hashed PNG and state, no PC provenance or unrelated deletion',async()=>{const m=await load();let calls=0;const api=m.createPcGithubTransport({enabled:true,repository:repo,getAccessToken:()=>{calls++;return 'synthetic-access';},fetchImpl:async()=>new Response('{}')});for(const item of [{path:'pc-local/export-provenance.json',sha:head},{path:'.github/workflows/run.yml',sha:head},{path:'mobile-review/state.json',sha:null}])await assert.rejects(api(prefix+'/git/trees',{method:'POST',body:{base_tree:tree,tree:[{...item,mode:'100644',type:'blob'}]}}),/tree|write|path|route/i);assert.equal(calls,0);});
test('auth and lost response errors never expose provider or response secrets or retry',async()=>{const m=await load();let calls=0;const denied=m.createPcGithubTransport({enabled:true,repository:repo,getAccessToken:()=>{throw Error('SYNTHETIC_SECRET');},fetchImpl:()=>calls++});await assert.rejects(denied(prefix),e=>!e.message.includes('SYNTHETIC_SECRET'));const api=m.createPcGithubTransport({enabled:true,repository:repo,getAccessToken:()=> 'synthetic-access',fetchImpl:async()=>{calls++;throw Error('SYNTHETIC_SECRET');}});await assert.rejects(api(prefix),e=>!e.message.includes('SYNTHETIC_SECRET'));assert.equal(calls,1);});
test('rate limits produce sanitized status and cooldown without repeated request',async()=>{const m=await load();let calls=0;const api=m.createPcGithubTransport({enabled:true,repository:repo,now:()=>1000,getAccessToken:()=> 'synthetic-access',fetchImpl:async()=>{calls++;return new Response('SYNTHETIC_SECRET',{status:429,headers:{'retry-after':'120'}});}});await assert.rejects(api(prefix),e=>e.status===429&&!e.message.includes('SYNTHETIC_SECRET'));await assert.rejects(api(prefix),e=>e.status===429);assert.equal(calls,1);});
test('redirects, malformed JSON and oversized responses are refused',async()=>{const m=await load();for(const response of [new Response('',{status:302}),new Response('bad',{status:200}),new Response('{}',{status:200,headers:{'content-length':String(40*1024*1024)}})]){const api=m.createPcGithubTransport({enabled:true,repository:repo,getAccessToken:()=> 'synthetic-access',fetchImpl:async()=>response});await assert.rejects(api(prefix));}});
test('reader pins private identity, exact commit and state blob hash without writes',async()=>{const m=await load(),state=fixture(),calls=[];const mock=apiMock(state);const result=await m.readPinnedReviewState({enabled:true,repository:repo,expectedHead:head,api:async(...args)=>{calls.push(args);return mock(...args);}});assert.equal(result.head,head);assert.equal(result.tree,tree);assert.deepEqual(result.state,state);assert.equal(calls.length,4);assert(calls.every(c=>c.length===1));});
test('reader refuses public/wrong identity/default branch/head mismatch and corrupt blobs',async()=>{const m=await load();for(const change of [{private:false},{id:444},{owner:{login:'other'}},{name:'other'},{default_branch:repo.branch}]){const mock=apiMock();await assert.rejects(m.readPinnedReviewState({enabled:true,repository:repo,api:async route=>route===prefix?{id:123,private:true,owner:{login:repo.owner},name:repo.repo,default_branch:'main',...change}:mock(route)}));}await assert.rejects(m.readPinnedReviewState({enabled:true,repository:repo,expectedHead:'c'.repeat(40),api:apiMock()}));const mock=apiMock();await assert.rejects(m.readPinnedReviewState({enabled:true,repository:repo,api:async route=>{const r=await mock(route);return route.includes('/contents/')?{...r,sha:'c'.repeat(40)}:r;}}));});
test('only explicit pinned state-path 404 can initialize empty state',async()=>{const m=await load();for(const status of [401,403,404]){const mock=apiMock();const api=async route=>{if(route.includes('/contents/'))throw Object.assign(Error('Synthetic denied'),{status});return mock(route);};if(status===404){const r=await m.readPinnedReviewState({enabled:true,repository:repo,api,allowAbsent:true});assert.equal(r.state,null);await assert.rejects(m.readPinnedReviewState({enabled:true,repository:repo,api}));}else await assert.rejects(m.readPinnedReviewState({enabled:true,repository:repo,api,allowAbsent:true}));}});
test('same repository exact commit comparison is allowed for lost-response lineage verification',async()=>{const m=await load();let calls=0;const api=m.createPcGithubTransport({enabled:true,repository:repo,getAccessToken:()=> 'synthetic-access',fetchImpl:async()=>{calls++;return new Response(JSON.stringify({status:'ahead'}));}});assert.equal((await api(prefix+'/compare/'+head+'...'+tree)).status,'ahead');await assert.rejects(api(prefix+'/compare/main...other'),/route/i);assert.equal(calls,1);});
test('credential wait cannot mutate the already validated wire request into force push or other path',async()=>{const m=await load();for(const type of ['patch','tree']){let release,captured;const token=new Promise(r=>release=r);const body=type==='patch'?{sha:head,force:false}:{base_tree:tree,tree:[{path:'mobile-review/state.json',mode:'100644',type:'blob',sha:head}]};const api=m.createPcGithubTransport({enabled:true,repository:repo,getAccessToken:()=>token,fetchImpl:async(_,init)=>{captured=JSON.parse(init.body);return new Response('{}');}});const result=api(prefix+(type==='patch'?'/git/refs/heads/'+repo.branch:'/git/trees'),{method:type==='patch'?'PATCH':'POST',body});if(type==='patch')body.force=true;else body.tree[0].path='.github/workflows/run.yml';release('synthetic-access');await result;if(type==='patch')assert.equal(captured.force,false);else assert.equal(captured.tree[0].path,'mobile-review/state.json');}});
test('custom serialization is validated as actual wire bytes before any credential or network call',async()=>{const m=await load();let calls=0;const api=m.createPcGithubTransport({enabled:true,repository:repo,getAccessToken:()=>{calls++;return 'synthetic-access';},fetchImpl:()=>{calls++;}});const body={base_tree:tree,tree:[{path:'mobile-review/state.json',mode:'100644',type:'blob',sha:head}],toJSON(){return {base_tree:tree,tree:[{path:'.github/workflows/run.yml',mode:'100644',type:'blob',sha:head}]};}};await assert.rejects(api(prefix+'/git/trees',{method:'POST',body}),/route/i);assert.equal(calls,0);});
