import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import {createHash} from 'node:crypto';
import {exportRelease,requestHash} from '../pc/exchange.mjs';
import {syntheticInputs} from '../pc/synthetic-fixture.mjs';
const load=()=>import('../pc/publish-release.mjs');
const expectedHead='a'.repeat(40),baseTree='b'.repeat(40),candidate='c'.repeat(40),advanced='d'.repeat(40),newTree='e'.repeat(40);
const blobSha=bytes=>createHash('sha1').update(Buffer.concat([Buffer.from('blob '+bytes.length+'\0'),bytes])).digest('hex');
function mockGithub(){
 const mock={calls:[],head:expectedHead,private:true,id:123,owner:'synthetic-owner',repo:'private-review-fixture',defaultBranch:'main',refReads:0,beforeFinalRead:null,beforePatch:null,loseAck:false,corruptBlob:false,failStatus:null,remoteState:null,patchStatus:null};
 const prefix='/repos/synthetic-owner/private-review-fixture';
 mock.api=async(url,init={})=>{
  const method=init.method||'GET',body=init.body;mock.calls.push({url,method,body});
  if(mock.failStatus)throw Object.assign(Error('Synthetic transport denied'),{status:mock.failStatus});
  if(url===prefix)return {id:mock.id,private:mock.private,owner:{login:mock.owner},name:mock.repo,default_branch:mock.defaultBranch};
  const route=url.slice(prefix.length);
  if(route==='/git/ref/heads/mobile-review/data'){mock.refReads++;if(mock.refReads===2&&mock.beforeFinalRead)mock.beforeFinalRead();return {object:{sha:mock.head}};}
  if(route==='/git/commits/'+expectedHead&&method==='GET')return {sha:expectedHead,tree:{sha:baseTree},parents:[]};
  if(route==='/contents/mobile-review/state.json?ref='+expectedHead){if(mock.remoteState===null)throw Object.assign(Error('Synthetic initial empty ledger'),{status:404});const bytes=Buffer.from(JSON.stringify(mock.remoteState));return {encoding:'base64',content:bytes.toString('base64'),size:bytes.length,sha:blobSha(bytes)};}
  if(route==='/git/blobs'&&method==='POST'){const bytes=Buffer.from(body.content,body.encoding==='base64'?'base64':'utf8');return {sha:mock.corruptBlob?advanced:blobSha(bytes)};}
  if(route==='/git/trees'&&method==='POST')return {sha:newTree};
  if(route==='/git/commits'&&method==='POST')return {sha:candidate,tree:{sha:body.tree},parents:body.parents.map(sha=>({sha}))};
  if(route==='/git/refs/heads/mobile-review/data'&&method==='PATCH'){
   if(mock.patchStatus)throw Object.assign(Error('Synthetic ref rejected'),{status:mock.patchStatus});
   if(mock.beforePatch)mock.beforePatch();
   if(mock.head!==expectedHead)throw Object.assign(Error('Synthetic non-fast-forward'),{status:409});
   assert.equal(body.force,false);assert.equal(body.sha,candidate);mock.head=candidate;
   if(mock.loseAck)throw Error('Synthetic lost acknowledgement');return {object:{sha:mock.head}};
  }
  throw Error('Unexpected synthetic route '+url);
 };
 return mock;
}
async function fixture(t){const root=await fs.mkdtemp(path.join(os.tmpdir(),'pc-publish-fixture-'));t.after(async()=>{const rel=path.relative(path.resolve(os.tmpdir()),path.resolve(root));assert.ok(rel&&!rel.startsWith('..')&&!path.isAbsolute(rel));await fs.rm(root,{recursive:true,force:true});});const exported=await exportRelease({...syntheticInputs(),allowedOutputRoot:root,outputDirectory:path.join(root,'release')}),api=await load(),mock=mockGithub();const input={approved:true,dedicatedReviewRepository:true,owner:'synthetic-owner',repo:'private-review-fixture',repositoryId:123,branch:'mobile-review/data',excludedRepositories:['synthetic-owner/bridge','synthetic-owner/commands'],exportDirectory:exported.outputDirectory,expectedHead,api:mock.api};return {root,exported,api,mock,input};}
const writes=mock=>mock.calls.filter(c=>c.method!=='GET');
async function modifyState(f,change){const state=JSON.parse(await fs.readFile(f.exported.stateFile,'utf8'));change(state);await fs.writeFile(f.exported.stateFile,JSON.stringify(state));}

test('publishes immutable assets and exact state in one non-force expected-parent transaction',async t=>{const f=await fixture(t),bytes=await fs.readFile(f.exported.stateFile),result=await f.api.publishPreparedRelease(f.input);assert.equal(result.status,'confirmed');assert.equal(result.head,candidate);assert.equal(result.assetCount,1);const tree=f.mock.calls.find(c=>c.url.endsWith('/git/trees')).body;assert.equal(tree.base_tree,baseTree);assert.deepEqual(tree.tree.map(e=>e.path).sort(),['mobile-review/assets/'+Object.values(f.exported.state.assets)[0].sha256+'.png','mobile-review/state.json']);assert.ok(tree.tree.every(e=>e.mode==='100644'&&e.type==='blob'));const commit=f.mock.calls.find(c=>c.url.endsWith('/git/commits')&&c.method==='POST').body;assert.deepEqual(commit.parents,[expectedHead]);assert.equal(commit.tree,newTree);assert.deepEqual(f.mock.calls.find(c=>c.method==='PATCH').body,{sha:candidate,force:false});assert.deepEqual(await fs.readFile(f.exported.stateFile),bytes);assert.ok(!JSON.stringify(f.mock.calls).includes('pc-local'));});
test('requires explicit publication and dedicated repository approval before API calls',async t=>{const f=await fixture(t);await assert.rejects(f.api.publishPreparedRelease({...f.input,approved:false}),/approval/i);await assert.rejects(f.api.publishPreparedRelease({...f.input,dedicatedReviewRepository:false}),/dedicated|approval/i);assert.equal(f.mock.calls.length,0);});
test('rejects bridge/command identities and malformed branch or expected head before API calls',async t=>{const f=await fixture(t);await assert.rejects(f.api.publishPreparedRelease({...f.input,excludedRepositories:['synthetic-owner/private-review-fixture']}),/separate|excluded/i);await assert.rejects(f.api.publishPreparedRelease({...f.input,branch:'main'}),/branch/i);await assert.rejects(f.api.publishPreparedRelease({...f.input,expectedHead:'bad'}),/head|SHA/i);assert.equal(f.mock.calls.length,0);});
test('checks private visibility, numeric identity, owner/name and non-default branch before object writes',async t=>{for(const change of [{private:false},{id:999},{owner:'wrong-owner'},{repo:'wrong-repo'},{defaultBranch:'mobile-review/data'}]){const f=await fixture(t);Object.assign(f.mock,change);const result=await f.api.publishPreparedRelease(f.input);assert.equal(result.status,'pending');assert.equal(writes(f.mock).length,0);}});
test('refuses an advanced initial head with zero Git object writes',async t=>{const f=await fixture(t);f.mock.head=advanced;const result=await f.api.publishPreparedRelease(f.input);assert.equal(result.status,'stale');assert.equal(result.observedHead,advanced);assert.equal(writes(f.mock).length,0);});
test('detects a branch advance before ref update and leaves the export pending',async t=>{const f=await fixture(t);f.mock.beforeFinalRead=()=>{f.mock.head=advanced;};const result=await f.api.publishPreparedRelease(f.input);assert.equal(result.status,'pending');assert.equal(result.reason,'branch_advanced');assert.equal(f.mock.calls.filter(c=>c.method==='PATCH').length,0);assert.equal(f.mock.head,advanced);});
test('non-fast-forward race after the final read never retries or overwrites',async t=>{const f=await fixture(t);f.mock.beforePatch=()=>{f.mock.head=advanced;};const result=await f.api.publishPreparedRelease(f.input);assert.equal(result.status,'pending');assert.equal(result.reason,'non_fast_forward');assert.equal(f.mock.calls.filter(c=>c.method==='PATCH').length,1);assert.equal(f.mock.head,advanced);});
test('lost ref acknowledgement is unconfirmed pending with a candidate commit and no retry',async t=>{const f=await fixture(t);f.mock.loseAck=true;const result=await f.api.publishPreparedRelease(f.input);assert.equal(result.status,'pending');assert.equal(result.reason,'publication_unconfirmed');assert.equal(result.candidateCommit,candidate);assert.equal(f.mock.head,candidate);assert.equal(f.mock.calls.filter(c=>c.method==='PATCH').length,1);});
test('validates every created Git blob SHA before creating trees or updating refs',async t=>{const f=await fixture(t);f.mock.corruptBlob=true;const result=await f.api.publishPreparedRelease(f.input);assert.equal(result.status,'pending');assert.equal(result.reason,'git_blob_hash_mismatch');assert.equal(writes(f.mock).length,1);assert.equal(f.mock.head,expectedHead);});
test('rejects corrupted PNG bytes and incorrect Git blob mappings before API calls',async t=>{const first=await fixture(t),hash=Object.values(first.exported.state.assets)[0].sha256;await fs.writeFile(path.join(first.exported.assetDirectory,hash+'.png'),'bad png');await assert.rejects(first.api.publishPreparedRelease(first.input),/PNG|hash/i);assert.equal(first.mock.calls.length,0);const second=await fixture(t);await modifyState(second,state=>{Object.values(state.assets)[0].blobSha=advanced;});await assert.rejects(second.api.publishPreparedRelease(second.input),/blob|hash/i);assert.equal(second.mock.calls.length,0);});
test('rejects extra files, missing assets and local-provenance files within the upload tree',async t=>{const first=await fixture(t);await fs.writeFile(path.join(first.exported.assetDirectory,'unhashed.png'),'bad');await assert.rejects(first.api.publishPreparedRelease(first.input),/asset|file|namespace/i);assert.equal(first.mock.calls.length,0);const second=await fixture(t);await fs.rename(second.exported.assetDirectory,path.join(second.root,'hidden-assets'));await assert.rejects(second.api.publishPreparedRelease(second.input));assert.equal(second.mock.calls.length,0);const third=await fixture(t);await fs.mkdir(path.join(third.exported.outputDirectory,'mobile-review','pc-local'));await assert.rejects(third.api.publishPreparedRelease(third.input),/namespace|pc.local|file/i);assert.equal(third.mock.calls.length,0);});
test('rejects oversized state/assets using stat before reading their bytes',async t=>{const first=await fixture(t);await fs.truncate(first.exported.stateFile,1000001);await assert.rejects(first.api.publishPreparedRelease(first.input),/size|large|limit/i);assert.equal(first.mock.calls.length,0);const second=await fixture(t),hash=Object.values(second.exported.state.assets)[0].sha256;await fs.truncate(path.join(second.exported.assetDirectory,hash+'.png'),25*1024*1024+1);await assert.rejects(second.api.publishPreparedRelease(second.input),/size|large|limit/i);assert.equal(second.mock.calls.length,0);});
test('rejects directory junctions into assets or into an export namespace before API calls',async t=>{const f=await fixture(t),aliased=path.join(f.root,'export-alias');await fs.symlink(f.exported.outputDirectory,aliased,process.platform==='win32'?'junction':'dir');await assert.rejects(f.api.publishPreparedRelease({...f.input,exportDirectory:aliased}),/symbolic|junction|link/i);assert.equal(f.mock.calls.length,0);const assetSource=path.join(f.root,'asset-source');await fs.rename(f.exported.assetDirectory,assetSource);await fs.symlink(assetSource,f.exported.assetDirectory,process.platform==='win32'?'junction':'dir');await assert.rejects(f.api.publishPreparedRelease(f.input),/symbolic|junction|link/i);assert.equal(f.mock.calls.length,0);});
test('authorization/transport failure remains pending without publication confirmation',async t=>{const f=await fixture(t);f.mock.failStatus=401;const result=await f.api.publishPreparedRelease(f.input);assert.equal(result.status,'pending');assert.equal(result.reason,'transport_failure');assert.equal(writes(f.mock).length,0);assert.equal(f.mock.head,expectedHead);});
test('refuses pc-local or in-place mobile-review directories as export roots',async t=>{const f=await fixture(t);for(const directory of [path.join(f.exported.outputDirectory,'pc-local'),path.join(f.exported.outputDirectory,'mobile-review')])await assert.rejects(f.api.publishPreparedRelease({...f.input,exportDirectory:directory}),/export|namespace|root/i);assert.equal(f.mock.calls.length,0);});
test('reads the current ledger pinned to expectedHead and preserves unchanged remote state',async t=>{const f=await fixture(t);f.mock.remoteState=structuredClone(f.exported.state);const result=await f.api.publishPreparedRelease(f.input);assert.equal(result.status,'confirmed');const read=f.mock.calls.find(c=>c.url.includes('/contents/'));assert.equal(read.url,'/repos/synthetic-owner/private-review-fixture/contents/mobile-review/state.json?ref='+expectedHead);assert.ok(f.mock.calls.indexOf(read)<f.mock.calls.findIndex(c=>c.method==='POST'));});
test('fresh expectedHead cannot publish an older export that omits interim operations',async t=>{const f=await fixture(t),remote=structuredClone(f.exported.state),entry=remote.manifest.entries[0],op={operationId:'interim-operation',id:entry.id,outputVersion:entry.outputVersion,reviewRound:entry.reviewRound,baseRevision:0,criteriaVersion:remote.manifest.criteria.version,kind:'review',payload:{score:7,note:'Interim mobile memo',checks:{readable:true},decision:'held'},deviceId:'synthetic-device',createdAt:'2026-10-08T00:00:00.000Z'};remote.operations[op.operationId]={requestHash:requestHash(op),request:op,result:{operationId:op.operationId,status:'applied',revision:1}};entry.review=op.payload;entry.revision=1;f.mock.remoteState=remote;const result=await f.api.publishPreparedRelease(f.input);assert.equal(result.status,'pending');assert.equal(result.reason,'stale_export_operations');assert.equal(writes(f.mock).length,0);});
test('refuses changed ledger records, immutable mappings and same-version mobile reviews',async t=>{const first=await fixture(t);const legacy={requestHash:'1'.repeat(64),result:{operationId:'legacy-operation',status:'stale',revision:0}};first.mock.remoteState=structuredClone(first.exported.state);first.mock.remoteState.operations['legacy-operation']=legacy;await modifyState(first,state=>{state.operations['legacy-operation']={...legacy,requestHash:'2'.repeat(64)};});let result=await first.api.publishPreparedRelease(first.input);assert.equal(result.reason,'stale_export_operations');assert.equal(writes(first.mock).length,0);const second=await fixture(t);second.mock.remoteState=structuredClone(second.exported.state);Object.values(second.mock.remoteState.assets)[0].blobSha=advanced;result=await second.api.publishPreparedRelease(second.input);assert.equal(result.reason,'stale_export_assets');assert.equal(writes(second.mock).length,0);const third=await fixture(t);third.mock.remoteState=structuredClone(third.exported.state);third.mock.remoteState.manifest.entries[0].review={score:8,note:'Current remote review',checks:{readable:true},decision:'held'};third.mock.remoteState.manifest.entries[0].revision=1;result=await third.api.publishPreparedRelease(third.input);assert.equal(result.reason,'stale_export_reviews');assert.equal(writes(third.mock).length,0);});
test('new release must archive the exact remote manifest including its latest reviews',async t=>{const f=await fixture(t);f.mock.remoteState=structuredClone(f.exported.state);f.mock.remoteState.manifest.entries[0].review={score:8,note:'Last review of old release',checks:{readable:true},decision:'held'};f.mock.remoteState.manifest.entries[0].revision=1;await modifyState(f,state=>{const oldKey=Object.keys(state.pcExport.entries)[0];state.manifest.reviewRound='next-round';state.manifest.entries[0].reviewRound='next-round';state.manifest.entries[0].outputVersion='f'.repeat(64);const e=state.manifest.entries[0],newKey=JSON.stringify([e.id,e.outputVersion,e.reviewRound]);state.pcExport.entries[newKey]=state.pcExport.entries[oldKey];delete state.pcExport.entries[oldKey];});let result=await f.api.publishPreparedRelease(f.input);assert.equal(result.reason,'stale_export_history');assert.equal(writes(f.mock).length,0);await modifyState(f,state=>{state.history.push({manifest:f.mock.remoteState.manifest,pcExport:f.mock.remoteState.pcExport});});result=await f.api.publishPreparedRelease(f.input);assert.equal(result.status,'confirmed');});
test('a 422 ref rejection remains pending without asserting a concurrency cause',async t=>{const f=await fixture(t);f.mock.patchStatus=422;const result=await f.api.publishPreparedRelease(f.input);assert.equal(result.status,'pending');assert.equal(result.reason,'ref_update_rejected');assert.equal(f.mock.calls.filter(c=>c.method==='PATCH').length,1);assert.equal(f.mock.head,expectedHead);});

test('publisher accepts exact verified 0.3.18 prepared and pinned provenance',async t=>{const f=await fixture(t);await modifyState(f,state=>{state.pcExport.pcVersion='0.3.18';});f.mock.remoteState=JSON.parse(await fs.readFile(f.exported.stateFile,'utf8'));const result=await f.api.publishPreparedRelease(f.input);assert.equal(result.status,'confirmed');});
test('publisher accepts exact verified 0.3.19 prepared and pinned provenance',async t=>{const f=await fixture(t);await modifyState(f,state=>{state.pcExport.pcVersion='0.3.19';});f.mock.remoteState=JSON.parse(await fs.readFile(f.exported.stateFile,'utf8'));assert.equal((await f.api.publishPreparedRelease(f.input)).status,'confirmed');});
test('publisher refuses unverified prepared PC provenance before any transport call',async t=>{for(const pcVersion of ['0.3.17','0.3.20','0.3.18-beta']){const f=await fixture(t);await modifyState(f,state=>{state.pcExport.pcVersion=pcVersion;});await assert.rejects(f.api.publishPreparedRelease(f.input),/baseline/i);assert.equal(f.mock.calls.length,0);}});
