import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {syntheticInputs,syntheticPng} from '../pc/synthetic-fixture.mjs';
import {requestHash} from '../pc/exchange.mjs';
const load=()=>import('../pc/release-feed.mjs');
const hash=bytes=>createHash('sha256').update(bytes).digest('hex');
const blob=bytes=>createHash('sha1').update(Buffer.concat([Buffer.from('blob '+bytes.length+'\0'),bytes])).digest('hex');
const firstHead='a'.repeat(40),firstTree='b'.repeat(40);
const repository={owner:'synthetic-owner',repo:'review-fixture',repositoryId:123,private:true,dedicatedReviewRepository:true,branch:'mobile-review/data',excludedRepositories:['synthetic-owner/bridge']};
const prefix='/repos/synthetic-owner/review-fixture';
function snapshots(input){const rows=structuredClone(input.rows).map(r=>({...r,status:'generated'})),pages=rows.reduce((n,r)=>n+r.images.length,0);return {pointer:{active:true,wholeCollectionRegenerated:true,reviewRound:input.reviewRound,posts:rows.length,pages},report:{reviewRound:input.reviewRound,deliveryStatus:'complete',processed:rows.length,entries:rows},deliveryJournal:{reviewRound:input.reviewRound,complete:true}};}
function mockRemote(){
 const m={head:firstHead,state:null,calls:[],blobs:new Map(),commits:new Map([[firstHead,{sha:firstHead,tree:{sha:firstTree},parents:[]}]]),trees:new Map(),losePatch:false,loseCommit:false,failPatch:false,corruptCandidate:false,blobReadsCorrupt:false,beforePatch:null};
 m.api=async(url,init={})=>{
  const method=init.method||'GET',body=init.body;m.calls.push({url,method,body});const route=url.slice(prefix.length);
  if(url===prefix)return {id:123,private:true,owner:{login:repository.owner},name:repository.repo,default_branch:'main'};
  if(route==='/git/ref/heads/'+repository.branch)return {object:{sha:m.head}};
  if(route.startsWith('/git/commits/')&&method==='GET'){const c=m.commits.get(route.split('/').at(-1));if(!c)throw Object.assign(Error('absent commit'),{status:404});return structuredClone(c);}
  if(route.startsWith('/contents/mobile-review/state.json?ref=')){
   const head=route.split('=').at(-1),commit=m.commits.get(head),tree=m.trees.get(commit?.tree.sha),entry=tree?.find(e=>e.path==='mobile-review/state.json');let bytes=entry?m.blobs.get(entry.sha):null;
   if(head===m.head&&m.state)bytes=Buffer.from(JSON.stringify(m.state));
   if(!bytes)throw Object.assign(Error('absent state'),{status:404});return {sha:blob(bytes),encoding:'base64',size:bytes.length,content:bytes.toString('base64')};
  }
  if(route.startsWith('/git/blobs/')&&method==='GET'){const sha=route.split('/').at(-1),bytes=m.blobs.get(sha);if(!bytes)throw Object.assign(Error('absent blob'),{status:404});return {sha,encoding:'base64',size:bytes.length,content:(m.blobReadsCorrupt?Buffer.from('corrupt'):bytes).toString('base64')};}
  if(route==='/git/blobs'&&method==='POST'){const bytes=Buffer.from(body.content,'base64'),sha=blob(bytes);m.blobs.set(sha,bytes);return {sha};}
  if(route==='/git/trees'&&method==='POST'){const sha=hash(Buffer.from(JSON.stringify(body))).slice(0,40),base=m.trees.get(body.base_tree)||[],tree=new Map(base.map(e=>[e.path,e]));for(const e of body.tree)tree.set(e.path,e);m.trees.set(sha,[...tree.values()]);return {sha};}
  if(route==='/git/commits'&&method==='POST'){const sha=hash(Buffer.from(JSON.stringify(body))).slice(0,40),c={sha,tree:{sha:body.tree},parents:body.parents.map(sha=>({sha}))};m.commits.set(sha,c);if(m.loseCommit)throw Error('lost commit response');return c;}
  if(route==='/git/refs/heads/'+repository.branch&&method==='PATCH'){
   if(m.beforePatch)m.beforePatch();if(m.failPatch)throw Error('lost request before apply');assert.equal(body.force,false);const c=m.commits.get(body.sha);assert.equal(c.parents[0].sha,m.head);m.head=body.sha;m.state=null;if(m.losePatch)throw Error('lost publication acknowledgement');return {object:{sha:m.head}};
  }
  if(route.startsWith('/compare/'))return {status:'ahead',merge_base_commit:{sha:route.split('/').at(-1).split('...')[0]},head_commit:{sha:m.head}};
  throw Error('Unexpected synthetic route '+route+' '+method);
 };
 m.read=async()=>{m.calls.push({url:'pinned-snapshot',method:'GET'});let state=m.state;if(!state){try{const r=await m.api(prefix+'/contents/mobile-review/state.json?ref='+m.head);state=JSON.parse(Buffer.from(r.content,'base64'));}catch(e){if(e.status!==404)throw e;}}
 return {head:m.head,tree:m.commits.get(m.head).tree.sha,state:state?structuredClone(state):null};};return m;
}
async function fixture(t){
 const root=await fs.mkdtemp(path.join(os.tmpdir(),'pc-feed-'));t.after(async()=>{const rel=path.relative(os.tmpdir(),root);assert.ok(rel&&!rel.startsWith('..')&&!path.isAbsolute(rel));await fs.rm(root,{recursive:true,force:true});});const input=syntheticInputs(),remote=mockRemote(),api=await load();let current=snapshots(input);const persisted=[];
 const options={enabled:true,store:input.store,criteria:input.criteria,repository,readSnapshots:async()=>structuredClone(current),readRemoteSnapshot:remote.read,api:remote.api,allowedOutputRoot:root,outputDirectory:path.join(root,'release'),persistJournal:async j=>{persisted.push(structuredClone(j));}};
 return {root,input,remote,api,options,persisted,get current(){return current;},set current(v){current=v;}};
}
const writes=m=>m.calls.filter(c=>c.method!=='GET');
const commits=m=>m.calls.filter(c=>c.method==='POST'&&c.url.endsWith('/git/commits'));
function feedback(state){const next=structuredClone(state),e=next.manifest.entries[0],op={operationId:'synthetic-review',id:e.id,outputVersion:e.outputVersion,reviewRound:e.reviewRound,baseRevision:0,criteriaVersion:next.manifest.criteria.version,kind:'review',payload:{score:8,note:'Mobile feedback preserved',checks:{readable:true},decision:'held'},deviceId:'synthetic-device',createdAt:'2026-10-08T00:00:00.000Z'};e.review=op.payload;e.revision=1;next.operations[op.operationId]={requestHash:requestHash(op),request:op,result:{operationId:op.operationId,status:'applied',revision:1}};return next;}

test('selects only current complete regenerated active collection with exact counts',async()=>{const {selectCompletedRound}=await load(),s=snapshots(syntheticInputs()),selected=selectCompletedRound(s);assert.equal(selected.reviewRound,'fixture-round');assert.equal(selected.rows.length,1);assert.equal(selected.pages,1);});
test('missing intermediate failed rolled-back and mismatched rounds never select older content',async()=>{const {selectCompletedRound}=await load(),base=snapshots(syntheticInputs()),changes=[s=>s.pointer=null,s=>s.pointer.active=false,s=>s.pointer.wholeCollectionRegenerated=false,s=>s.report.deliveryStatus='pending',s=>s.report.processed=0,s=>s.report.entries[0].status='failed',s=>s.report.entries[0].status='cached',s=>s.report.entries[0].reviewRound='old',s=>s.deliveryJournal=null,s=>s.deliveryJournal.complete=false,s=>s.deliveryJournal.rolledBack=true,s=>s.deliveryJournal.reviewRound='next',s=>s.pointer.posts=2,s=>s.pointer.pages=2,s=>s.report.entries.push({...s.report.entries[0]}),s=>s.report.entries[0].images=[]];for(const change of changes){const s=structuredClone(base);change(s);assert.equal(selectCompletedRound(s),null);}});
test('default disabled feed performs no reads writes export or transport',async()=>{const {runReleaseFeed}=await load(),forbidden=()=>assert.fail('disabled side effect');assert.deepEqual(await runReleaseFeed({readSnapshots:forbidden,readRemoteSnapshot:forbidden,api:forbidden,persistJournal:forbidden}),{status:'disabled'});});
test('incomplete current transition makes zero transport calls and zero exports',async t=>{const f=await fixture(t);f.current.deliveryJournal.complete=false;const result=await f.api.runReleaseFeed(f.options);assert.equal(result.status,'waiting');assert.equal(f.remote.calls.length,0);assert.deepEqual(await fs.readdir(f.root),[]);});
test('complete release reuses PC versions and checkpoints candidate before ref mutation',async t=>{const f=await fixture(t);f.remote.beforePatch=()=>{const p=f.persisted.at(-1).pending;assert.ok(p.candidateCommit);assert.equal(p.phase,'ref_update_in_flight');};const r=await f.api.runReleaseFeed(f.options);assert.equal(r.status,'confirmed');assert.equal(commits(f.remote).length,1);assert.ok(r.journal.confirmed.trustedLocalSnapshot);assert.deepEqual(await fs.readFile(path.join(r.exported.assetDirectory,hash(syntheticPng)+'.png')),syntheticPng);assert.equal(f.persisted.at(-1).pending,null);});
test('unchanged release is a noop after mobile feedback advances without erasing remote review',async t=>{const f=await fixture(t),first=await f.api.runReleaseFeed(f.options),remote=await f.remote.read();f.remote.state=feedback(remote.state);const before=structuredClone(f.remote.state);f.remote.calls=[];const next=await f.api.runReleaseFeed({...f.options,journal:first.journal,outputDirectory:path.join(f.root,'again')});assert.equal(next.status,'noop');assert.deepEqual(f.remote.state,before);assert.equal(writes(f.remote).length,0);});
test('new round archives latest pinned feedback and skips verified identical PNG blob upload',async t=>{const f=await fixture(t),first=await f.api.runReleaseFeed(f.options),remote=await f.remote.read();f.remote.state=feedback(remote.state);const old=structuredClone(f.remote.state);f.input.rows[0].reviewRound='next-round';f.input.reviewRound='next-round';f.current=snapshots(f.input);f.remote.calls=[];const next=await f.api.runReleaseFeed({...f.options,journal:first.journal,outputDirectory:path.join(f.root,'next')});assert.equal(next.status,'confirmed');assert.deepEqual(next.exported.state.history[0].manifest,old.manifest);assert.deepEqual(next.exported.state.operations,old.operations);assert.equal(next.exported.state.manifest.entries[0].review,null);const posts=f.remote.calls.filter(c=>c.method==='POST'&&c.url.endsWith('/git/blobs'));assert.equal(posts.length,1);assert.ok(f.remote.calls.some(c=>c.url.includes('/git/blobs/')&&c.method==='GET'));});
test('corrupt confirmed remote blob blocks delta publication without mutating ref',async t=>{const f=await fixture(t),first=await f.api.runReleaseFeed(f.options);f.input.rows[0].reviewRound='next-round';f.input.reviewRound='next-round';f.current=snapshots(f.input);f.remote.blobReadsCorrupt=true;f.remote.calls=[];const r=await f.api.runReleaseFeed({...f.options,journal:first.journal,outputDirectory:path.join(f.root,'next')});assert.equal(r.status,'pending');assert.equal(commits(f.remote).length,0);assert.equal(f.remote.calls.filter(c=>c.method==='PATCH').length,0);});
test('lost publication acknowledgement verifies exact candidate without duplicate commit or ref update',async t=>{const f=await fixture(t);f.remote.losePatch=true;const first=await f.api.runReleaseFeed(f.options);assert.equal(first.status,'pending');const candidate=first.journal.pending.candidateCommit;assert.equal(f.remote.head,candidate);f.remote.calls=[];const next=await f.api.runReleaseFeed({...f.options,journal:JSON.parse(JSON.stringify(first.journal))});assert.equal(next.status,'confirmed');assert.equal(next.head,candidate);assert.equal(writes(f.remote).length,0);});
test('lost ref request before application verifies same candidate then retries only ref update',async t=>{const f=await fixture(t);f.remote.failPatch=true;const first=await f.api.runReleaseFeed(f.options);assert.equal(first.status,'pending');f.remote.failPatch=false;f.remote.calls=[];const next=await f.api.runReleaseFeed({...f.options,journal:first.journal});assert.equal(next.status,'confirmed');assert.equal(commits(f.remote).length,0);assert.equal(writes(f.remote).length,1);assert.equal(writes(f.remote)[0].method,'PATCH');});
test('uncertain commit creation stays blocked without creating duplicate commit',async t=>{const f=await fixture(t);f.remote.loseCommit=true;const first=await f.api.runReleaseFeed(f.options);assert.equal(first.status,'pending');assert.equal(first.journal.pending.phase,'commit_in_flight');assert.equal(first.journal.pending.candidateCommit,null);f.remote.calls=[];const next=await f.api.runReleaseFeed({...f.options,journal:first.journal});assert.equal(next.status,'blocked');assert.equal(writes(f.remote).length,0);});
test('missing durable journal callback and untrusted remote baseline refuse publication',async t=>{const f=await fixture(t);await assert.rejects(f.api.runReleaseFeed({...f.options,persistJournal:undefined}),/persist|durable/i);assert.equal(f.remote.calls.length,0);const first=await f.api.runReleaseFeed(f.options);f.remote.calls=[];await assert.rejects(f.api.runReleaseFeed({...f.options,journal:{},outputDirectory:path.join(f.root,'untrusted')}),/trusted|baseline|snapshot/i);assert.equal(writes(f.remote).length,0);assert.ok(first.journal.confirmed);});
test('completion snapshot changing during export refuses publication',async t=>{const f=await fixture(t),read=f.options.readSnapshots;let reads=0;f.options.readSnapshots=async()=>{const s=await read();if(++reads>1)s.deliveryJournal.complete=false;return s;};const r=await f.api.runReleaseFeed(f.options);assert.equal(r.status,'waiting');assert.equal(writes(f.remote).length,0);});
test('journal persistence failure prevents commit creation',async t=>{const f=await fixture(t);f.options.persistJournal=async j=>{if(j.pending?.phase==='commit_in_flight')throw Error('synthetic persistence failure');};const r=await f.api.runReleaseFeed(f.options);assert.equal(r.status,'pending');assert.equal(commits(f.remote).length,0);assert.equal(f.remote.calls.filter(c=>c.method==='PATCH').length,0);});
test('only changed PNG and state blobs are uploaded while old immutable content remains retained',async t=>{const f=await fixture(t),first=await f.api.runReleaseFeed(f.options),changed=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=','base64');f.input.rows[0].reviewRound='changed-round';f.input.rows[0].images[0].sha256=hash(changed);f.input.reviewRound='changed-round';f.current=snapshots(f.input);f.options.store={readOnly:true,list:f.input.store.list,image:async()=> 'data:image/png;base64,'+changed.toString('base64')};f.remote.calls=[];const r=await f.api.runReleaseFeed({...f.options,journal:first.journal,outputDirectory:path.join(f.root,'delta')});assert.equal(r.status,'confirmed');const uploads=f.remote.calls.filter(c=>c.method==='POST'&&c.url.endsWith('/git/blobs'));assert.equal(uploads.length,2);assert.equal(uploads.filter(c=>Buffer.from(c.body.content,'base64').equals(changed)).length,1);assert.equal(uploads.filter(c=>Buffer.from(c.body.content,'base64').equals(syntheticPng)).length,0);assert.equal(Object.keys(r.exported.state.assets).length,2);});
test('candidate byte and parent tampering blocks all recovery writes',async t=>{for(const tamper of ['bytes','parent']){const f=await fixture(t);f.remote.losePatch=true;const first=await f.api.runReleaseFeed(f.options),p=first.journal.pending;if(tamper==='parent')f.remote.commits.get(p.candidateCommit).parents=[{sha:'f'.repeat(40)}];else {const c=f.remote.commits.get(p.candidateCommit),tree=f.remote.trees.get(c.tree.sha),entry=tree.find(e=>e.path==='mobile-review/state.json');f.remote.blobs.set(entry.sha,Buffer.from('{}'));}f.remote.calls=[];const next=await f.api.runReleaseFeed({...f.options,journal:first.journal});assert.equal(next.status,'blocked');assert.equal(writes(f.remote).length,0);}});
test('authenticated feedback descendant confirms candidate without duplicate publication',async t=>{const f=await fixture(t);f.remote.losePatch=true;const first=await f.api.runReleaseFeed(f.options),p=first.journal.pending,c=f.remote.commits.get(p.candidateCommit),state=(await f.remote.read()).state,advanced='f'.repeat(40);f.remote.commits.set(advanced,{sha:advanced,tree:c.tree,parents:[{sha:p.candidateCommit}]});f.remote.head=advanced;f.remote.state=feedback(state);f.remote.calls=[];const r=await f.api.runReleaseFeed({...f.options,journal:first.journal});assert.equal(r.status,'confirmed');assert.equal(r.head,advanced);assert.equal(writes(f.remote).length,0);assert.equal(f.remote.state.manifest.entries[0].review.score,8);});
test('descendant cannot rewind candidate reviews even with legacy applied ledger retained',async t=>{const f=await fixture(t),initial=await f.api.runReleaseFeed(f.options),current=(await f.remote.read()).state;current.manifest.entries[0].review={score:8,note:'Original',checks:{readable:true},decision:'held'};current.manifest.entries[0].revision=1;current.operations.legacy={requestHash:'1'.repeat(64),result:{operationId:'legacy',status:'applied',revision:1}};f.remote.state=current;f.options.criteria={...f.options.criteria,version:'criteria-2'};f.remote.losePatch=true;const pending=await f.api.runReleaseFeed({...f.options,journal:initial.journal,outputDirectory:path.join(f.root,'criteria')});assert.equal(pending.status,'pending');const p=pending.journal.pending,c=f.remote.commits.get(p.candidateCommit),state=(await f.remote.read()).state,advanced='f'.repeat(40);state.manifest.entries[0].review={score:2,note:'Rewound',checks:{readable:true},decision:'held'};f.remote.commits.set(advanced,{sha:advanced,tree:c.tree,parents:[{sha:p.candidateCommit}]});f.remote.head=advanced;f.remote.state=state;f.remote.calls=[];const r=await f.api.runReleaseFeed({...f.options,journal:pending.journal});assert.equal(r.status,'blocked');assert.equal(writes(f.remote).length,0);});
test('ref checkpoint failure prevents ref request and retains replayable candidate',async t=>{const f=await fixture(t),save=f.options.persistJournal;f.options.persistJournal=async j=>{if(j.pending?.phase==='ref_update_in_flight')throw Error('synthetic disk unavailable');await save(j);};const r=await f.api.runReleaseFeed(f.options);assert.equal(r.status,'pending');assert.equal(f.remote.calls.filter(c=>c.method==='PATCH').length,0);const durable=f.persisted.at(-1);assert.equal(durable.pending.phase,'candidate_created');f.remote.calls=[];const recovered=await f.api.runReleaseFeed({...f.options,journal:durable,persistJournal:save});assert.equal(recovered.status,'confirmed');assert.equal(commits(f.remote).length,0);});
test('pending publication from another active collection cannot be replayed',async t=>{const f=await fixture(t);f.remote.failPatch=true;const first=await f.api.runReleaseFeed(f.options);f.input.rows[0].reviewRound='next';f.input.reviewRound='next';f.current=snapshots(f.input);f.remote.calls=[];const r=await f.api.runReleaseFeed({...f.options,journal:first.journal});assert.equal(r.status,'blocked');assert.equal(writes(f.remote).length,0);});
test('repository binding in journal refuses reuse for another dedicated repository',async t=>{const f=await fixture(t),r=await f.api.runReleaseFeed(f.options);f.remote.calls=[];await assert.rejects(f.api.runReleaseFeed({...f.options,journal:r.journal,repository:{...repository,repositoryId:456}}),/journal|repository/i);assert.equal(f.remote.calls.length,0);});
test('default pinned reader binds approved injected API and validates dedicated repository before export',async t=>{const f=await fixture(t);const r=await f.api.runReleaseFeed({...f.options,readRemoteSnapshot:undefined});assert.equal(r.status,'confirmed');assert.ok(f.remote.calls.some(c=>c.url===prefix));assert.ok(f.remote.calls.some(c=>c.url===prefix+'/git/commits/'+firstHead));});
function failKnownPrecommitOnce(f){const api=f.remote.api;let fail=true;f.options.api=async(url,init={})=>{if(fail&&url===prefix&&f.persisted.at(-1)?.pending?.phase==='export_ready'){fail=false;throw Error('synthetic transient repository read');}return api(url,init);};}
test('known precommit transport failure resumes exact prepared export without another namespace or duplicate commit',async t=>{const f=await fixture(t);failKnownPrecommitOnce(f);const first=await f.api.runReleaseFeed(f.options);assert.equal(first.status,'pending');assert.equal(first.journal.pending.phase,'export_ready');assert.equal(commits(f.remote).length,0);const bytes=await fs.readFile(first.exported.stateFile),before=await fs.readdir(f.root);f.remote.calls=[];const next=await f.api.runReleaseFeed({...f.options,journal:JSON.parse(JSON.stringify(first.journal))});assert.equal(next.status,'confirmed');assert.deepEqual(await fs.readdir(f.root),before);assert.deepEqual(await fs.readFile(first.exported.stateFile),bytes);assert.equal(next.exported.outputDirectory,first.exported.outputDirectory);assert.equal(commits(f.remote).length,1);});
test('known precommit resume rejects tampered prepared state or local trusted baseline with zero writes',async t=>{for(const target of ['state','snapshot']){const f=await fixture(t);failKnownPrecommitOnce(f);const first=await f.api.runReleaseFeed(f.options);await fs.writeFile(target==='state'?first.exported.stateFile:first.exported.snapshotFile,'{}');f.remote.calls=[];const next=await f.api.runReleaseFeed({...f.options,journal:first.journal});assert.equal(next.status,'blocked');assert.equal(writes(f.remote).length,0);}});
test('known precommit resume rechecks current canonical store before any publication write',async t=>{const f=await fixture(t);failKnownPrecommitOnce(f);const first=await f.api.runReleaseFeed(f.options),original=f.options.store;f.options.store={...original,list:async()=>{const listing=await original.list();listing.entries[0].current={id:listing.entries[0].id,outputVersion:listing.entries[0].outputVersion,reviewRound:listing.reviewRound,score:2,note:'changed locally'};return listing;}};f.remote.calls=[];const next=await f.api.runReleaseFeed({...f.options,journal:first.journal});assert.equal(next.status,'blocked');assert.equal(writes(f.remote).length,0);});
test('known precommit failure with advanced feedback head requires explicit reexport without stale ledger writes',async t=>{const f=await fixture(t),confirmed=await f.api.runReleaseFeed(f.options),state=(await f.remote.read()).state;f.input.rows[0].reviewRound='next-round';f.input.reviewRound='next-round';f.current=snapshots(f.input);f.options.outputDirectory=path.join(f.root,'next');failKnownPrecommitOnce(f);const first=await f.api.runReleaseFeed({...f.options,journal:confirmed.journal});assert.equal(first.journal.pending.phase,'export_ready');const advanced='f'.repeat(40),c=f.remote.commits.get(f.remote.head);f.remote.commits.set(advanced,{sha:advanced,tree:c.tree,parents:[{sha:f.remote.head}]});f.remote.head=advanced;f.remote.state=feedback(state);const before=structuredClone(f.remote.state);f.remote.calls=[];const next=await f.api.runReleaseFeed({...f.options,journal:first.journal});assert.equal(next.status,'pending');assert.equal(next.reason,'precommit_remote_changed_reexport_required');assert.deepEqual(f.remote.state,before);assert.equal(writes(f.remote).length,0);});
test('known precommit resume revalidates current source PNG hashes before publication',async t=>{const f=await fixture(t);failKnownPrecommitOnce(f);const first=await f.api.runReleaseFeed(f.options);f.options.store={...f.options.store,image:async()=> 'data:image/png;base64,'+Buffer.from('changed source bytes').toString('base64')};f.remote.calls=[];const next=await f.api.runReleaseFeed({...f.options,journal:first.journal});assert.equal(next.status,'blocked');assert.equal(writes(f.remote).length,0);});
test('commit checkpoint rejection once restores known precommit phase for durable retry',async t=>{for(const saveBeforeThrow of [false,true]){const f=await fixture(t),save=f.options.persistJournal;let reject=true;f.options.persistJournal=async j=>{if(reject&&j.pending?.phase==='commit_in_flight'){reject=false;if(saveBeforeThrow)await save(j);throw Error('synthetic one-shot checkpoint rejection');}await save(j);};const first=await f.api.runReleaseFeed(f.options);assert.equal(first.status,'pending');assert.equal(commits(f.remote).length,0);const durable=f.persisted.at(-1);assert.equal(durable.pending.phase,'export_ready');assert.equal(durable.pending.candidateCommit,null);assert.equal(durable.pending.treeSha,null);f.remote.calls=[];const resumed=await f.api.runReleaseFeed({...f.options,journal:durable});assert.equal(resumed.status,'confirmed');assert.equal(commits(f.remote).length,1);}});
