import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';
import {syntheticInputs} from '../pc/synthetic-fixture.mjs';import {version} from '../../../desktop/post-review-store.cjs';
import {createPcGithubTransport,readPinnedReviewState} from '../pc/github-transport.mjs';import {createGithubAdapter} from '../app/github-adapter.js';
import {createFixtureFeedbackTransaction} from '../pc/feedback-transaction.mjs';import {mockReviewGithub} from './helpers/mock-review-github.mjs';
const load=()=>import('../pc/review-pipeline.mjs');
const repository={owner:'synthetic-owner',repo:'private-pipeline-fixture',repositoryId:789,private:true,dedicatedReviewRepository:true,branch:'mobile-review/data',excludedRepositories:['synthetic-owner/bridge-fixture']};
function completion(input){return {pointer:{active:true,wholeCollectionRegenerated:true,reviewRound:input.reviewRound,posts:1,pages:1},report:{reviewRound:input.reviewRound,deliveryStatus:'complete',processed:1,entries:input.rows.map(r=>({...r,status:'generated'}))},deliveryJournal:{reviewRound:input.reviewRound,complete:true}};}
async function fixture(t){
 const root=await fs.mkdtemp(path.join(os.tmpdir(),'pc-feedback-fixture-'));t.after(async()=>{const rel=path.relative(os.tmpdir(),root);assert(rel&&!rel.startsWith('..'));await fs.rm(root,{recursive:true,force:true});});
 await fs.writeFile(path.join(root,'.mobile-feedback-fixture.json'),JSON.stringify({schemaVersion:1,syntheticOnly:true}));
 const input=syntheticInputs(),feedbackFile=path.join(root,'canonical-feedback.json');await fs.writeFile(feedbackFile,JSON.stringify({schemaVersion:1,recordType:'user_post_quality_feedback',reviewRound:input.reviewRound,evaluations:[]}));
 const remote=mockReviewGithub(repository),api=createPcGithubTransport({enabled:true,repository,getAccessToken:async()=> 'synthetic-access',fetchImpl:remote.fetch});let journal={};
 const persistJournal=async j=>{const file=path.join(root,'feed-journal.json'),temp=file+'.tmp',handle=await fs.open(temp,'w');try{await handle.writeFile(JSON.stringify(j));await handle.sync();}finally{await handle.close();}await fs.rename(temp,file);journal=JSON.parse(await fs.readFile(file,'utf8'));};
 const tx=createFixtureFeedbackTransaction({enabled:true,syntheticFixture:true,allowedFixtureWorkspace:os.tmpdir(),fixtureRoot:root,feedbackFile,readSnapshots:async()=>({rows:input.rows,criteria:input.criteria,reviewRound:input.reviewRound,trustedLocalSnapshot:journal.confirmed.trustedLocalSnapshot})});
 const store={...input.store,list:async()=>{const listing=await input.store.list(),data=JSON.parse(await fs.readFile(feedbackFile,'utf8'));for(const e of listing.entries)e.current=data.evaluations.find(v=>v.id===e.id&&v.outputVersion===e.outputVersion&&v.reviewRound===input.reviewRound)||null;return listing;}};
 let supplyQueue=Promise.resolve();const withSupplyLock=fn=>{const r=supplyQueue.then(fn);supplyQueue=r.catch(()=>{});return r;};
 const m=await load(),options={enabled:true,dataTransferApproved:true,canonicalMergeApproved:true,repository,api,readSnapshots:async()=>completion(input),readJournal:async()=>structuredClone(journal),persistJournal,withSupplyLock,supplyLockContract:{allFeedWriters:true},store,criteria:input.criteria,allowedOutputRoot:root,feedbackTransaction:tx};
 const pipeline=m.createPcReviewPipeline(options);return {root,input,feedbackFile,remote,api,pipeline,options,get journal(){return journal;}};
}
function mobileOperation(manifest,id='synthetic-review',baseRevision=0){const e=manifest.entries[0];return {operationId:id,id:e.id,outputVersion:e.outputVersion,reviewRound:e.reviewRound,criteriaVersion:manifest.criteria.version,baseRevision,kind:'review',payload:{score:9,note:'Synthetic end-to-end memo',checks:{readable:true},decision:'publish_approved'},deviceId:'synthetic-device',createdAt:'2026-10-08T00:00:00.000Z'};}
test('pipeline default-off and separate transfer/merge approvals perform no callbacks',async()=>{const m=await load(),forbidden=()=>assert.fail('disabled callback');const p=m.createPcReviewPipeline({api:forbidden,readSnapshots:forbidden,readJournal:forbidden,feedbackTransaction:{importFeedback:forbidden}});assert.deepEqual(await p.supplyOnce(),{status:'disabled'});assert.deepEqual(await p.importOnce(),{status:'disabled'});const q=m.createPcReviewPipeline({enabled:true,dataTransferApproved:true,canonicalMergeApproved:false});assert.deepEqual(await q.importOnce(),{status:'disabled'});});
test('complete synthetic PC release travels through mock transport/mobile review into one atomic canonical commit',async t=>{const f=await fixture(t);const supplied=await f.pipeline.supplyOnce({outputDirectory:path.join(f.root,'release')});assert.equal(supplied.status,'confirmed');const mobile=createGithubAdapter({approved:true,dedicatedReviewRepository:true,...repository,api:f.api});const manifest=await mobile.request('/v1/review/manifest'),op=mobileOperation(manifest);assert.equal((await mobile.request('/v1/review/operations',{method:'POST',body:JSON.stringify(op)})).status,'applied');const imported=await f.pipeline.importOnce();assert.equal(imported.status,'committed');const data=JSON.parse(await fs.readFile(f.feedbackFile,'utf8'));assert.equal(data.evaluations[0].score,9);assert.equal(data.evaluations[0].outputVersion,version(f.input.rows[0]));assert.equal('decision' in data.evaluations[0],false);assert.equal(data.mobileImport.decisionRecords[0].decision,'publish_approved');const before=await fs.readFile(f.feedbackFile);assert.equal((await f.pipeline.importOnce()).status,'unchanged');assert.deepEqual(await fs.readFile(f.feedbackFile),before);});
test('lost mobile acknowledgement uses original operation and preserves concurrent canonical edit',async t=>{const f=await fixture(t);await f.pipeline.supplyOnce({outputDirectory:path.join(f.root,'release')});const mobile=createGithubAdapter({approved:true,dedicatedReviewRepository:true,...repository,api:f.api}),manifest=await mobile.request('/v1/review/manifest'),op=mobileOperation(manifest);f.remote.loseNextRef=true;await assert.rejects(mobile.request('/v1/review/operations',{method:'POST',body:JSON.stringify(op)}));const commits=f.remote.commits.size;assert.equal((await mobile.request('/v1/review/operations',{method:'POST',body:JSON.stringify(op)})).status,'duplicate');assert.equal(f.remote.commits.size,commits);const original=JSON.parse(await fs.readFile(f.feedbackFile));original.evaluations.push({id:op.id,outputVersion:op.outputVersion,reviewRound:op.reviewRound,score:2,note:'Independent PC edit',updatedAt:'2026-10-08T00:00:01.000Z'});await fs.writeFile(f.feedbackFile,JSON.stringify(original));const bytes=await fs.readFile(f.feedbackFile);const result=await f.pipeline.importOnce();assert.equal(result.status,'conflict');assert.deepEqual(await fs.readFile(f.feedbackFile),bytes);});
test('new completed round receives blank mobile score and old feedback cannot affect its canonical file',async t=>{const f=await fixture(t);await f.pipeline.supplyOnce({outputDirectory:path.join(f.root,'release')});const mobile=createGithubAdapter({approved:true,dedicatedReviewRepository:true,...repository,api:f.api}),manifest=await mobile.request('/v1/review/manifest');await mobile.request('/v1/review/operations',{method:'POST',body:JSON.stringify(mobileOperation(manifest))});await f.pipeline.importOnce();f.input.rows[0].reviewRound='next-fixture-round';f.input.reviewRound='next-fixture-round';const next=await f.pipeline.supplyOnce({outputDirectory:path.join(f.root,'next')});assert.equal(next.status,'confirmed');const fresh=await mobile.request('/v1/review/manifest');assert.equal(fresh.entries[0].review,null);assert.notEqual(fresh.entries[0].outputVersion,manifest.entries[0].outputVersion);await fs.writeFile(f.feedbackFile,JSON.stringify({schemaVersion:1,recordType:'user_post_quality_feedback',reviewRound:f.input.reviewRound,evaluations:[]}));const bytes=await fs.readFile(f.feedbackFile);const result=await f.pipeline.importOnce();assert.equal(result.status,'unchanged');assert(result.proposal.stale.length>0);assert.deepEqual(await fs.readFile(f.feedbackFile),bytes);const pinned=await readPinnedReviewState({enabled:true,repository,api:f.api});assert.equal(pinned.state.history[0].manifest.entries[0].review.score,9);});
